### ISSUE TITLE
Empty result

### ISSUE THREAD

**Issue by fortael** [gruhn/vue-qrcode-reader#1]
Hello. I hope this package will be useful for me, but...
When DOM is ready i see only slot text. Seems it's even mounted 

![image](https://user-images.githubusercontent.com/16315079/31577593-c46b2318-b13b-11e7-8d0d-ba2090953481.png)
 
but i don't see anything. No any error, just empty.

Also would be great to have online demo for this. 
(and my respect for using BEM ;) )

**Comment by gruhn** [comment]
Yeah, this package is totally broken. I really wanted to have it fixed a long time ago but you're giving me new motivation. I'll deal with it in the following days :wink:

**Comment by gruhn** [comment]
Ok, I published a few updates to npm. Note that I changed the hole API.

I'm also trying to create a demo using GitHub pages but for some reason I can't make it work online. You might be interested in the source code anyway: https://github.com/gruhn/vue-qrcode-reader-demo/blob/master/src/components/TheQrcodeReaderDemo.vue

**Comment by fortael** [comment]
Yes, great. I like how does it work, thank you. Seems i faced same problem - it only works with **https**. Now is our project in development mode but soon i'll change it to https. Your component will be very useful. Appreciate your help. Thank you
