### ISSUE TITLE
Scan image in file or data URL?

### ISSUE THREAD

**Issue by p3v9d5ui** [gruhn/vue-qrcode-reader#100]
Is it possible to use any of these components without user interaction? I'm looking for a qrcode scanner which will accept a file path or data URL, which I already have.

**Comment by gruhn** [comment]
No this is not possible. I think this isn't too hard to implement yourself though.

This component is using [jsQR](https://github.com/cozmo/jsQR) under the hood. You just need to get your hands on an [ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) instance based on your file path or data url. Once you have that you can pass it to jsQR. 

Here you'll find some hints on how get ImageData from various sources:

https://github.com/gruhn/vue-qrcode-reader/blob/8170bb13f7558dcd8223ed22728fd1c7b6e96600/src/misc/image-data.js
