### ISSUE TITLE
Throw error when QrcodeCapture fails

### ISSUE THREAD

**Issue by dakshshah96** [gruhn/vue-qrcode-reader#101]
According to the documentation, this is how `QrcodeCapture` behaves currently:

> However, if no QR code is pictured or an error occurs, decode silently fails.

Is it possible to throw an error when a QR code is not detected in a captured image in the current version of the library?

**Comment by gruhn** [comment]
Use the `detect` event instead 🙂 The event payload is a `Promise` which rejects in case of errors (just like the `init`event of `QrcodeStream`).

**Comment by dakshshah96** [comment]
Thanks for the help! Worked perfectly 🎉
