### ISSUE TITLE
Disable multiple image selection in QrcodeCapture

### ISSUE THREAD

**Issue by dakshshah96** [gruhn/vue-qrcode-reader#103]
Is there a way to disable multiple image selection in the `QrcodeCapture` file picker component?

If not, I'd be more than happy to try contributing to a library that I've extensively used for the past couple of months in my applications!

**Comment by gruhn** [comment]
Nice to hear that :grinning:

The `input` is the root element of `QrcodeCapture`. That's why any HTML attribute on the component will override/be added to the `input`. 

Removing the `multiple` attribute should do the trick:

```html
<qrcode-capture :multiple="false">
```

**Comment by dakshshah96** [comment]
Oops, didn't know it was this simple 😝 

Thanks, that worked 🎉
