### ISSUE TITLE
Allow to plug in other detection algos?

### ISSUE THREAD

**Issue by uwolfer** [gruhn/vue-qrcode-reader#109]
I like to modularized structure of the code, especially the 'misc' folder. While looking into it, I've noticed that there are just a few lines of code are qr-code specific.

Some time ago I've done an experiment: I've created an app which allows scanning MRZ (machine readable zones of passports / ID cards). That implementation just allowed uploading an image, see: https://github.com/uwolfer/mrz-scanner

Now the idea: I think it would be quite easy to integrate MRZ scanning into your component: instead of "hardcoding" the "jsQR" stuff in worker.js, we could pass a custom detection function which just needs to return the scanned result in a defined format. That would open the doors for any real time scanning which is handled really nice with workers in your impl. For example, it would also allow using any other QR library (as there are two pull requests are available). You can find the relevant detection code of my MRZ experiment here: https://github.com/uwolfer/mrz-scanner/blob/master/src/index.js#L80-L102

What do you think about this idea? Have I missed important parts of the code?

**Comment by gruhn** [comment]
I like your idea and I was thinking about this too for a while. My only excuse for not pushing forward in this direction is that the project is so strongly "branded" around QR code detection. I think it would be awkward if a package that is meant to scan anything is still called "*-qrcode-reader". The main effort probably lies in rewriting documentation, adjusting the demos, new logo!, ... 


In principle, those are minor issue though. In the long run we could create a dedicated package and derive "vue-qrcode-reader" from that. 


The only technical issue I can think of right now, is the `track` property. Functions you pass receive a `location` object which is basically returned as-is from jsQR. The object has fields like `topLeftFinderPattern`. Finder patterns are those three big squares in the corners of every QR code. So this is actually some QR code specific stuff that is exposed over the components API. Also not a big deal but something we should keep in mind.

**Comment by uwolfer** [comment]
> In principle, those are minor issue though. In the long run we could create a dedicated package and derive "vue-qrcode-reader" from that. 

That makes sense to me. I do not have a good name for the "base" library right now, but it could be a nice framework for any real time image / stream "reader" / "scanner". Probably this base library would not even need to depend on Vue.js - but I'm not sure here. But I think we could extract some more algo related things out of the Vue component into a vanilla class in "misc" folder.

> The only technical issue I can think of right now, is the track property.

This tracking functionality could also be useful when scanning MRZ. In that case, it would also be a square. But I could also imagine other use cases like a face detection scanner which would be more than a square. Probably use a generic data structure like a list of `shape`s, where a `shape` contains a list of `coordinate`s which are connected per shape with a line in the default tracking implementation? I think it would be quite straight forward to just map the location output of jsQR to a generic structure. Also, the result `content` which is a string now could be a more sophisticated object (in case of MRZ for example an object which contains the raw-text-result and a parsed content which is a nested object itself).

**Comment by gruhn** [comment]
I think for now we should experiment a little bit and try to replace jsQR with several different libraries (for MZR, face detection and so, as you mentioned) and find out where the challenges are.

**Comment by gruhn** [comment]
Made a quick update to the API docs: 

https://gruhn.github.io/vue-qrcode-reader/api/QrcodeStream.html#worker

Feedback greatly appreciated!

**Comment by gruhn** [comment]
@uwolfer 

Maybe instead of a constructor function, we should demand a string path to a worker script. So templates look somewhat like this: 
```html
<qrcode-stream worker="path/to/worker.js"></qrcode-stream>
```
This saves you an extra step and it might be slightly less confusing. 
On the other hand, I don't think this approach play well with inline workers or module workers.

As already mentioned, my second concern regards the [track property](https://gruhn.github.io/vue-qrcode-reader/api/QrcodeStream.html#track). Right now it's tightly coupled to the output of `jsQR`. Track functions get a location object as the first argument. The structure of this object is defined by jsQR:

```js
{
  topLeftCorner: { x, y },
  topRightCorner: { x, y },
  bottomLeftCorner: { x, y },
  bottomRightCorner: { x, y },
  topLeftFinderPattern: { x, y },
  topRightFinderPattern: { x, y },
  bottomLeftFinderPattern: { x, y }
}
```

If you plug in a different worker, you have to convert, whatever location information this one provides, into the jsQR structure. This is kind of awkward. Especially the `xxxxxxFinderPattern` fields are very QR code specific. Also, some scanning libraries don't provide location information at all.

Maybe we can define some kind of general scanner-object-interface which is not only handling the image processing but also the tracking. Then, instead of a worker, we would expect such a scanner-object.

**Comment by vividy** [comment]
Hello,

I've tried to implement an BareCode reader as a worker.
This implementation seems to be similar to JsQr implementation: https://mubaidr.js.org/Javascript-Barcode-Reader/

First i have tried to reimplement JsQr:
Scan.Vue
```
<QrcodeStream :worker="worker" @decode="onDecode"></QrcodeStream>
<script src="./js/scan.js"></script>

```
./js/scan.js
```
import Worker from './myJsQr.js'
export default {
  props: {
    worker: {
      type: Function,
      default: Worker
    }
  },
  methods: {
    onDecode (decodedString) {
      console.log(decodedString)
    }
  }
}
```
./js/myJsQr.js is the same than your /src/worker/jsqr.js I've just added some console.log


But this implementation work with the default worker...
Did i something wrong?

**Comment by gruhn** [comment]
`src/worker/jsqr.js` doesn't actually export anything. The file is preprocessed by webpack using:

https://github.com/webpack-contrib/worker-loader

Only when you set this up yourself, you can do: `import Worker from ...`.

I plan to make this more convenient but I'm too busy at the moment.

Side note: 
The author of the library, you referenced, states: 

> This script does not implement logic to locate/rotate barcode in the given image.
> 
> Make sure the barcode image is the only thing in the image. Otherwise this script will most probably fail.

This means that this library is not able to process camera frames. It won't work with `QrcodeStream`. It might partially work with `QrcodeCapture` and `QrcodeDropZone` though.

**Comment by RacerDelux** [comment]
@gruhn 
I would love to see the default worker here written in TS following your example. That would be very useful.

**Comment by w-a-b** [comment]
Could there be an addition worker-options prop that could be included in the worker events?
I would like to have a custom worker that behaves a bit differently than the default, for example I don't want a hard-coded `inversionAttempts: "dontInvert"`, but allow the user to select this and the ability to change the behavior runtime.

**Comment by chao** [comment]
I have successful implemented a wasm barcode reader with vue-qrcode-reader. I'm using a wasm from the article "https://barkeywolf.consulting/posts/barcode-scanner-webassembly/".

**Comment by gruhn** [comment]
@chao Very interesting, thank you. I think I'm also going to tinker with ZBar a bit. This looks really promising.
