### ISSUE TITLE
[Feature] Set default camera.

### ISSUE THREAD

**Issue by canhkieu** [gruhn/vue-qrcode-reader#11]
I use this library on the device with 2 cameras (Front and Back). Could add a feature to set default camera. Or how to set default camera in code. Thank

**Comment by gruhn** [comment]
This component SHOULD always default to the rear camera.

I assume you tested the component on a device and it used the front camera instead? If so, check if you have the same problem on the demo page and tell me your device name, OS version and browser version.

Or do you really want to be able to manually configure which camera is used? If this is what you mean, please explain your use case.

Thanks!

**Comment by canhkieu** [comment]
I building a Kiosk Web App on Android Tablet has 2 camera. The member need to check-in by Qr-code on front-camera. I tested on some android table, some time it's scan rear camera, some time it's scan front camera. I need to have a solution to turn on rear|front on device.

**Comment by gruhn** [comment]
Hmmm... I don't get it. Why do want your users to check-in using the front camera? I would expect that this is a little bit cumbersome?

**Comment by canhkieu** [comment]
This is our demo devices. It has two camera. User will check-in from front-camera.
![tour-ct](https://user-images.githubusercontent.com/136077/33703033-d52bce90-db58-11e7-807a-57aea935ed47.png)

**Comment by gruhn** [comment]
Ok, now I get it. I'll deal with it :wink:

**Comment by gruhn** [comment]
I opened a PR. Install it via 
```bash
yarn add git+https://github.com/gruhn/vue-qrcode-reader.git#constraint-prop
# or
npm install --save git+https://github.com/gruhn/vue-qrcode-reader.git#constraint-prop
```
and check if this suits your needs. 

I also updated the README in this PR. Refer to that for usage instructions.

**Comment by canhkieu** [comment]
So fast and very details. Thanks bro.

**Comment by gruhn** [comment]
sure :grin: :+1:

**Comment by gruhn** [comment]
now also on NPM
