### ISSUE TITLE
`StreamApiNotSupportedError` thrown instead of `NotSupportedError´

### ISSUE THREAD

**Issue by Lazy3valuation** [gruhn/vue-qrcode-reader#110]
Hello guys! I'm trying to run the demo found on 
https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html
but I get "ERROR: Stream API is not supported in this browser"
I'm using Chrome for Android, in my Huawei p10 lite. Latest version, updated yesterday...
This site says I should support it, why am I getting this error? 
https://caniuse.com/#feat=stream
My website works pretty well on my pc with Firefox and my webcam.
(Mobile Chrome version 74.0.3729.136, yeah, I uninstalled and reinstalled chrome.)
EDIT: Forgot to add that this does not works even in a Samsung s8, and a Xiaomi. But everything works in the Demo page. They all use Chrome for android.

**Comment by gruhn** [comment]
I just checked the demo page on _Samsung Galaxy S8_ and _Samsung Galaxy S8+_ with _Chrome 72_. I don't get any error messages. 

Can you provide more info? Any console output maybe?

**Comment by Lazy3valuation** [comment]
Well, this doesn't work with Chrome on PC. I suppose it's because my website has not (yet) an SSL certificate. I'm creating one with Certbot, to see if that works.
I've uninstalled chrome on my telephone and it has been restore to a very old version, now the error is secure context required (https or localhost).
If SSL is really the cause of this error, it should not say "Stream API is not supported in this browser" in new versions...
I'll try to update my website to SSL afap. I'll update this post if the error persists.

**Comment by gruhn** [comment]
> I'm trying to run the demo found on [...] but I get "ERROR: [...]

> But everything works in the Demo page.

> The website works pretty well on my pc with my webcam.

> Well, this doesn't work with Chrome on PC

I'm confused. Where exactly is the component working for you and where not?
Can you please make this clear, somewhat like this:

 * Samsung S8 -> does not work -> on the demo page
 * Chome on PC -> does work -> on my website
 * Huawei p10 ...
 * ...

**Comment by Lazy3valuation** [comment]
Firefox on PC -> works both on demo page and my website
Chrome on PC -> works on demo page -> does not work on my website
Chrome on all android phones in my home -> works on demo page -> does not work on my website

**Comment by Lazy3valuation** [comment]
Sorry, missclicked and closed the issue...
Firefox on PC -> works on demo page ->works on my website
Chrome on PC -> works on demo page -> does not work on my website
Chrome on every android phone at my home -> works on demo page -> does not work on my website

**Comment by gruhn** [comment]
Ok so it always works on the demo page?  

So the issue is then that you get the Stream-API error message in newer versions of Chrome although it should be the SSL error message?

**Comment by Lazy3valuation** [comment]
Yes, it always works in the demo page. 
I think the problem is the SSL certificate.
Right now, I'm trying to make my vue project work with https... I'll update the thread when I get that working.

**Comment by Lazy3valuation** [comment]
I'm having some problems compiling my vue app with npm run build: it shows me a blank page with no errors in the developer console, so it may take a while to see if the error was the SSL certificate.

**Comment by Lazy3valuation** [comment]
Yes, the problem was the HTTPS. What confused me was the wrong error written in the webpage.. But anyway, as it's written in the docs, always use HTTPS with Chrome. Any Chrome, mobile or not.

**Comment by gruhn** [comment]
You're right. This shouldn't be happening 🤔

**Comment by Lazy3valuation** [comment]
> 
> 
> Yes, the problem was the HTTPS. What confused me was the wrong error written in the webpage.. But anyway, as it's written in the docs, always use HTTPS with Chrome. Any Chrome, mobile or not.

Exactly. 🤔

**Comment by Lazy3valuation** [comment]
Do you need any screenshot of the bug? I think I can still get some console messages/warnings/errors in Chrome for PC. Chrome Mobile should not have the console..
