### ISSUE TITLE
[Feature Request]: pick specific camera by device ID

### ISSUE THREAD

**Issue by Nisgrak** [gruhn/vue-qrcode-reader#111]
Hi! I am making an app with 2 zones to scan, with 2 different cameras.

How can I select the cam I wish to use?

In #92 you suggest pass an object to camera prop, but with the lasts updates that didn't work.

Thanks and amazing lib :D

**Comment by gruhn** [comment]
Jep, this is not possible anymore.

Can you elaborate your use case in detail 🙂  Maybe there is a different approach.

**Comment by Nisgrak** [comment]
It's a program to non-strict in-out report program. Each user has a card with a code.

User pass the card if they came late, but at the same time other user could gone, passing his card.

The operator needs to change the operation performed when a code gets detected, but the possible human error it's too high, because of that I want 2 cams, each for one zone, one exit other entry.

**Comment by gruhn** [comment]
I see... 

The camera-prop got refactored because passing an entire `MediaStreamConstraints` object turned out to be verbose, error prone, hard to understand and especially totally unnecessary for most use cases.

Additionally to the current allowed input values for the camera-prop (`auto`, `front`, `rear`, `off`) we could *again* allow device IDs. As explained in #94 you could use [navigator.mediaDevices.enumerateDevices()](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices) and get your hands on the device ID of the specific camera you want to request.

I'm not convinced this is worth it though. I'd like to wait if other people come up with similar requirements.

In the meantime I suggest you either downgrade to v1.4.2 or make a fork and overwrite this [computed property](https://github.com/gruhn/vue-qrcode-reader/blob/8c5090527fa71999f1e188aaf1e2b7ed5a7e7e20/src/components/QrcodeStream.vue#L97-L126).

**Comment by alexcos20** [comment]
count me in for the same request.

My problem is simpler...

I use a webcam to scan some qrcode for a warehouse.   For desktop pc, it works perfect.
But somebody came in with a laptop with embedded webcam, and this is the default device, no matter what USB port i will use to plug in the external webcam.

The app still works, but is very hard to take a package and move it in the front of the laptop to scan the qrcode, rather that moving the webcam over the package.

Thanks!

**Comment by rayko92** [comment]
Yep, I need this feature and I don't want to stuck in the v1.4 :/

Thanks a lot, I love u, I appreciate this lib so much.

**Comment by Nisgrak** [comment]
Where I can see the documentation for the v1.4? 
While I wait to the update I stuck in that version.

Thanks!

**Comment by gruhn** [comment]
The source code of the documentation/demo page is tracked on the branch `gh-pages-src`. Browse the files prior to the v2 update commit to view the full old documentation:

https://github.com/gruhn/vue-qrcode-reader/tree/6449e1153f5e116d2d80990b83df1633df819e39

Here is a direct link to the v1.4 documentation of `QrcodeStream`:

https://github.com/gruhn/vue-qrcode-reader/blob/6449e1153f5e116d2d80990b83df1633df819e39/docs/api/QrcodeStream.md

**Comment by snsanich** [comment]
Hi.

In project we use app to scan qrcode. We install app on client's computers and mobile phones. We also provide our mobile phones if the app is not working on their devices. On their devices precision of default camera every fourth case is not ok.

On April 2019 I implemented switcher beetween front and back camera, equal to camera-prop 'front', 'rear'. It did not work, though now I do not have versions of phones where I failed to switch cameras. Then I started to load a list of cameras of device and change them if we need different devices.

I use deviceID anyway, cause: we have more, then 300 client devices. Each our mobile device cost us at least 50$.

For my case I prefer if my partner is able to fix camera without updating sources, by choosing another DeviceID.

**Comment by gruhn** [comment]
### 1)

> On their devices precision of default camera every fourth case is not ok.

So, are you saying that 3 out of 4 devices use the wrong camera by default? What are they using instead? The front camera although it should be the rear camera?

If that's the case this is a bug of the component. It should consistently pick the rear camera if that is possible. You shouldn't have to _fix this_ by passing the device ID manually.

### 2)

> It did not work, though now I do not have versions of phones where I failed to switch cameras.

What are you saying in this sentence?

 _It did not work_ **but now** you _do not_ have phones where switching cameras fails?

### 3)

> I use deviceID anyway, cause: we have more, then 300 client devices. Each our mobile device cost us at least 50$.

Can you go into detail, what kind of project this is? Why do you buy the devices for your clients?

I don't understand your reasoning here: "we have 300+ clients devices **AND** each costs 50$+ **THEREFORE** we use device ID"

**Comment by snsanich** [comment]
> ### 1)
> > On their devices precision of default camera every fourth case is not ok.
> 
> So, are you saying that 3 out of 4 devices use the wrong camera by default? What are they using instead? The front camera although it should be the rear camera?

Here I tried to say: quality of picture of rear camera were not suitable to make scan of QRCode. The size of QRcode we have is 1.5cm.

> 
> If that's the case this is a bug of the component. It should consistently pick the rear camera if that is possible. You shouldn't have to _fix this_ by passing the device ID manually.
> 

It might be bug of software, I did not investigate the issue enough.

> ### 2)
> > It did not work, though now I do not have versions of phones where I failed to switch cameras.
> 
> What are you saying in this sentence?

I had phones where switching cameras fails on April 2019. I mean I did not make a list of the devices, of their OS.

> 
> _It did not work_ **but now** you _do not_ have phones where switching cameras fails?
> 
> ### 3)
> > I use deviceID anyway, cause: we have more, then 300 client devices. Each our mobile device cost us at least 50$.
> 
> Can you go into detail, what kind of project this is? Why do you buy the devices for your clients?
> 

The project is a copy of gympass.com, but we use PWA application to register card holders and we register them by scanning QRCode and verifying identity.

> I don't understand your reasoning here: "we have 300+ clients devices **AND** each costs 50$+ **THEREFORE** we use device ID"

Here I meant that I have broad list of different devices that use the library.

**Comment by gruhn** [comment]
> quality of picture of rear camera were not suitable to make scan of QRCode. The size of QRcode we have is 1.5cm.

So are you saying there are multiple cameras on these devices and the ones picked by default have poor quality but one of the other cameras would have sufficient quality so you would like to pick that one explicitly by passing the camera-device-ID? 

If that's the case, what kind of device is that? How come it has multiple cameras with such significantly varying quality?

> >If that's the case this is a bug of the component. It should consistently pick the rear camera if that is possible. You shouldn't have to fix this by passing the device ID manually.
>
> It might be bug of software, I did not investigate the issue enough.

So if this would be a bug and it would be fixed, would that resolve your issue?

**Comment by araimbekoff** [comment]
Hi!
Huawei Mate 20 Pro has several cameras. One of them is a telescope camera. This camera is not suitable for scanning, because you need to keep the phone far from the qr code.
Therefore, I would also like to be able to choose a camera by deviceId.

Please help!

**Comment by MartCube** [comment]
Hi!
Many phones today have several cameras ( 3 to 4). 
With using the **prop camera** to auto or rear we often select the wrong camera.
Maybe we can have a second option where we can pick camera by deviceId since as I read that cause you a lot of errors or maybe you can provide us some other solution since this looks a common problem for many users.

**Comment by gruhn** [comment]
Ok, some new thoughts on this. If there would be a `device-id` prop, how would you solve the problem of picking the right ID? If there is a general solution we could build it right into the component. If there isn't, how is this prop helpful?

**Comment by Nisgrak** [comment]
I have a select with a list of the multiples cameras in the device, the user picks and the model is the device-id in the lib(in v1.4.2).

If you want a common solution, maybe should be an optional button inside the cam to select the next other camera. Or maybe to show a dialog with a select but that's probably not follows app style, etc...

**Comment by MartCube** [comment]
> Ok, some new thoughts on this. If there would be a `device-id` prop, how would you solve the problem of picking the right ID? If there is a general solution we could build it right into the component. If there isn't, how is this prop helpful?

This is not ideal solution, but in most of the cases of mobiles with multiple cameras the main camera out of all rear cameras is the last in the **list** of registered cameras. Maybe instead of getting the **first** camera of the given list we have an option to get the **last** camera of the list.

**Comment by gruhn** [comment]
Hey everybody, please check out #179
