### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by michalexvr** [gruhn/vue-qrcode-reader#116]
We have some way to use focus?, our QR codes are really small and the camera does not taking good because the image is blurred. How can we fix it?

**Comment by gruhn** [comment]
I was just browsing the [MediaStream API specification](https://w3c.github.io/mediacapture-image/#focus-mode) and it looks like you can define what they call a _Point of interest_. 

If I understand this correctly, you pass a set of coordinates (e.g. the location where the user tabbed on the screen) and the camera is then auto-focused at this point.

Sounds like exactly what we need right? I'll try to implement this ASAP.

**Comment by michalexvr** [comment]
Yes! Is it!!

**Comment by alqu** [comment]
Hi,

is there any progress on that feature? Does it work as described in the API specs?

Would love to see this feature in action as well.

**Comment by gruhn** [comment]
@alqu turns out not a single browser currently supports this API yet. It's not even mentioned on MDN or Caniuse. The spec is pretty much the only source currently. Sorry, we have to wait until browsers start implementing it.

**Comment by michalexvr** [comment]
I solved for a while using an autofocus camera powered by hardware.

**Comment by gruhn** [comment]
@michalexvr what exactly do mean? Can you elaborate a little bit more?

**Comment by alqu** [comment]
> @alqu turns out not a single browser currently supports this API. It's not even mentioned on MDN or Caniuse. The spec is pretty much the only source currently. Sorry, we have to wait until browsers start implementing it.

OK, you are right. So I use this as it is... Thanks! 👍

**Comment by michalexvr** [comment]
> what exactly do mean? Can you elaborate a little bit more?

This camera (https://www.logitech.com/es-es/product/b525-webcam) supports autofocus by hardware i used this for what i needed.

**Comment by a2exfr** [comment]
Hi. 
I just faced same problem.
What do you think, can it be solved  by changing focus mode or by adjusting the focus manually, for example, with external slider, of course, for those browsers that support it?
