### ISSUE TITLE
Basic environment setup

### ISSUE THREAD

**Issue by Apai08** [gruhn/vue-qrcode-reader#118]
Hi, I'm still in learning process and i'm getting confused how to use this library. I'm using laravel framework, and in need explaination on how to utilize the function. I mean where to put the code of this qr code library, what to code in my blade.php file and how to make the relationship between vuejs and laravel. I do go through the fiddle given but still cant get the point. Will appreciate any guide from you. thanks

**Comment by metalmini** [comment]
You will have to use Vue in your project

https://vuejsdevelopers.com/2018/02/05/vue-laravel-crud/

https://github.com/gruhn/vue-qrcode-reader#default-import

**Comment by gruhn** [comment]
I'm not sure about your level of experience but as @metalmini pointed out you should first get comfortable with use Vue+Laravel in general.

Laravel comes with a lot of stuff pre-configured so you don't need to go the old school path (declaring all your dependencies using script tags) which is presented in the fiddle. 

Laravel allows you to author [Vue components in dedicated files](https://laravel.com/docs/5.8/frontend#writing-vue-components). Each demo on [the demo page](https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html) is such a component file. So you can just [copy one of these](https://github.com/gruhn/vue-qrcode-reader/tree/gh-pages-src/docs/.vuepress/components/demos) to get started.

Now, where to put the code of the library? You don't have to download it manually or include a link to a JS file somewhere. You should use `npm` which is a command line tool that's kind of doing the downloading for you.

I know this is a lot of mental overhead if you have never used anything like `npm` before but it's a vital part of the JavaScript ecosystem
