### ISSUE TITLE
QrcodeCapture (via upload qrcode image) is available on ie11?

### ISSUE THREAD

**Issue by bongjinpark1** [gruhn/vue-qrcode-reader#120]
Windows 10
IE version : 11.1.18362.0
Component: QrcodeCapture(and maybe QrcodeDropzone)

Hi.

On readme.md, browser support of QrcodeCapture is ie 10+, but do not available in ie11.

On ie11, file input not showing.

Is not available on ie11?

Thanks.

**Comment by gruhn** [comment]
So the component is not being rendered? Any console output?

**Comment by bongjinpark1** [comment]
> So the component is not being rendered? Any console output?

Component is not being rendered.

On your demo page.
![Windows 10 2019-06-26 08-44-15](https://user-images.githubusercontent.com/42724459/60141073-de5a9600-97ee-11e9-9528-aa81617d3623.png)

On console
![Windows 10 2019-06-26 08-44-36](https://user-images.githubusercontent.com/42724459/60141075-e0245980-97ee-11e9-8a66-bf9872900ae7.png)

On DOM explorer
![Windows 10 2019-06-26 08-45-31](https://user-images.githubusercontent.com/42724459/60141079-e1ee1d00-97ee-11e9-987f-62ac728b9889.png)

Thanks to your support.

**Comment by gruhn** [comment]
Ok I think the "Syntax error" is caused by an arrow function which IE 11 doesn't support. I'll try to fix it.
