### ISSUE TITLE
prop "camera" in QrcodeStream does not accept String

### ISSUE THREAD

**Issue by dakshshah96** [gruhn/vue-qrcode-reader#123]
This is how I'm using the QrcodeStream component in my web app:

```
<qrcode-stream @init="onInit" @decode="onDecode" :camera="qrPaused ? 'off' : 'rear'"></qrcode-stream>
```

I assign the string 'off' or 'rear' based on the value of `qrPaused` to the `camera` prop but get the following error:

```
[Vue warn]: Invalid prop: type check failed for prop "camera". Expected Object, Boolean, got String.
```

**Comment by gruhn** [comment]
Are you using `vue-qrcode-reader` prior to version 2 ? Since version 2 the camera prop accepts strings. In v1.4.2 and below objects/booleans were expected.

**Comment by dakshshah96** [comment]
I just updated `vue-qrcode-reader` to the latest version. My `package.json` also says `"vue-qrcode-reader": "^2.0.1"`. Also did `npm install` twice just to make sure.

**Comment by gruhn** [comment]
Can you try to remove your `node_modules` directory and run `npm install` again?

**Comment by dakshshah96** [comment]
That fixed it 🎉 
Should've tried that in the first place.

Sorry for the trouble!

**Comment by gruhn** [comment]
Don't worry 🎉
