### ISSUE TITLE
Inverted colors no longer supported, add as option

### ISSUE THREAD

**Issue by lane-c-wagner** [gruhn/vue-qrcode-reader#124]
My app uses inverted QR codes, Im not stuck unable to upgrade. Why not add a prop that signals to the component that it wants to use inverted images? That way performance isn't compromised but it still works if necessary.

**Comment by gruhn** [comment]
Please elaborate your use case and convince me this is not an edge case. Do you really really need color inverted OR codes?

I seriously dislike components with too many props:
* Props introduce API level complexity
* Props introduce internal complexity. More cases need to be covered, making the hole thing more error prone
* Props can't be removed without breaking backwards compatibility

In the long run we want to allow you to plug in arbitrary scanning libraries (see #109). That why you can scan whatever you want (color inverted QR codes, bar codes, faces maybe, ...). For a quick workaround you can downgrade to v1.4.2 which still supports color inverted QR codes.

**Comment by gruhn** [comment]
Just merged the experimental `worker` prop. Check the discussion at #109
