### ISSUE TITLE
QrcodeCapture won't detect image but QrcodeStream does

### ISSUE THREAD

**Issue by demonskp** [gruhn/vue-qrcode-reader#126]
README.md  said  QrcodeStream is only expect use in https or http://localhost.

So How can I judge QrcodeStream is or not available?

Also, I want to know about the plans for IOS support.

**Comment by gruhn** [comment]
I don't understand your question. 

This is ok:
http://localhost
https://www.example.com
https://192.168.1.1
https://...

Not ok:
http://www.example.com
http://192.168.1.1
http://...


Extending iOS support is impossible so there is no plan to do that.

**Comment by demonskp** [comment]
I am sorry for my bad English.
But your answer really helped me, and I also want to know how to improve the recognition rate of qrcode-capture, it seems difficult to identify the larger photos taken by the phone.

**Comment by gruhn** [comment]
Please share a photo that is not recognized.

**Comment by demonskp** [comment]
![微信图片_20190718151456.jpg](https://upload-images.jianshu.io/upload_images/5927708-5e9d2ec0379abad2.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![微信图片_20190718151513.jpg](https://upload-images.jianshu.io/upload_images/5927708-339e0cf0e49bc04d.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by demonskp** [comment]
thanks for your patience

**Comment by Damanii** [comment]
I'm having a similar issue where the QrcodeStream will capture but the QrcodeCapture will not. Even for very clear ones. Example below

![QR](https://user-images.githubusercontent.com/17342653/63293045-133a1500-c295-11e9-88fd-c97d87d24918.jpg)

**Comment by gruhn** [comment]
This is so weird.

This image fails:
![qrcode_fails](https://user-images.githubusercontent.com/26570572/63300417-7305df80-c2d8-11e9-88a8-8f764ff57fd2.jpg)

This image works:
![qrcode_works](https://user-images.githubusercontent.com/26570572/63300418-739e7600-c2d8-11e9-85e4-6bcbef6da0ed.jpg)

The first one is your image @Damanii , just cut and scaled a little. The second one is generated by me but

* it's exactly the same pattern
* it encodes the same string: "123123123"
* same file format: JPEG
* same aspect ratio: 572x664

I loaded your image into GIMP. I tried to reduce the reflection. I tried to increase color contrast. No matter what I do, the image is not being detected. On the other hand, no matter what I do to my image, it keeps working. I'm puzzled.

**Comment by gruhn** [comment]
After some recent dependency updates I tried to scan all QR codes in this thread again and all are working so I'd call this resolved.

**Comment by tpharaoh** [comment]
I am having a similar issue. 

```
<label for="uploadQR" class="btn btn-block py-2 btn-secondary text-white" @click="error=$t('notifications.qr_error');qrScan=true">{{$t('general.scan')}}</label>
                    <div v-if="qrScan">
                        <qrcode-drop-zone @decode="onDecode" @init="logErrors" v-if="!noStreamApiSupport">
                            <qrcode-stream class="img-thumbnail mx-auto" style="width:250px;height:250px" v-if="!noStreamApiSupport" @decode="onDecode" @init="onInit" />
                        </qrcode-drop-zone>
                        
                        <qrcode-capture v-if="noStreamApiSupport" @decode="onDecode" id="uploadQR" />
                    </div>
```

this is mostly your code, I just added a button so it fits my styling.

Safari MacOS: stream works
Chrome MacOS: stream
Android App (cordova): stream
IOS App (Cordova): capture, camera opens, but doesnt detect. I got it to work earlier today, same QR code

![123456_QR](https://user-images.githubusercontent.com/2931452/97340275-3e05fd00-188c-11eb-908b-c326dd48d78e.png)
123456 Plain text

**Comment by tpharaoh** [comment]
I used detect instead of decode to get more info.

It says:
TypeError: t.addEventListener is not a functiond (on 't.addEventListener(e,r)','t.addEventListener is undefined')
