### ISSUE TITLE
Can not decode some QR Codes (not alignment mark)

### ISSUE THREAD

**Issue by dedosmedia** [gruhn/vue-qrcode-reader#127]
Hi!
I have had issues trying to decode some QR codes. What all of them have in common is they are V1 QR codes, so there is not alignment mark.
Do you know what is the issue with these codes? Why are not being decoded by this library?

https://s3.amazonaws.com/event-system-qr/OGE/1563205967509-TAEH6ZCLM.png
https://s3.amazonaws.com/event-system-qr/OGE/1563201865250-W-J01FKGX.png
https://s3.amazonaws.com/event-system-qr/OGE/1563203458016-J671U5VC8.png
https://s3.amazonaws.com/event-system-qr/OGE/1563205581789-91C5MIDA0.png
https://s3.amazonaws.com/event-system-qr/OGE/1563205967509-TAEH6ZCLM.png
https://s3.amazonaws.com/event-system-qr/OGE/1563796394390-71LV-B705.png

Thanks for your help!

**Comment by gruhn** [comment]
[jsQR](https://cozmo.github.io/jsQR/), the library we are using to read QR codes, too seems to be unable to read your QR codes. That means _we_ cant really do anything about it. You might want to open an issue at their repository.

**Comment by dedosmedia** [comment]
Hi.
Thanks so much for your quick answer!
I have been able to manage it. Simply, I am forcing my app to generate QR V2 codes, and that will solve my issue. Thanks for your library, it's a lifesaver.

**Comment by gruhn** [comment]
Good to know though. I'll add a caveat to the README.
