### ISSUE TITLE
Read QrCode

### ISSUE THREAD

**Issue by dalcero** [gruhn/vue-qrcode-reader#129]
Hello. Why can't I read the same QrCode twice? I have to read another QrCode and then read the previous one again, just like that it works. Is it any configuration?

**Comment by gruhn** [comment]
This is explained in the docs. See the info section below the code example:
https://gruhn.github.io/vue-qrcode-reader/api/QrcodeStream.html#events

The _Pause & Validate_ demo offers a solution: 
https://gruhn.github.io/vue-qrcode-reader/demos/Validate.html
