### ISSUE TITLE
Lodash Issue

### ISSUE THREAD

**Issue by Ajusa** [gruhn/vue-qrcode-reader#13]
Hi,

I just started using this plugin, so my apologies if I rushed ahead. I am importing (downloaded from the dist folder) the css file and JS file (the -browser one) in my index.html. When I open up Chrome and check the dev console, I am getting many errors related to Lodash.
```
vue.js:580 [Vue warn]: Error in getter for watcher "constraintsNormalized": "TypeError: __WEBPACK_IMPORTED_MODULE_5_lodash_isObject___default(...) is not a function"

found in

---> <QrcodeReader>
       <Root>
```

Please let me know if you need any more information!

**Comment by gruhn** [comment]
Hey, thanks for reporting :+1: Try upgrading to `v0.6.7`. Should be fixed now.

**Comment by gruhn** [comment]
So? Did it work?

**Comment by Ajusa** [comment]
Sorry, I have been using the dist folder for scripts. If I am correct, that one has not been updated yet.

I could run an npm install, but I am not well versed in packaging, and npm breaks a lot on my machine. Could you commit the built version? Thanks!

**Comment by gruhn** [comment]
Sure
