### ISSUE TITLE
Cannot click Allow or Block in permission prompt

### ISSUE THREAD

**Issue by louisluu** [gruhn/vue-qrcode-reader#139]
**Describe the bug**
When get asked for camera access permission, I cannot click on any button (e.g. Allow and Block).

**To Reproduce**
1. On Android Chrome
2. Access [demo page](https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html)
3. Will see the prompt: "ABC wants to use your camera"
4. Cannot click Block or Allow button in the prompt

**Expected behavior**
Should be able to click Block or Allow

**Screenshots**
https://imgur.com/a/jc8J1o2

**Smartphone (please complete the following information):**
 - Device: Android (anonymous)
 - OS: Android 7.0
 - Browser: Chrome
 - Version 76.0.3809.111

**Additional context**
Tried this library in my local project (localhost) and worked fine.

**Comment by gruhn** [comment]
Some android apps run in the background and create screen overlays that prevent you from interacting with permission dialogs. For example blue light filter apps like [Twilight](https://play.google.com/store/apps/details?id=com.urbandroid.lux). Is it possible you have an app like this running?

**Comment by louisluu** [comment]
Thanks @gruhn for the quick answer.

I dont have any custom app that does the overlay thing (that I know of), but my phone does have a native feature called "Reading mode". I tested it again in different ways:

- my phone, Chrome, Reading mode turned off -> did not work
- my phone, Chrome, Reading mode turned on -> did not work
- my phone, Firefox Focus -> could not see the permission prompt
- my friend phone, Chrome -> works

So, do you know if there is any other explanation? or its because something else is doing the screen overlays on my phone?

Cheers,

**Comment by gruhn** [comment]
I'm almost certain, it has nothing to do with the demo. But to be sure check if you have the same problem on [this page](https://webqr.com).

Also check out [this thread](https://talk.sonymobile.com/t5/Xperia-XA1-Ultra/Allow-button-not-working/td-p/1260755). This guy seems to have the same problem.

**Comment by louisluu** [comment]
Tested webqr and not working, so must be some apps/services that have "Draw over other apps" permission.

Anw, thanks for your helps, appreciate it.

Closing this issue now.
