### ISSUE TITLE
this.$listeners is undefined. Quasar framework integration.

### ISSUE THREAD

**Issue by maclaine-san** [gruhn/vue-qrcode-reader#14]
Hi, Can this be implemented using **quasar-framework**?
I have an issue using this package in my current project which is built using **quasar-framework v.14.1**.
My use case is to embed the **qr-code-reader** in a **modal**. The **webcam** can be successfully detected and can be displayed inside the modal but there is an error which is preventing me to scan a **QRCode**.
This is the error I get. It states that **this.$listeners is undefined**
![image](https://user-images.githubusercontent.com/20497345/34353277-1f7d6bd0-ea62-11e7-969a-96d09763aa59.png)

**Comment by gruhn** [comment]
Hey, I haven't worked with quasar yet but I can't think of an obvious reason why it should be a problem.

`vue-qrcode-reader` checks if event handlers for `locate` and/or `decode` are registered by its parent component. This can be checked using the instance property [vm.$listeners](https://vuejs.org/v2/api/#vm-listeners). If no handlers are registered, continuously locating and decoding (which is rather expensive) would be unecessary and is therefore omitted. 

Now it seems like `$listeners` is not available in your component instance for some reason. Maybe this is a bug or quasar interferes here...

Could you share your source or provide detailed steps to reproduce?

**Comment by maclaine-san** [comment]
After hours of debugging I have found what was the reason why the vue instance property `this.$listeners` is undefined. It turned out quasar has a custom event handling instance property that handles the events called `_events`. 
So in order for it to work with **quasar-framework** I updated your `QrcodeReader.vue` component a little bit, changed the `this.$listeners` to `this._events` on `shouldScan()` and `shouldLocate()` computed functions.

Looking forward for a full quasar-framework support in the future.
Nice work with the package btw.

**Comment by gruhn** [comment]
Thanks for taking the time :grinning: :+1:

I believe `_events` is a property also [used internally by Vue](https://github.com/vuejs/vue/blob/dev/src/core/instance/events.js#L13). I'm not sure what the difference to `$listeners` is though.

I'd love to support quasar and find out why it's not working already but I hope there is a solution which is based on Vues official API.

**Comment by chameleonbr** [comment]
Hey @maclaine-san, you could send me sample code to use this module inside quasar framework? I have problems with postCSS or something like that.

**Comment by gruhn** [comment]
This might be fixed now. `$listener` is not used anymore.
