### ISSUE TITLE
localhost:8080 working, but deployment not working

### ISSUE THREAD

**Issue by AcodeWizard** [gruhn/vue-qrcode-reader#140]
**Describe the bug**
I developed my project using this module so I built and run in the Apache server.
But browser with domain name has some errors, but localhost:port number is working correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/47908734/63783778-2b242100-c8b3-11e9-8cdc-2a7df452a5f9.png)

**Comment by gruhn** [comment]
You have to use HTTPS. For details, please have a look at the READMEs *browser support* section

**Comment by findmoon** [comment]
> You have to use HTTPS. For details, please have a look at the READMEs _browser support_ section

Whether can cancel this restriction, or add an option, it can set the enable or disable must be used in https，thank you!

**Comment by AcodeWizard** [comment]
Thanks for your reply, I am now testing in my hosting server. but not checking.
When I have checked, I will inform you about the result.
Hopes to work correctly.
