### ISSUE TITLE
Force rear camera on laptop

### ISSUE THREAD

**Issue by ibbtek** [gruhn/vue-qrcode-reader#142]
**Describe the bug**
Trying to pass either the 'rear' or 'front' camera failed on my laptop. The scanner only work when I explicitly pass the 'auto' string to the camera prop.

**To Reproduce**
1. Set the camera prop to 'rear' or visit this [link](https://gruhn.github.io/vue-qrcode-reader/demos/SwitchCamera.html) on your laptop

**Expected behavior**
Setting the camera prop to 'rear' should work

**Screenshots**
Trying on the [switch to front camera demo page](https://gruhn.github.io/vue-qrcode-reader/demos/SwitchCamera.html) (not working)
![image](https://user-images.githubusercontent.com/25365069/63936017-c0abe600-ca56-11e9-9f91-73c98d299530.png)

Trying on the [decode continuously demo page](https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html) (working)
![thumbsup](https://user-images.githubusercontent.com/25365069/63937062-78da8e00-ca59-11e9-9d36-80c72d0b81f2.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser: Firefox Quantum
 - Version: 68.0.2 (64-bit)

 - OS: Linux Ubuntu
 - Browser: Chrome
 - Version: 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
As the problem only occure when explicitly giving the 'rear' string to the camera, looking at the source code I think the problem is coming from this switch:

```js
switch (this.camera) {
        case "auto":
          base.video.facingMode = { ideal: "environment" };
          return base;
        case "rear":
          base.video.facingMode = { exact: "environment" };
          return base;
        case "front":
          base.video.facingMode = { exact: "user" };
          return base;
        case "off":
          return undefined;
        default:
          return undefined;
}
```
Changing it to this should work (note the 'ideal' instead of 'exact' on rear facingMode obj) :

```js
switch (this.camera) {
        case "auto":
          base.video.facingMode = { ideal: "environment" };
          return base;
        case "rear":
          base.video.facingMode = { ideal: "environment" };
          return base;
        case "front":
          base.video.facingMode = { exact: "user" };
          return base;
        case "off":
          return undefined;
        default:
          return undefined;
}
```
I did a PR

**Comment by ibbtek** [comment]
**Update**
I tried my fix and changing 
```js
case "rear":
          base.video.facingMode = { exact: "environment" };
``` 
to 
```js
case "rear":
          base.video.facingMode = { ideal: "environment" };
``` 
it works

**Comment by gruhn** [comment]
The problem is that many devices don't label the installed cameras clearly. Sometimes stuff isnt recognized as a rear camera although it should, causing the `rear` option to fail. 

With `auto` you always get a result as long as there is any camera available. Potentially even a front camera stream. This is confusing behavior for an option called `rear`.

I agree that the situation is not ideal but since we have `auto` I don't think it makes sense to have `rear` behave exactly the same way. Moreover this could be considered a breaking change.
