### ISSUE TITLE
I can't use the rear camera

### ISSUE THREAD

**Issue by xiaxiao001** [gruhn/vue-qrcode-reader#148]
vue-qrcode-reader:2.0.4
web browser is:  Chrome 70 on Android 8.1 

Camera is auto ; using front camera
Camera is front; display error OverconstrainedError: Unknown name of constraint detected
Camera is rear; display error OverconstrainedError: Unknown name of constraint detected
But I use my phone to open https://gruhn.github.io/vue-qrcode-reader/ . Can use the rear camera,
I don't know if the version I am using is low, or I need to install other plugins.
please help me! Thank you!

**Comment by xiaxiao001** [comment]
![XPPITX$NI MQG 4A}RRX0UI](https://user-images.githubusercontent.com/34258290/65410243-6b2be480-de1c-11e9-91af-272f8e6563b1.png)

**Comment by gruhn** [comment]
Can you please assemble a minimal demo of your code (for example on jsfiddle) so I can reproduce your issue. Otherwise I can't help you. 

You could modify [this demo](https://jsfiddle.net/vqg8to36/1/) until your issue appears.

**Comment by xiaxiao001** [comment]
I am very sorry, jsfiddle I use less;
I installed vue-qrcode-reader : 2.0.4 ;
I have a problem setting the "camera" parameter in the <qrcode-stream tag;
<qrcode-stream @decode="onDecode" @init="onInit" :camera="camera" />
Scanning is only performed when the “camera” parameter is “auto”;
When the “camera” parameter is “rear” or “front”, an error is displayed.
If you can, I hope you can give me some ideas.

**Comment by xiaxiao001** [comment]
Need to install the webrtc-adapter plugin and introduce it in main.js?

**Comment by gruhn** [comment]
> If you can, I hope you can give me some ideas.

As I said, please provide a minimal reproduction otherwise I can't help.

> Need to install the webrtc-adapter plugin and introduce it in main.?

no, this done automatically

**Comment by xiaxiao001** [comment]
Hi, do you need to debug the code? I can package the vue project online and let you run the results.Can it be like this?
