### ISSUE TITLE
Minified + gzipped size badge in README display wrong value

### ISSUE THREAD

**Issue by 3rdSenna** [gruhn/vue-qrcode-reader#150]
![image](https://user-images.githubusercontent.com/32235364/66959508-6dbbdb80-f062-11e9-8fcc-70414d747728.png)

I've my vue component which Imports only imports QrcodeStream, but in the end of the compilation process I've far bigger files even minified and gzipped.

Any help will veeeeery welcome. I'm quiet new with these building process.

```
<script>
import { QrcodeStream } from 'vue-qrcode-reader'

export default {
  components: { QrcodeStream },
  ...
}
</script>
```

![image](https://user-images.githubusercontent.com/32235364/66958767-d6a25400-f060-11e9-9d20-38d3718e500a.png)

![image](https://user-images.githubusercontent.com/32235364/66958951-49133400-f061-11e9-9a9a-e7db8f082644.png)

![image](https://user-images.githubusercontent.com/32235364/66958969-57615000-f061-11e9-96ab-5cc4a4a6bbca.png)

I could split in smaller chunks, but the biggest chunk it's still the qrCode piece.

![image](https://user-images.githubusercontent.com/32235364/66959215-d191d480-f061-11e9-83fb-ca0036b31806.png)

**Comment by Turbotailz** [comment]
Is this a development build, or a production build?

**Comment by 3rdSenna** [comment]
> Is this a development build, or a production build?

It's production build.

**Comment by gruhn** [comment]
This is definitely false advertisement. 250kB is more like it. I'm aware of this issue but I couldn't figure out how this size is computed. The badge is provided by bundlephobia:

https://bundlephobia.com/result?p=vue-qrcode-reader@2.1.1

Bundlephobia claims that both direct and transitive dependencies are taken into account. However, our dependency to `jsqr` and `webrtc-adapter` each alone already exceed the computed size.

Any help with this issue is greatly appreciated.

**Comment by 3rdSenna** [comment]
Oook so...
It's completely fine to be 250KB. My concern was that I was doing something really wrong. 

So, I'm getting the real size. That's fine.
@gruhn , 
Thanks for the answer and the lib =)

**Comment by gruhn** [comment]
Yes. Thanks for reminding me though. This is arguably misleading and should be fixed. Let's keep this open.

**Comment by 3rdSenna** [comment]
That's ok. I closed because as it was a question, I had a proper answer. But it's up to you =)

**Comment by gruhn** [comment]
fixed.
