### ISSUE TITLE
Can't fake camera with tests

### ISSUE THREAD

**Issue by Nisgrak** [gruhn/vue-qrcode-reader#151]
**Describe the bug**
I try to make a test with Cypress, faking the qr as y4m file, when use the convenient flag(describe below) the lib throw a error.

**To Reproduce**
1. Use the flags `--use-fake-device-for-media-stream` and `--use-file-for-fake-video-capture=absolute/route/to/qr.y4m` in chrome
2. Open the [demos](https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html)
3. See the error in the page

**Expected behavior**
The cam should be faked with the y4m file

**Additional context**
https://docs.cypress.io/api/plugins/browser-launch-api.html#Use-fake-video-for-webcam-testing
[Example y4m file](https://github.com/gruhn/vue-qrcode-reader/files/3810339/examplefile.zip)

**Comment by gruhn** [comment]
Note, that we haven't managed to implement any tests so far (see #61). 

What error are you seeing on the page?

**Comment by Nisgrak** [comment]
This is the error.

![image](https://user-images.githubusercontent.com/19597708/68304247-a9682500-00a5-11ea-9290-470bdd0ba32b.png)

**Comment by gruhn** [comment]
The only thing I can say so far is that this is caused by a [NotReadableError](https://stackoverflow.com/a/47551322). I'll try to dig deeper in time.

**Comment by tzifrea** [comment]
Any developments on this?
