### ISSUE TITLE
OnePlus 5 not able to scan QR code

### ISSUE THREAD

**Issue by MarcianoStikkelorum** [gruhn/vue-qrcode-reader#153]
**Describe the bug**
Based on some google searches, a OnePlus 5 is unable to scan a QR code by default with the normal camera. I've scratched my head for hours trying to resolve this but I found out that you're forced to install Google Lens for it to work. Normally, this wouldn't be a problem. But I'm trying to get it working for a webshop which.. gets more traffic than the usual apps using things like this. 

I was wondering if there is any way for you, or other developers, to check if a camera supports the QR functionality based on the device. We'll only be using the QR-scanner on mobile devices based on their user-agent so a desktop fallback is already built in. 

**Expected behavior**
Not really expected, more like a requested behavior. Either a function to check if the scanner actually works, or an event that fires when the QR can't be decoded and/or read (I can make this myself too, if you can't do anything before opening the camera). 

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: Android custom build form OnePlus (A5000_23_191008, translates to OxygenOS 9.0.9)
 - Browser: Google Chrome
 - Version: 78.0.3904.96

**Additional context**
Installing Google Lens seems to resolve the issue, for those who are wondering. I'm using the latest version of the plugin.

**Comment by gruhn** [comment]
I would be surprised if your device needs built-in support for QR code scanning. The only thing we need is access to the camera using the [Stream API](https://caniuse.com/#feat=stream) to get our hands on the image data. The QR code scanning algorithm is entirely implemented in JavaScript. So with the latest Chrome on Android this shouldn't be a problem.

Can you describe how your problem expresses? Are there any errors? Have you only checked your own implementation or the demo page too?

You might want to check if these demos fail on your device as well:

https://cozmo.github.io/jsQR/
https://schmich.github.io/instascan/

**Comment by MarcianoStikkelorum** [comment]
Both the demo pages are not working on my phone without Google Lens, which is strange because every other brand/phone I use.. it does work. I think it has something to do with the kernel build on the OnePlus 5, I've resolved it by simply installing Google Lens and hinting users after 5 seconds if the plugin still hasn't received the data.
