### ISSUE TITLE
Input type file need IMPROVE

### ISSUE THREAD

**Issue by tranvannhat** [gruhn/vue-qrcode-reader#155]
With Android device (device test brand: Xiaomi) + Chrome browser  
Input type select not option select file in other folder.  I wish you update or optional props ```capture="environment"``` in ```QrcodeCapture.vue```. Thanks

![android](https://user-images.githubusercontent.com/28804941/70368694-8917ca00-18e0-11ea-93aa-3ff13acb5932.jpg)

<img width="517" alt="qrcode-capture" src="https://user-images.githubusercontent.com/28804941/70368665-26bec980-18e0-11ea-9e82-44b790ba936d.png">

**Comment by gruhn** [comment]
I'm not sure what you are trying to say but note that you can overwrite or remove the `capture` attribute:

```html
<qrcode-capture :capture="false" />
```


See: https://gruhn.github.io/vue-qrcode-reader/api/QrcodeCapture.html#props

**Comment by tranvannhat** [comment]
i want delete attr ```capture```

**Comment by tranvannhat** [comment]
> I'm not sure what you are trying to say but note that you can overwrite or remove the `capture` attribute:
> 
> ```
> <qrcode-capture :capture="false" />
> ```
> 
> See: https://gruhn.github.io/vue-qrcode-reader/api/QrcodeCapture.html#props

Thanks bro
