### ISSUE TITLE
Certain code can not be read

### ISSUE THREAD

**Issue by danielgross-safer-print** [gruhn/vue-qrcode-reader#156]
**Certain code can not be read**
I have a string that wont't be decoded:
BAD92A71B50A5261947544ED50186959

Other decoders do work (e.g. zxing). If I remove the last character it does work too.

**Screenshots**
Try for yourself
![QR](https://user-images.githubusercontent.com/58699064/70451181-34717c00-1aa5-11ea-8f42-8b7c039c4ced.png)

**Comment by gruhn** [comment]
I'm not sure what's wrong with this QR code. 

Note that jsQR, the scanning library we use, has trouble when there is not at least a little bit white margin around the code. This is the case with your QR code so I added some margin but it still couldn't be detected:

![70451181-34717c00-1aa5-11ea-8f42-8b7c039c4ced](https://user-images.githubusercontent.com/26570572/70471506-96de7280-1acd-11ea-9fd7-0b2e1f55dc7c.png)

However, using [this site](http://goqr.me/) I generated a QR code based on the text you provided and this one seems to work:

![qrcode2](https://user-images.githubusercontent.com/26570572/70471738-166c4180-1ace-11ea-994f-b99a172bad8e.jpeg)

The QR codes are visually different so your encoding must be somehow different such that is messes with the detection algorithm :man_shrugging:

**Comment by danielgross-safer-print** [comment]
Very strange problem. I changed the correction level (using this code creator: https://the-burtons.xyz/barcode-generator/) to Q. Now everything's working fine. 
![ScreenShot 029 1911161822 pdf -  _var_www-tickettool_tickets_1911161822-1 pdf  - SumatraPDF](https://user-images.githubusercontent.com/58699064/70475687-5d116a00-1ad5-11ea-9cfb-46e0d4702e4e.png)

Thanks for the help!
