### ISSUE TITLE
document is not defined in Nuxt

### ISSUE THREAD

**Issue by radislaw** [gruhn/vue-qrcode-reader#159]
I use vue-qr-reader with<client-only> tag in Nuxt project, but I have an error: document is not defined and infinity loading page

**To Reproduce**
```
<template>
  <client-only>
     <QrcodeStream />
  </client-only>
</template>

<script>
import { QrcodeStream } from 'vue-qrcode-reader'
...
```

**Desktop**
 - OS: ubuntu 16.04
 - Browser: chrome 79
 - Version "vue-qrcode-reader": "^2.1.1"

**Comment by delrueba** [comment]
Wrap the QrcodeStream in your own component and then import your component like this

`  components: {
    scanner: () => import('@/components/client-only/Scanner')
  }`

```
<client-only>
  <scanner />
</client-only>
```

**Comment by radislaw** [comment]
I created plugin file for use VueQrcodeReader globally
```
import Vue from 'vue'
import VueQrcodeReader from 'vue-qrcode-reader'

Vue.use(VueQrcodeReader)
```
Then added it in nuxt.config.js with mode: 'client'

```
 plugins: [
    { src: '@/plugins/qrCodeReader.js', mode: 'client' }
]
```
And just use it:
``` 
<qrcode-stream @decode="onDecode" />
```

**Comment by ccsaposs** [comment]
> Wrap the QrcodeStream in your own component and then import your component like this
> 
> ` components: { scanner: () => import('@/components/client-only/Scanner') }`
> 
> ```
> <client-only>
>   <scanner />
> </client-only>
> ```

@delrueba What should the component file look like?

I'm running into a "document is not defined" error with this as my component:
```vue
<template>
  <QrcodeStream />
</template>

<script>
import QrcodeStream from 'vue-qrcode-reader'
export default {
  components: { QrcodeStream },
}
</script>
```

**Comment by delrueba** [comment]
> > Wrap the QrcodeStream in your own component and then import your component like this
> > ` components: { scanner: () => import('@/components/client-only/Scanner') }`
> > ```
> > <client-only>
> >   <scanner />
> > </client-only>
> > ```
> 
> @delrueba What should the component file look like?
> 
> I'm running into a "document is not defined" error with this as my component:
> 
> ```
> <template>
>   <QrcodeStream />
> </template>
> 
> <script>
> import QrcodeStream from 'vue-qrcode-reader'
> export default {
>   components: { QrcodeStream },
> }
> </script>
> ```

@ccsaposs unfortunately I don't have that project anymore. Have you tried using <qrcode-stream> instead of <QrcodeStream> ?
In hindsight though, I'd go with the plugin method described by @radislaw .

**Comment by ccsaposs** [comment]
@delrueba Thank you for your quick repsonse!

I tried `<qrcode-stream>` and got the same result.  Do you know if it's possible to do it inside a component?  The reason I'm asking is since I only need it for a small part of my website, so I'd prefer not to import the plugin globally.

**Comment by gabrielsze** [comment]
still facing the exact same issue

**Comment by brncmp** [comment]
anyone? /\

**Comment by aleksvilly** [comment]
> anyone? /\

use this - https://github.com/nimiq/qr-scanner

1.
`npm install qr-scanner`

2.plugins/qr-scanner.js:
```
import Vue from 'vue';
import QrScanner from 'qr-scanner';
QrScanner.WORKER_PATH = '/qr-scanner-worker.min.js'; // Ensure this path is correct and accessible
Vue.prototype.$QrScanner = QrScanner;
```

3.// nuxt.config.js:
```
export default {
  plugins: [
    { src: '~/plugins/qr-scanner.js', mode: 'client' }
  ]
}
```

4.
`cp node_modules/qr-scanner/qr-scanner-worker.min.js static/
`
5.components/ComQRScanner.vue:
```
<template>
  <div>
    <video ref="video" style="width: 100%; height: auto;"></video>
    <div v-if="error" class="error">{{ error }}</div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      qrScanner: null,
      error: null
    };
  },
  mounted() {
    this.initializeScanner();
  },
  beforeDestroy() {
    if (this.qrScanner) {
      this.qrScanner.stop();
    }
  },
  methods: {
    async initializeScanner() {
      const video = this.$refs.video;

      try {
        this.qrScanner = new this.$QrScanner(video, this.onDecode);
        await this.qrScanner.start();
      } catch (err) {
        this.error = this.$t('grid.CameraAccessIsRequired');
        console.error('Error initializing QR Scanner:', err);
      }
    },
    onDecode(result) {
      console.log('Decoded result:', result);
      this.$emit('decode', result);
    }
  }
};
</script>

```
