### ISSUE TITLE
Allow for camera selection

### ISSUE THREAD

**Issue by dvenske** [gruhn/vue-qrcode-reader#164]
On modern phones often there are multiple cameras. For example my Huawei P30 Pro has 4 back facing and 1 front.

If you head to this page:
https://philnash.github.io/mediadevices-camera-selection/

It shows an example of changing cameras. Currently the QR scanner uses a camera that I have to hold a good meter away to scan a QR code (impressive that it can do that but it's not feasible). Would it be possible for the selection of camera to be implemented into the library? 

Cheers

**Comment by gruhn** [comment]
How does the native camera app on your phone deal with this situation? Is there a drop-down where you can pick the camera? Or does it just pick a default front and rear camera?

**Comment by dvenske** [comment]
On the camera app it usually detects which to use, it also will use all cameras combined to generate the best picture. I believe it has a depth sensor too and switches camera based on that. I don't think this is information we have access to via the JS api. I did however test using the above javascript app to switch between the available cameras and it makes a very big difference.

I've got the same problem with other phones I've tested with. Pretty much any modern phone is going to have multiple cameras these days. Even the cheaper P30 non-pro version has 3 rear cameras. I tested with a samsung S20 and S9+.

**Comment by gruhn** [comment]
What I don't like about explicit camera selection is that the user has to do it. He doesn't understand why he must make a decision between multiple rear cameras. He expects this to *just work*.

I really want to make sure first that there is no way to implement some sensible default behavior.

I'm not sure how capable the JS API is, in this regard. Maybe we can default to short distance camera or something.

**Comment by araimbekoff** [comment]
> Maybe we can default to short distance camera or something.

Yeap!

**Comment by dvenske** [comment]
> Maybe we can default to short distance camera or something.

I agree with this. Considering QR scanning is inevitably going to be closer than say a photo. Not sure if it's possible to find that.

**Comment by gruhn** [comment]
Hey everybody, please check out: #179
