### ISSUE TITLE
Can I use Decode by Upload without open camera? 

### ISSUE THREAD

**Issue by pagongamedev** [gruhn/vue-qrcode-reader#167]
Can I use Decode by Upload without open camera? have it have tag or config for set default about it.

i want use classic file upload for scan only.

thank you for your help

**Comment by gruhn** [comment]
Yes. Check the docs: 

https://gruhn.github.io/vue-qrcode-reader/api/QrcodeCapture.html#props

You need to remove the HTML attribute `capture`:

```html
<qrcode-capture :capture="false" />
```
