### ISSUE TITLE
Component not loading when website deployed to AWS S3

### ISSUE THREAD

**Issue by ayudh37** [gruhn/vue-qrcode-reader#168]
I successfully integrated this great component to my project. It works on localhost however after building my project and pushing the build folder dist to AWS S3, the component doesn't load, there's just a blank white area. 

I took a look at https://github.com/gruhn/vue-qrcode-reader/issues/34 however that wasn't really helpful.  

Any ideas as to what may be going on?

**Screenshots**
Here's proof of it working in localhost: 
![image](https://user-images.githubusercontent.com/11541303/80555672-8d659080-8a03-11ea-9cd8-4be094f93677.png)

And here it is when the dist folder is deployed on S3:
![image](https://user-images.githubusercontent.com/11541303/80555770-d289c280-8a03-11ea-8e1e-4cdb3f72fc83.png)

**Desktop**
 - OS: [iOS, Windows]
 - Browser [Chrome, Firefox]

**Smartphone**
 - Device: [Huawei Nexus]
 - OS: [Android 8]
 - Browser [Chrome]

**Comment by gruhn** [comment]
Do you use https?

**Comment by ayudh37** [comment]
No

**Comment by ayudh37** [comment]
I'm closing the issue as I didn't read the docs that stated the https issue. My bad, have a nice day.
