### ISSUE TITLE
Using this component in Wechat does not work in IOS.

### ISSUE THREAD

**Issue by yoyomule** [gruhn/vue-qrcode-reader#171]
This component is used in Wechat, but it is found that wechat in Android has no problem, but it does fail in IOS. Can we consider supporting wechat compatibility on IOS?

**Comment by gruhn** [comment]
Do you mean it's used inside the Wechat app on iOS? In this case, the app probably uses  WKWebView and this is not supported. We have to wait for Apple to do something about it. See: 

https://bugs.webkit.org/show_bug.cgi?id=188360
