### ISSUE TITLE
Getting TypeError

### ISSUE THREAD

**Issue by fitzhex** [gruhn/vue-qrcode-reader#173]
I'm using the code on this demo page [https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html](https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html)
The camera won't load after i allow the permission. 
Getting TypeError:a.finally is not a function 

**Screenshots**
![Screenshot_20200506-104227](https://user-images.githubusercontent.com/6078068/81134181-8b14b080-8f86-11ea-9ebc-40946861c015.jpg)

**Smartphone (please complete the following information):**
 - Device: Oneplus 5
 - OS: Android 9
 - Browser Firefox
 - Version 68.8.0

**Additional context**
On Chrome and Opera this demo works fine.
For your information i'm using Quasar framework  v1.10.5

**Comment by gruhn** [comment]
This seems to correspond to [Promise.prototype.finally](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally) 

Does it work when you go to [the original demo](https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html) with that device/browser?

**Comment by fitzhex** [comment]
yes, the original page does work.. Posibble conflict with others package?
