### ISSUE TITLE
QR code capture doesn't work on Chrome/Mozilla for iOS

### ISSUE THREAD

**Issue by Mario996** [gruhn/vue-qrcode-reader#175]
**Describe the bug**
Using your demo on: https://gruhn.github.io/vue-qrcode-reader/demos/Upload.html I'm not able to decode the QR code, while it works perfectly when I use the same image on Safari

**To Reproduce**
1. Go to https://gruhn.github.io/vue-qrcode-reader/demos/Upload.html using the setup I wrote below
2. Add an image using camera

**Expected behavior**
QR code gets decoded 

**Screenshots**
![IMG_0009](https://user-images.githubusercontent.com/39298317/81812571-9cc9fb00-9526-11ea-8180-3b72fb1addf7.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 13.4.1
 - Browser Chrome/Firefox
 - Version 81.4044.124/25.0

**Comment by gruhn** [comment]
Yes, sadly it doesn't. Please review the browser support table. We can't do anything about it.
