### ISSUE TITLE
Can i get Imagedata form qrcode-capture when :capture="false"?

### ISSUE THREAD

**Issue by pagongamedev** [gruhn/vue-qrcode-reader#176]
i use 
<qrcode-capture :capture="false" />

for scan without camera

i use "onDetect" for get image but it not response.
and "onDecode" get only string

i try "@onChangeInput" it not work "onDecode" not response too.

**Comment by gruhn** [comment]
It shouldn't be a problem. Can you create a demo on https://jsfiddle.net/ or https://codepen.io/pen/ or something?

**Comment by pagongamedev** [comment]
sorry for late

i don't know how use nuxt in jsfiddle

i try "@onChangeInput" or ":onChangeInput"   it not work 

my code
```
<template>
  <div>
    <p class="error">{{ error }}</p>
    <p class="decode-result">
      Last result:
      <b>{{ result }}</b>
    </p>
    <p class="decode-file">
      File:
      <b>{{ file }}</b>
    </p>

    <qrcode-capture :onChangeInput="onChangeInput" @decode="onDecode" :capture="false" />
  </div>
</template>
<script>
import { QrcodeCapture } from 'vue-qrcode-reader'

export default {
  layout: 'blank',
  components: { QrcodeCapture },
  beforeMount() {},
  data() {
    return {
      loading: false,
      result: '',
      error: '',
      file: ''
    }
  },

  methods: {
    onChangeInput(event) {
      console.log('How to Get File : ', event)
      this.file = event.target.files // <--- i want a files
    },

    onDecode(result) {
      this.result = result
    },

    async onInit(promise) {
      try {
        await promise
      } catch (error) {
        if (error.name === 'NotAllowedError') {
          this.error = 'ERROR: you need to grant camera access permisson'
        } else if (error.name === 'NotFoundError') {
          this.error = 'ERROR: no camera on this device'
        } else if (error.name === 'NotSupportedError') {
          this.error = 'ERROR: secure context required (HTTPS, localhost)'
        } else if (error.name === 'NotReadableError') {
          this.error = 'ERROR: is the camera already in use?'
        } else if (error.name === 'OverconstrainedError') {
          this.error = 'ERROR: installed cameras are not suitable'
        } else if (error.name === 'StreamApiNotSupportedError') {
          this.error = 'ERROR: Stream API is not supported in this browser'
        }
      }
    }
  }
}
</script>

<style scoped>
.error {
  font-weight: bold;
  color: red;
}
</style>
```

**Comment by pagongamedev** [comment]
> sorry for late
> 
> i don't know how use nuxt in jsfiddle
> 
> i try "@onChangeInput" or ":onChangeInput" it not work
> 
> my code
> 
> ```
> <template>
>   <div>
>     <p class="error">{{ error }}</p>
>     <p class="decode-result">
>       Last result:
>       <b>{{ result }}</b>
>     </p>
>     <p class="decode-file">
>       File:
>       <b>{{ file }}</b>
>     </p>
> 
>     <qrcode-capture :onChangeInput="onChangeInput" @decode="onDecode" :capture="false" />
>   </div>
> </template>
> <script>
> import { QrcodeCapture } from 'vue-qrcode-reader'
> 
> export default {
>   layout: 'blank',
>   components: { QrcodeCapture },
>   beforeMount() {},
>   data() {
>     return {
>       loading: false,
>       result: '',
>       error: '',
>       file: ''
>     }
>   },
> 
>   methods: {
>     onChangeInput(event) {
>       console.log('How to Get File : ', event)
>       this.file = event.target.files // <--- i want a files
>     },
> 
>     onDecode(result) {
>       this.result = result
>     },
> 
>     async onInit(promise) {
>       try {
>         await promise
>       } catch (error) {
>         if (error.name === 'NotAllowedError') {
>           this.error = 'ERROR: you need to grant camera access permisson'
>         } else if (error.name === 'NotFoundError') {
>           this.error = 'ERROR: no camera on this device'
>         } else if (error.name === 'NotSupportedError') {
>           this.error = 'ERROR: secure context required (HTTPS, localhost)'
>         } else if (error.name === 'NotReadableError') {
>           this.error = 'ERROR: is the camera already in use?'
>         } else if (error.name === 'OverconstrainedError') {
>           this.error = 'ERROR: installed cameras are not suitable'
>         } else if (error.name === 'StreamApiNotSupportedError') {
>           this.error = 'ERROR: Stream API is not supported in this browser'
>         }
>       }
>     }
>   }
> }
> </script>
> 
> <style scoped>
> .error {
>   font-weight: bold;
>   color: red;
> }
> </style>
> ```

this plug in can get file?

**Comment by gruhn** [comment]
Sorry for the late response. 

Are you saying that `QrcodeCapture` component does not emit the `detect` event? Please provide an online demo (on jsFiddle, CodePen, etc.) that showcases this bug. I know it's extra work but I'm very busy. I'm sure you are too but if I already have to spend an hour reproducing this bug, I likely won't find the time to deal with this at all.

**Comment by pagongamedev** [comment]
i check for new version @2.3.3 

now it have onDetect function i can get image data now

https://gruhn.github.io/vue-qrcode-reader/api/QrcodeCapture.html#events


thank you so much
