### ISSUE TITLE
Lack of Typescript Type Definitions

### ISSUE THREAD

**Issue by RacerDelux** [gruhn/vue-qrcode-reader#178]
You have to do a workaround with a self-defined .d.ts file to compile this if you are using typescript.

A basic type definition file would be great - if only the minimum file to allow compiling to occur.

**Comment by iqre8** [comment]
Bump
```
24:26 Could not find a declaration file for module 'vue-qrcode-reader'. '<appdir>/node_modules/vue-qrcode-reader/dist/vue-qrcode-reader.common.js' implicitly has an 'any' type.
  Try `npm install @types/vue-qrcode-reader` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-qrcode-reader';`
```

**Comment by iqre8** [comment]
I am able to compile it with the following basic type definition:

```
mkdir -p ./src/types
tee -a << ./src/types/vue-qrcode-reader.d.ts << END
declare module "vue-qrcode-reader";
declare module 'QrcodeCapture';
declare module 'QrcodeDropZone';
declare module 'QrcodeStream';
END

```

**Comment by RacerDelux** [comment]
@iqre8 Yes, you have the correct method. You can actually just call it .d.ts if you want. While this does not add true typing to the project, this is the minimum requirement to let ts projects use the code without having to implement a fix. Should be included in the distro imo.

**Comment by gruhn** [comment]
hey everybody, don't hesitate to open pull requests
