### ISSUE TITLE
Allow @decode for same content

### ISSUE THREAD

**Issue by rentalhost** [gruhn/vue-qrcode-reader#182]
**Describe the bug**

Currently `@decode` will happen once for each content. It is a bit limiting because I need _beep_ to user understand that the code was readed and display a message like "code already readed".

**To Reproduce**

```html
<qrcode-stream @decode="decode"></qrcode-stream>
```

**Expected behavior**

Allow same content be `@decode`'d infinitely. Maybe a new attribute to make it possible.

```html
<qrcode-stream @decode="decode" same-content-interval="3000"></qrcode-stream>
```

Currently I put a `:key` and I increase an internal `data()` value, but stream is recreated. I think that it could lead with memory leak, anyway it is very slow in some devices.

**Comment by gruhn** [comment]
You may use the `camera` prop for that. Check this demo:

https://gruhn.github.io/vue-qrcode-reader/demos/Validate.html
