### ISSUE TITLE
Additional "worker-opts" prop

### ISSUE THREAD

**Issue by w-a-b** [gruhn/vue-qrcode-reader#183]
The default worker and the existing solution for replacing it ( #109 ) seem to be too detached from Vue's reactive space.

If I for example want to replace the default worker, which has hard-coded `inversionAttempts: "dontInvert"`, with a configurable worker where inversionAttempts is controlled by the user, there is no easy way of doing this the "Vue way"(?)

I am imagining that a new, optional `workerOpts: Object` prop in `QrcodeCapture`, `QrcodeDropZone` and `QrcodeStream` could solve this problem very easily: The (reactive) workerOpts could be forwarded to the worker (i.e included in the message posted to the worker, in addition to the ImageData), and the customized worker could change its behavior according to these opts.

This way my new worker could for example check `workerOpts.inversionAttempts` and use whatever is passed from my app instead of the hardcoded `inversionAttempts: "dontInvert"`.

I guess this could also allow anyone to replace the default worker with a custom worker that checks the workerOpts for instructions about cropping the image before scanning ( #15 )

**Comment by gruhn** [comment]
The intent with the worker prop, is the completely decouple which scanning implementation is used with the component. If you require behavior different from the default, you should implement your own worker. I know the current way to pass a custom worker is tricky and not very convenient. I plan to refactor this when I finally find time for that. 

Not sure if it works, but you could try worker implementation. Modify it carefully. Due to the function to string conversion in line 2, this can easily break. 

```js
const inlineWorker = func => {
  const functionBody = func.toString().trim().match(
    /^function\s*\w*\s*\([\w\s,]*\)\s*{([\w\W]*?)}$/
  )[1];

  return new Worker(URL.createObjectURL(
    new Blob([ functionBody ], { type: "text/javascript" })
  ));
}

export default () => {
  return inlineWorker(function () {
    self.importScripts("https://cdn.jsdelivr.net/npm/jsqr@1.2.0/dist/jsQR.min.js");

    self.addEventListener("message", function (event) {
      const imageData = event.data;
      const result = jsQR(imageData.data, imageData.width, imageData.height);

      let content = null;
      let location = null;

      if (result !== null) {
        content = result.data;
        location = result.location;
      }

      const message = { content, location, imageData };
      self.postMessage(message, [imageData.data.buffer]);
    });
  });
}
````

**Comment by w-a-b** [comment]
Thanks, I will I will check out your suggestion. I understand the reasoning behind having support for swapping the worker, my concern is just that the worker should be able to react to new configurations done runtime, for example if the user checks an "invert" checkbox, or a "scan only what is in the center of the video-stream and ignore the rest" checkbox. And by allowing the vue application to pass an option object to your component, and just have it forwarded to the worker in addition to ImageData, then it would be very easy to implement a custom worker that is controlled using Vue props.
