### ISSUE TITLE
QrcodeStream `init` not fire on `camera` props change: useless watch of `constraints`?

### ISSUE THREAD

**Issue by AllanChain** [gruhn/vue-qrcode-reader#184]
**Describe the bug**
When upgrade to 2.3.1 , changing `camera` props of QrcodeStream does not fire `init` to get cameraInstance as 2.1.1 would do

**To Reproduce**
1. Create QrcodeStream with initial `camera` props to `off`
2. Change `camera` to `auto` on a button click
3. `init` not fire

I will create a reproduce repo or snip if this is not clear.

**Expected behavior**
Fire `init` and get camera instance

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Version 83

**Smartphone (please complete the following information):**

**Additional context**

The component is watching `constraints` which is not present. There was a computed `constraints` on 2.1.1

**Comment by gruhn** [comment]
@AllanChain thanks! Does [the new version](https://github.com/gruhn/vue-qrcode-reader/releases/tag/v2.3.2) work again for you?

**Comment by AllanChain** [comment]
Yes, it works! Thanks for quick response!
