### ISSUE TITLE
Galaxy Note 10 Plus (Android 10) returns an error code (NotReadableError)

### ISSUE THREAD

**Issue by river612** [gruhn/vue-qrcode-reader#185]
**Describe the bug**
URL: https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html
Issue: NotReadableError is returned 
Device : Galaxy Note 10 Plus
OS : android 10
Application: Chrome 

**To Reproduce**
Device : Galaxy Note 10 Plus
1. Click  'Chrome Application' 
2. Go to 'https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html'
2. See error(NotReadableError is returned)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45793083/86566159-21c01680-bfa4-11ea-9f40-6fb8bac3729c.png)

**Smartphone (please complete the following information):**
 - Device: [ Galaxy Note 10 Plus]
 - OS: [Android 10]
 - Browser [Chrome]

**Additional context**

**Comment by gruhn** [comment]
The error indicates that the camera is already in use. Could that be the problem here?

**Comment by river612** [comment]
I am wondering why I am getting the error that the camera is in use.
To Reproduce
Steps to reproduce the behavior:
Device : **Galaxy Note 10 Plus(Andoroid 10)**
Click 'Chrome Application'
Go to 'https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html'
See error(NotReadableError is always returned )

At that time, I didn't use any other application (include camera). only used chrome application.
Demo site(https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html') always return NotReadableError.

**Comment by gruhn** [comment]
I used Browserstack to view the demo page in Chrome on Galaxy Note 10 Plus (Android 10) but I don't get any errors.

**Comment by river612** [comment]
Thanks for your support.
Today, I update the version of vue-qrcode-reader (from v2.1.1 to v2.3.2).
After the update, it works well with my application. 
But it didn't still work with chrome application. I already restarted the device(Device : Galaxy Note 10 Plus) several times. Unfortunately I don't know the reason.
Anyway, my application works well with v2.3.2.
