### ISSUE TITLE
catch uncaught (in promise)

### ISSUE THREAD

**Issue by michael-erwin** [gruhn/vue-qrcode-reader#19]
The async function to handle init event cannot catch promise rejection error inside try - catch block. Seems like the reject method was not implemented in promise object passed. I used the sample in its doc as:
```javascript
 methods: {
  async onInit (promise) {
    // show loading indicator
    try {
      await promise
      // successfully initialized
    } catch (error) {
      if (error.name === 'NotAllowedError') {
        // user denied camera access permisson
      } else if (error.name === 'NotFoundError') {
        // no suitable camera device installed
      } else if (error.name === 'NotSupportedError') {
        // page is not served over HTTPS (or localhost)
      } else if (error.name === 'NotReadableError') {
        // maybe camera is already in use
      } else if (error.name === 'OverconstrainedError') {
        // passed constraints don't match any camera. Did you requested the front camera although there is none?
      } else {
        // browser is probably lacking features (WebRTC, Canvas)
      }
    } finally {
      // hide loading indicator
    }
  }
}
```

I get the console error in chrome:

`Uncaught (in promise)
vue-qrcode-reader.common.js?1730:1 `

**Comment by radar155** [comment]
Can you provide a fiddle to reproduce this error? Where are you running your app?

**Comment by michael-erwin** [comment]
@radar155 I'm running it in local dev environment on full webpack template generated with vue cli tool v2.8.2.

**Comment by radar155** [comment]
I can't reproduce this error under those conditions. What do you mean by "local dev enviorment" ? Are you running your app on a device with a camera? Anyway please provide a fiddle to reproduce the error

**Comment by gruhn** [comment]
We don't manually implement a resolve and reject at all. The Promise delivered by `@init` comes from an [an aync function itself](https://github.com/gruhn/vue-qrcode-reader/blob/master/src/components/QrcodeReader.vue#L237-L280). Of course the code is transpiled with babel so resolve/reject are implicitly implemented there. I wouldn't assume it's a babel issue so quick though. 

> I get the console error in chrome:
>
> `Uncaught (in promise) vue-qrcode-reader.common.js?1730:1`

Is this already the hole error message or is there a bit more? Also, can you tell me if you have the same error on the [demo page](https://gruhn.github.io/vue-qrcode-reader/)?

**Comment by michael-erwin** [comment]
@radar155 I can't reproduce the error either in another clean template as the issue only happens in actual project.

@gruhn There's no error in demo page but in actual project here's the error I'm having that cannot be caught:

Chrome:
`
Dashboard.vue?c565:453 qr scanner init success
vue-qrcode-reader.common.js?1730:1 Uncaught (in promise) {name: "NotAllowedError", message: "Permission denied", constraint: undefined, toString: ƒ}constraint: undefinedmessage: "Permission denied"name: "NotAllowedError"toString: ƒ ()arguments: (...)caller: (...)length: 0name: "toString"prototype: {constructor: ƒ}__proto__: ƒ ()[[FunctionLocation]]: getusermedia.js?b218:148[[Scopes]]: Scopes[4]__proto__: Object
r @ vue-qrcode-reader.common.js?1730:1
(anonymous) @ vue-qrcode-reader.common.js?1730:1
Promise.then (async)
r @ vue-qrcode-reader.common.js?1730:1
(anonymous) @ vue-qrcode-reader.common.js?1730:1
e @ vue-qrcode-reader.common.js?1730:1
(anonymous) @ vue-qrcode-reader.common.js?1730:1
startCamera @ vue-qrcode-reader.common.js?1730:1
boundFn @ vue.esm.js?efeb:187
mounted @ vue-qrcode-reader.common.js?1730:1
callHook @ vue.esm.js?efeb:2817
insert @ vue.esm.js?efeb:4011
invokeInsertHook @ vue.esm.js?efeb:5759
patch @ vue.esm.js?efeb:5964
Vue._update @ vue.esm.js?efeb:2572
updateComponent @ vue.esm.js?efeb:2690
get @ vue.esm.js?efeb:3033
run @ vue.esm.js?efeb:3110
flushSchedulerQueue @ vue.esm.js?efeb:2876
(anonymous) @ vue.esm.js?efeb:1783
flushCallbacks @ vue.esm.js?efeb:1704
`
https://content.screencast.com/users/michael-erwin-p/folders/Jing/media/2ef65fb1-4516-4013-b590-5783115bf10a/2018-02-13_1730.png

Firefox:
`Unhandled promise rejection MediaStreamError { name: "NotAllowedError", message: "The request is not allowed by the user agent or the platform in the current context.", constraint: "", stack: "" } vue-qrcode-reader.common.js:1
	k/</e< vue-qrcode-reader.common.js:1
	module.exports</t.exports vue-qrcode-reader.common.js:1
	k/< vue-qrcode-reader.common.js:1
	run setImmediate.js:40
	runIfPresent setImmediate.js:69
	onGlobalMessage setImmediate.js:109
`
https://content.screencast.com/users/michael-erwin-p/folders/Jing/media/2bdd4fee-a9a6-4ea9-a6fd-f1c423f28d47/2018-02-13_1731.png

**Comment by gruhn** [comment]
So, looks like the error is caused by rejected camera access permission. I assume this is on purpose?

Can you show me the line in `vue-qrcode-reader.common.js?1730:1` (pretty printed) where the error occurs? 

Also try using the classic Promise syntax instead and see what happens. Something like this:

```javascript
onInit (promise) {
  promise.then(() => {
    /* ... */
  }).catch(error => {
    console.log(error)
  })
}
```

**Comment by michael-erwin** [comment]
@gruhn Yes it was intentional to simulate the issue. Regardless of how error was produced, all types of error thrown as to whether the camera was not present or declined by user are not caught. I even transferred the component and install dependencies to the fresh template I tested previously where there is no error but now the problematic error was reproduced. Here's the first line in stack trace (pretty printed):

https://content.screencast.com/users/michael-erwin-p/folders/Jing/media/9d550b8c-3e7b-4f69-a066-90aebf7b8c23/2018-02-15_2011.png

https://content.screencast.com/users/michael-erwin-p/folders/Jing/media/8081a687-b605-4811-b45b-68e5860f714a/2018-02-15_2010.png

**Comment by gruhn** [comment]
Thanks for that! It wasn't as helpful as I expected though :grimacing: Can you somehow publish that fresh Vue project where you where able to reproduce this issue? Maybe create a repo?

**Comment by michael-erwin** [comment]
OMG there is no real bug but my silly mistake. The culprit - habit of putting enclosing parenthesis in every function call because it looks cool in editor. So instead of:

`<QrcodeReader @init="onInit" />`

I did this:
`<QrcodeReader @init="onInit()" />`

Now I'm ashamed of myself.

**Comment by gruhn** [comment]
I see! Haha :grin: don't worry.

FYI you can also write `<QrcodeReader @init="onInit($event)" />` if you find this more convenient.

**Comment by michael-erwin** [comment]
Wow I didn't know that! Thanks for the helpful tip & support. +1

**Comment by vmangelovv** [comment]
Hi everyone. I would like to pay attention to this issue =>
On Firefox the function onInit is running the real initialization is not happening.
I think this is bug to work out.
This is my ex.:
`<qrcode-stream @decode="onDecode" @init="onInit"></qrcode-stream>`
and the init func:
```
onInit (promise) {
  promise.then(() => {
    /* ... */
  }).catch(error => {
    console.log(error)
  })
}
```
in "then" and in "catch" i have anything
I tried init() and init($event) but don't work

**Comment by sradforth** [comment]
If it helps anyone else, seems like I had a similar error with 

`a.finally `

not defined in the minified dist version.  This happened before onInit callback was invoked as the promise had already resolved to an error so the camera was enabled but couldn't see the video stream (and no scanning was happening).
Tried polyfill and all sorts but to no avail.  Building locally without minification gave a more descriptive error. Turned out the fix was to add "blob and worker-src" to the security policy...

This may be a red herring but after adding this to our index.html it all sprung to life.

```
    <meta http-equiv="Content-Security-Policy" content="default-src * data:
      blob: 'unsafe-inline' 'unsafe-eval';
      worker-src * blob: data: 'unsafe-inline' 'unsafe-eval';
...
    >

```

If it helps, same behaviour was seen on Firefox and Chrome, Ubuntu.
