### ISSUE TITLE
Camera not activating on Android app

### ISSUE THREAD

**Issue by Klym-SooperPooper** [gruhn/vue-qrcode-reader#190]
I built an Android app by using npm cordova plugin, when I activate qr code reader, I don`t get camera activated

qrcode stream tag not starting streaming on a page of Android app

Cordova plugin version 9.0.0
Vue version 2.6.11

**Comment by vesper8** [comment]
@Klym-SooperPooper did you ever figure this out? Also using Cordova.. it works perfect in IOS.. but no camera yet on Android.
