### ISSUE TITLE
umd files assets not copied to build production

### ISSUE THREAD

**Issue by xicond** [gruhn/vue-qrcode-reader#191]
**Describe the bug**
`*.umd.*` files from node_modules not copied to build production

**To Reproduce**
use `vue-cli-service build`

<img width="1595" alt="Screen Shot 2020-07-20 at 15 01 10" src="https://user-images.githubusercontent.com/2734368/87909068-1be52d80-ca9a-11ea-8704-0bb5c84aed1b.png">

"vue": "2.6.10"
"@vue/cli-service": "3.6.0"
"vue-qrcode-reader": {
      "version": "2.3.9"
}

**Comment by gruhn** [comment]
Are you using vue-qrcode-reader 2.3.9?

**Comment by xicond** [comment]
> Are you using vue-qrcode-reader 2.3.9?

Yes, I'm
Any suggestion ?
First time I tried, auomatically chose that version

**Comment by gruhn** [comment]
No, that's correct. The files were indeed missing in 2.3.4-2.3.8 but should be included again in 2.3.9. See:

https://www.jsdelivr.com/package/npm/vue-qrcode-reader?path=dist

**Comment by xicond** [comment]
> No, that's correct. The files were indeed missing in 2.3.4-2.3.8 but should be included again in 2.3.9. See:
> 
> https://www.jsdelivr.com/package/npm/vue-qrcode-reader?path=dist

@gruhn 

But I tried, it still not copied to `dist` folder of build production
I'm import the components independently as the user guide
How can I make it ? 
Do I only can register all of them globally ?

**Comment by gruhn** [comment]
I'm able to reproduce this. The file is included but the path is not resolved correctly. You can downgrade to 2.3.3 for now.

**Comment by gruhn** [comment]
just released a fix. Please confirm if it works for you
