### ISSUE TITLE
Unable to get stream (ChunkLoadError)

### ISSUE THREAD

**Issue by TimoScheuermann** [gruhn/vue-qrcode-reader#192]
**Describe the bug**
I followed the guide on npm and served the site over https:

main.ts includes
`import VueQrcodeReader from 'vue-qrcode-reader';
Vue.use(VueQrcodeReader);`

[Component](https://github.com/TimoScheuermann/gastro-scanner/blob/master/src/components/GastroAssistant-QR-Code-Scanner.vue)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave, Edge, Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 14
 - Browser safari

**Comment by gruhn** [comment]
just released a fix. Please confirm if it works for you

**Comment by TimoScheuermann** [comment]
Its working. Thank you :)
