### ISSUE TITLE
Trouble Scanning Low data QR with 21 modules

### ISSUE THREAD

**Issue by lobonz** [gruhn/vue-qrcode-reader#193]
Here is a QR code, 
https://i.imgur.com/i3bq0wa.png
it scans fine using an IOS camera, and have generated many at this size and tested them that do scan but now finding that some don't scan.
There are no errors and does not show any form of border like its even detecting it.

This one
https://i.imgur.com/MHdnezn.png
Works fine though, so confused what could be wrong.

I am testing with this page https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html
Any help would be appreciated.

**Comment by gruhn** [comment]
I can reproduce this issue. We use [jsQR](https://github.com/cozmo/jsQR) to process images. Simply, bumping it form 1.2.0 to 1.3.1 fixes the issue on my side. I rebuilt the demo page. Please confirm.

**Comment by lobonz** [comment]
Amazing, thankyou for fixing that so fast.
All my codes now work again which is great as I have a few thousand parts out there already labelled :)
