### ISSUE TITLE
Inconsistencies between browsers 

### ISSUE THREAD

**Issue by bennymakesstuff** [gruhn/vue-qrcode-reader#194]
**The Bug Symptoms**
I am using QrcodeStream in my Vue application (Served over HTTPS/SSL).
The stream is requesting access on first use in all browsers.
The following is a list of working and not working after access is granted to the camera.
Worth noting is no error messages present at all in any browser. I have also inspected over remote debugging for mobile browsers.

**Working as Expected**
- Desktop (Ubuntu 20.04LTS): Chromium 84.0.4147.105
- Desktop (Ubuntu 20.04LTS): Firefox 79.0
- iPhone (14.0 Developer Beta): Safari iOS

**Not Working**
- iPhone (14.0 Developer Beta): Chome iOS (Expected not to work as described in documentation)
- Android 7.1.1: Chrome Android 61.0.3163.98
- Android 7.1.1: Firefox Android 68.11.0

I will also preface this with your live examples working fine on all devices and I have 1 for 1 copied the code over.

Any start point for investigation would be appreciated.

**Comment by gruhn** [comment]
So everything works on the demo page, right? Also are you saying that you are prompted for camera access permission even in iOS Chrome? That would be interesting.

From first glance: Chrome 61 is from July 2017 or something. That's 3 years old. Maybe updating does the trick for this one at least.

**Comment by gruhn** [comment]
I also just fixed a Firefox bug in v2.3.12. The demo page should be up-to-date so please check if the problem persists there in Firefox on your device.
