### ISSUE TITLE
MediaStreamError in Firefox

### ISSUE THREAD

**Issue by 1995Everton** [gruhn/vue-qrcode-reader#195]
**Resume**
I am testing the compatibility of my web application and found an error that is only happening in Firefox. The error happens even in the demo

**Expected Functionality**
Scan the qr code through the `` init`` event

**Actual Functionality**
The camera is not being loaded on the page, even after granting permission, both on localhost and in production

**Error Report**
```
MediaStreamError : {
      constraint: "",
      message: "Starting video failed",
      name: "AbortError"
 }
```

**Screenshots**
Demonstration
![lib-qrcode-reader](https://user-images.githubusercontent.com/47858939/89454839-ac2c9f00-d737-11ea-99e6-80ac2671040e.png)
MyApp Error Console
![console-myapp](https://user-images.githubusercontent.com/47858939/89454848-b189e980-d737-11ea-8fd7-4795d59504d2.png)

**Desktop:**
 - (Ubuntu 18.04LTS): Firefox 79.0

**Note**
I am using version ^ 2.3.11, before that I was using version ^ 2.1.1 and he pointed out the following error:
```
TypeError: s()(...)[0].getCapabilities is not a function
```

**Comment by 1995Everton** [comment]
It seems that the first "Starting video failed" error that I mentioned and causing when you have another browser using the camera at the same time, however, another error appears when we just leave the firefox open. I tried your demo on the Desktop (Windons 10 64-bit) Firefox 79.0 and it worked

**New Error Report**
``` TypeError: r.getCapabilities is not a function ```

**Screenshots**
![Captura de tela de 2020-08-06 12-10-04](https://user-images.githubusercontent.com/47858939/89548741-c8831700-d7dd-11ea-8a0c-9be3d0804cc9.png)

**Comment by gruhn** [comment]
> however, another error appears when we just leave the firefox open. I tried your demo on the Desktop (Windons 10 64-bit) Firefox 79.0 and it worked

So is it working or not on the demo page?

**Comment by 1995Everton** [comment]
Yes, the demo is working on all browsers that I tested, sorry for bothering. My application calls the "getCapabilities" method, however, in the Firefox documentation (https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/getCapabilities) they don't support this method, could it have something to do with the error I'm experiencing?

**Comment by gruhn** [comment]
You're absolutely right. Please check if this resolves your isssue:
```
npm i vue-qrcode-reader@2.3.12-alpha.1
```

**Comment by 1995Everton** [comment]
Yes, worked perfectly, thank you very much!

**Screenshots**
![Captura de tela de 2020-08-07 11-15-55](https://user-images.githubusercontent.com/47858939/89654873-ae117200-d89f-11ea-9fb3-5f79ed174dbe.png)
