### ISSUE TITLE
Not working on IOS Chrome

### ISSUE THREAD

**Issue by hendri1** [gruhn/vue-qrcode-reader#196]
**Describe the bug**
Can't access for device iOS with chrome browser

**Screenshots**
![image](https://user-images.githubusercontent.com/12600578/89485573-4853b600-d7cb-11ea-9900-1c78f29c23be.png)

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: 13.3
 - Browser: Chrome
 - Version: 84

**Comment by gruhn** [comment]
This is a known issue and unfortunately we can't do anything about it. See #29
