### ISSUE TITLE
Problem with aztec and barcodes

### ISSUE THREAD

**Issue by estebancores** [gruhn/vue-qrcode-reader#199]
im trygin to read aztec codes but it doesn't work. what can i do to be able to read those kind of codes

**Comment by gruhn** [comment]
This library can only process QR codes out of the box. You have the option to pass a WebWorker implements arbitrary scanning procedures: 

**https://gruhn.github.io/vue-qrcode-reader/api/QrcodeStream.html#props**

**Comment by carcade** [comment]
> im trygin to read aztec codes but it doesn't work. what can i do to be able to read those kind of codes

Do you have any success implementing aztec code reading with vue-qrcode-reader?

**Comment by estebancores** [comment]
> > im trygin to read aztec codes but it doesn't work. what can i do to be able to read those kind of codes
> 
> Do you have any success implementing aztec code reading with vue-qrcode-reader?

No man, I have to use this library to create my own aztec code reader, it also works with a several kind:

https://github.com/zxing/zxing

I hope you can solve your problem

**Comment by carcade** [comment]
> > > im trygin to read aztec codes but it doesn't work. what can i do to be able to read those kind of codes
> > 
> > 
> > Do you have any success implementing aztec code reading with vue-qrcode-reader?
> 
> No man, I have to use this library to create my own aztec code reader, it also works with a several kind:
> 
> https://github.com/zxing/zxing
> 
> I hope you can solve your problem

Thanks for reply!
