### ISSUE TITLE
Doesn't work with Vue native

### ISSUE THREAD

**Issue by waqaskhann** [gruhn/vue-qrcode-reader#206]
I get this error:
Requiring module "node_modules/vue-qrcode-reader/dist/VueQrcodeReader.umd.min.js", which threw an exception: TypeError: undefined is not an object (evaluating 'window.document.currentScript')

**Comment by gruhn** [comment]
I have no experience with Vue Native. But from a quick glance at the docs I found this: 

>  If you want to use a third party library refer to react-native packages instead of vuejs especially if the library uses render function or is dependent on html since vue-native does not work on html.

https://vue-native.io/docs/community-libraries-doc.html

I guess that rules out using this library, sorry :/
