### ISSUE TITLE
Stops scanning after about 30 seconds

### ISSUE THREAD

**Issue by joehewitt** [gruhn/vue-qrcode-reader#207]
**Describe the bug**
The reader stops decoding after 30-60 seconds. 

**To Reproduce**
Visit one of the live demos. Trying scanning for a period of time. Expect to see the the tracking rectangle stop appearing within less than a minute. No more QR codes will be decoded after this. You must reload the page to continue scanning. 

I am seeing this on iOS 14 Safari using 2.3.13 of this library. I have had this problem for a while dating back to iOS 13 and a 1.x version of this library. To scan more than a few QR codes I have to keep reloading the page. I am surprised this bug hasn't been reported yet as it has been present for quite a long time. I should have reported it long ago.

**Comment by gruhn** [comment]
hmm, in both Desktop Chrome and Android Chrome it keep working for me for at least 3 minutes straight. Can you reproduce this on non-iOS devices?

**Comment by joehewitt** [comment]
It's clearly an iOS-specific bug. Do you test on iOS? One odd thing I noticed - I connected Safari on my iPhone to the developer console on my Mac and that seemed to alleviate the issue. As soon as I disconnected the dev console and reloaded the page the problem reappeared. 

I don't have any Android devices to test on personally.

**Comment by joehewitt** [comment]
I was reading some other bug reports and read you state that you don’t have any iOS devices to test with. I would strongly advise that you make a big bold disclaimer on the front page of this repo that states that iOS compatibility is not verified. If I had known that I probably wouldn’t have wasted so much time trying to make this module work on my iPhone.

**Comment by gruhn** [comment]
I do have an iPhone SE on iOS 13.7 by now. I just checked and couldn't still can't reproduce. Scanning worked for 3 minutes straight.

**Comment by joehewitt** [comment]
I've found the root of the problem. It's a bug in iOS Safari that affects jsQR and causes the worker to shut down. I have yet to find a workaround. Here is the jsQR bug report:

https://github.com/cozmo/jsQR/issues/157

**Comment by realmarkomalis** [comment]
@gruhn could this PR please be reviewed/merged? It would solve a lot of issues for me.

**Comment by gruhn** [comment]
Ah I overlooked this PR. Reviewing now!

**Comment by realmarkomalis** [comment]
No worries, happens to the best. Tnx for checking it immediately!
