### ISSUE TITLE
overlay class possibly conflicting with app css style

### ISSUE THREAD

**Issue by tewfik-dj** [gruhn/vue-qrcode-reader#208]
The default tracking seems to use an `overlay` class by default.
If you happen to have the same class declared globally in your project, then there is the possibility of a conflict, and maybe unexpected behavior.

I suggest a short warning to be added to the readme.md file so that people won't run into this (like me).
The ideal fix (imho) would be to rename such a generic class and use a prefix to ensure uniqueness. (e.g: `qrcode-reader-*`)

Thanks!

**Comment by gruhn** [comment]
Thanks for pointing this out. I blindly assumed the new CSS-in-JS approach would cause all `class` attributes to be replaced with inline `style`.

**Comment by gruhn** [comment]
fix is out: [v2.3.14](https://github.com/gruhn/vue-qrcode-reader/releases/tag/v2.3.14)

**Comment by tewfik-dj** [comment]
> fix is out: [v2.3.14](https://github.com/gruhn/vue-qrcode-reader/releases/tag/v2.3.14)

Thanks for the quick fix! Appreciated.
