### ISSUE TITLE
Vue Native Error

### ISSUE THREAD

**Issue by GeRaged** [gruhn/vue-qrcode-reader#210]
Hey,

I tried to setup vue-qrcode-reader on vue-native but I get this error on ios emulator

Unrecognized event: {"type":"client_log","level":"error","data":["TypeError: undefined is not an object (evaluating 'window.document.currentScript')"]}

Got this error in this file VueQrcodeReader.umd.min.js.
I used npm to install the packages.

**Comment by gruhn** [comment]
ahh yes, this came up before: #206

I'll update the docs.
