### ISSUE TITLE
Browser field in package.json

### ISSUE THREAD

**Issue by chaitanyapotti** [gruhn/vue-qrcode-reader#212]
**Describe the bug**
Please don't specify `browser` field in package.json.
it causes webpack to use umd build to bundle which doesn't de-deduplicate dependencies and causes code bloat.

if you want to specify browser field, Please use some configuration like this [here](https://github.com/torusresearch/torus.js/blob/feat/rollup/package.json#L7)
(Assuming you have an esm build. If not, not specifying `browser` field is better)

#### Reasoning
As seen [here](https://cli.vuejs.org/guide/build-targets.html#library), cjs build should be used by bundlers and not umd

**Comment by gruhn** [comment]
thanks for pointing that out. Field is removed in next release.
