### ISSUE TITLE
Camera does not initialize in browser on Android 8.0 (Chrome)

### ISSUE THREAD

**Issue by OneMoreRound82** [gruhn/vue-qrcode-reader#213]
I have built a very small app to utilize the QR code scanner - this works fine on desktop with the browser (Chrome) asking me to allow access to the camera.  However this does not happen when I access it on mobile.  I have noticed other people having similar issues so I have included a link to my code on paste in.  I'm pretty sure I'm doing everything correct as it works on desktop and I've taken the code from the examples.

https://pastebin.com/5NRVYKpx

Thanks

**Comment by totzibecker** [comment]
Same problem here on all Andriod devices. On OSX the QR codes are detected fast.
This problem has been known here, but it seems it can't be fixed

**Comment by OneMoreRound82** [comment]
I found the issue to this.  It was because the domain that I was developing on was not https.  By default for security Chrome doesn't give access to the camera on unsecure domains.  There's a setting in chrome somewhere (can't remember where) to override this though.  So the issue is not with the plugin, but the browser.
