### ISSUE TITLE
Error.name：'insecureContextError'

### ISSUE THREAD

**Issue by huyang271** [gruhn/vue-qrcode-reader#218]
It happens on devices based on Android 5.0 in the capacitor application.

I have no idea...

SOS!!!

**Comment by gruhn** [comment]
It usually means you are not using HTTPS.

**Comment by huyang271** [comment]
> It usually means you are not using HTTPS.
> 
> You might find this useful: https://github.com/gruhn/vue-qrcode-reader#im-running-a-dev-server-on-localhost-how-to-test-on-my-mobile-device-without-https

It may not be the reason for the https protocol. There is no problem in the mobile browser, but when I package it as a webapp with Capacitor, it does not work properly. The same problem also occurs when I package it with Cordova.

I'm not sure what caused it. Currently I tried Android 5.1 (not effective), Android 7.0 (effective) and 9.0 (effective)

If you have some ideas, you can tell me at any time, thank you very much

**Comment by gruhn** [comment]
This is where the exception is thrown:

https://github.com/gruhn/vue-qrcode-reader/blob/dd7f55bf3ba6ba1944069164a33b5677864d1040/src/misc/camera.js#L74-L76

Note that `localhost` counts as secure without https. Everything else does not. Not even your own IP address. You have to use https.
