### ISSUE TITLE
Feature to allow scanning of same code multiple times

### ISSUE THREAD

**Issue by samipetteri** [gruhn/vue-qrcode-reader#219]
Right now it is not possible to read same qr-code in repetition. We would like to use it so that you could reset that flag with a button so the next code could be the same as the one before. 

Meaning, we would like to be able to reset the contentBefore from code below to null programmatically.

https://github.com/gruhn/vue-qrcode-reader/blob/dd7f55bf3ba6ba1944069164a33b5677864d1040/src/misc/scanner.js#L38

**Comment by gruhn** [comment]
Please read the "TIP" section in the api docs of the `decode` event:

https://gruhn.github.io/vue-qrcode-reader/api/QrcodeStream.html#decode

Also checkout the [Pause & Validate demo](https://gruhn.github.io/vue-qrcode-reader/demos/Validate.html) for an implementation example.

**Comment by samipetteri** [comment]
Changing the camera is slow operation and makes the feel ankward so thats why we dont like to use it. I guess we well figure out something else 👍

**Comment by gruhn** [comment]
I assumed it's always fine to bridge the time gap with maybe 1000ms of [micro interaction](https://lottiefiles.com/search?q=check&category=animations).

Otherwise, can you please elaborate your use case?
