### ISSUE TITLE
Can't trigger access to mobile device camera (Adonuxt)

### ISSUE THREAD

**Issue by eromanov** [gruhn/vue-qrcode-reader#22]
Hi,

Running Adonuxt - accessing the page on mobile device doesn't trigger any qrcode activity (i.e. doesn't ask me to access the camera at all). Your demo works perfectly, though! Do you know what I need to do to get it to run on mobile (iOS/Safari)?

Awesome tool. by the way, worked perfectly on my laptop.

**Comment by gruhn** [comment]
hmm... I don't know much about Adonuxt and Nuxt in general. Are you saying the demo worked for you on iOS but not when you tried to implement it yourself? Or did it only work on your laptop?

**Comment by eromanov** [comment]
Hello! Thank you for replying so quickly. 

You're right, the demo worked for me on iOS, and on the laptop (Windows), but when I tried to implement it myself it only worked on the laptop, and not the iOS. I did think it was something to do with server-side rendering, but that all seems OK.

**Comment by gruhn** [comment]
Your welcome :grinning: 

I haven't worked with SSR yet, so I don't know what kind of adjustments this component would require. 

I can't think of anything you need to include. `vue-qrcode-reader` has some external dependencies but npm should take care of that.

Can you provide a something that helps me reproduce your issue.

**Comment by eromanov** [comment]
The component is literally the QR reader and a couple of headers (code attached...)

[qr-reader-dot-vue.txt](https://github.com/gruhn/vue-qrcode-reader/files/1796945/qr-reader-dot-vue.txt)

**Comment by gruhn** [comment]
Looks good to me. I forgot to mention, I have no access to a computer  and can't test anything at least till Thursday. In the meantime you could check if you have the same problem in a non-Adonuxt context. For example the vue-cli webpack template or something. Also:

Don't you get any error messages or console output? Is there a way to debug iOS Safari?

Does the component render at all? Try filling the `slot` and see if it anything is visible:

```javascript
<qrcode-reader>
   Blabla... Some content
</qrcode-reader>
```

Is your page publicly available? I could try to see what happens on Android.

**Comment by eromanov** [comment]
Yeah I'll try that! 

I think it must be something with my set up :) 

I'll let you know if I solve it. Thanks for your help!

**Comment by eromanov** [comment]
Right, the problem was that I wasn't accessing it on my mobile using HTTPS! Flicked to HTTPS, and it's all working like a dream :D :D :D
