### ISSUE TITLE
iOS Capacitor Problem

### ISSUE THREAD

**Issue by mihajlon97** [gruhn/vue-qrcode-reader#222]
Error: ⚡️  [error] - [Vue warn]: Error in callback for watcher "shouldStream": "TypeError: null is not an object (evaluating 'this.cameraInstance.captureFrame')"

Camera permission is allowed.
Iphone 7, iOS 14.3
Any ideas about the error?

**Comment by gruhn** [comment]
Can you reproduce this issue on the demo page?

https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html

**Comment by diadal** [comment]
is there any way to make it work with capacitor apps ios and android
