### ISSUE TITLE
Cannot scan multiple consecutively

### ISSUE THREAD

**Issue by Hsuan1025** [gruhn/vue-qrcode-reader#223]
**Describe the bug**
After continuous scanning, there will be a red frame crashing and the QRcode cannot be scanned anymore.

**Screenshots**
![0126](https://user-images.githubusercontent.com/58675770/105784650-2d147700-5fb4-11eb-9be3-127e02f3a9d5.jpg)

**Smartphone (please complete the following information):**
 - Device:  iPhone6s
 - OS: iOS14.3
 - Browser: safari
 - Version

**Comment by gruhn** [comment]
Do you have the same issue with your device [on the demo page](https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html)?

**Comment by arbisyarifudin** [comment]
Same here. 
My device doesn't have an issue if i console log the error on the init function.
