### ISSUE TITLE
Perform redirection after detecting the QR code

### ISSUE THREAD

**Issue by VladimirVecera** [gruhn/vue-qrcode-reader#224]
Once I detect the QR code, I need to load the URL automatically, for example: /data.php?qrcode= ?? 
How can I do that?

**Comment by gruhn** [comment]
Just perform regular JavaScript redirect: https://stackoverflow.com/a/11690095

```html
<qrcode-stream @decode="onDecode"></qrcode-stream>
```
```js
onDecode(url) {
   window.location.href = url
}
```

**Comment by gruhn** [comment]
https://codepen.io/gruhn/pen/rNxQPay?editors=1111

**Comment by Morrisonleary** [comment]
Awesome, thanks! Just was curious if anyone was using this on a high-level production website.
