### ISSUE TITLE
Can't scan same code in a row and clearing cache doesn't work

### ISSUE THREAD

**Issue by Kirian-snx** [gruhn/vue-qrcode-reader#225]
Hi there,

I start writing a short app to test qrcode scan, but I need to be able to scan the same qrcode with decode. And isn't working.
I see the Tips with 'paused' to clear cache but when I try doesn't do anything and still not able to re-scan my code.

Also I use a modal for popup, with the description of my qrcode.

I want to scan a first time and if I close the popup be able to scan again, can I have some help plz ^^

**Comment by gruhn** [comment]
Have you seen this demo? 

https://gruhn.github.io/vue-qrcode-reader/demos/Validate.html

**Comment by Kirian-snx** [comment]
Oh right, I will try this, but is with 'camera' and not with 'paused' like you said in the tips

**Comment by gruhn** [comment]
Alright :+1: 

Where do you found this information though? The `paused` used to exists but it has been removed a long time ago.

**Comment by Kirian-snx** [comment]
I don't really remember, I do a lot of website to find how to deal with my problem and I end it on a website that say the 'paused' button could clear the cached and so can scan again a qrcode already scan.

**Comment by gruhn** [comment]
ah ok. Outdated thrid-party material then, I guess. Thank you.
