### ISSUE TITLE
QrcodeStream onDecode is cannot produce the same result twice in a row

### ISSUE THREAD

**Issue by richardeakin** [gruhn/vue-qrcode-reader#227]
I've been `QrcodeStream` in my project and it is working well, however I'm seeing that I can't get the same code to fire an `onDecode()` once it has already been detected - I have to use some other code first, before it will give me a callback for the first. Is there some sort of limiter with settings to control this? I tested directly with `jsQR` and it does not seem to be an issue there (though I do need to implement the limiting myself to avoid getting many callbacks of the same type in a short period of time).

Ideally, there would be some sort of 'min time between same code detected' setting but I haven't found it..

Thanks!

**Comment by gruhn** [comment]
Checkout [the "TIP" section in the docs for the `decode` event](https://gruhn.github.io/vue-qrcode-reader/api/QrcodeStream.html#decode). Also checkout the [Pause & Validate](https://gruhn.github.io/vue-qrcode-reader/demos/Validate.html) demo for an example implementation.

**Comment by richardeakin** [comment]
So there is no way to override this? I would consider that a bug (as I need to be able to scan the same qr code twice in a row for my application).

FWIW because of this, I switched to using jsQR directly and added a second timeout that allows the same QR code to be scanned  again after 2 seconds. I think if it were to be more generic, that 2 seconds would be user settable.

**Comment by gruhn** [comment]
It's possible to scan the same QR code twice as presented in the demo above. And it can be done with something like 2 seconds delay between scans. 

If this is not sufficient for you, please elaborate your use case.

**Comment by richardeakin** [comment]
That is sufficient - just didn't work for me in your demo. I can only get a new scan emitted if it is not the same as the previous (regardless of time between scans). I also didn't see any properties around this, seemed internal to QrcodeStream.vue.

**Comment by gruhn** [comment]
So you can't scan the same QR code twice with the [Pause & Validate demo](https://gruhn.github.io/vue-qrcode-reader/demos/Validate.html) ?

It's true that there are no explicit props. The "cache" is cleared implicitly by turning the camera off.

**Comment by richardeakin** [comment]
Seems to work in that example. I tested with "Decode Continuously", where `onDecode()` was only firing if it was a new QR code, regardless of how long I waited. I guess this doesn't work because the camera remains on (and I don't intend to turn it off).

**Comment by gruhn** [comment]
Turning the camera off just has visual effect of pausing the video stream. You still see a still image. It shouldn’t hurt the user flow. If you pause right after a `decode` event the scanned frame is automatically displayed. You can show some [micro interaction](https://lottiefiles.com/search?q=check&category=animations) maybe to signal to users that the QR code has been processed. Then turn the camera ON again to proceed scanning. 

In my opinion this implicit workflow aligns better with the reactive paradigm.

**Comment by richardeakin** [comment]
Suit yourself, your library. Just letting you know that this inflexibility led me to write my own wrapper to suit my needs.

**Comment by gruhn** [comment]
Sure, I still don't understand why the current approach is not compatible with your needs.

**Comment by gruhn** [comment]
Since this keeps coming up, I added a dedicated demo: 

https://gruhn.github.io/vue-qrcode-reader/demos/ScanSameQrcodeMoreThanOnce.html

**Comment by Dekari** [comment]
Hello... in vue3 when i tied to use the demo the camera is well turned off and on but i get 2 console errors and scanning is not available anymore (even if the camera still works)

Console errors:
products.js:1694 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'captureFrame')
    at Proxy.shouldStream (products.js:1694:17180)
    at callWithErrorHandling (app.js:10181:22)
    at callWithAsyncErrorHandling (app.js:10190:21)
    at job (app.js:11799:17)
    at flushPreFlushCbs (app.js:10341:13)
    at updateComponentPreRender (app.js:15750:9)
    at ReactiveEffect.componentUpdateFn [as fn] (app.js:15663:21)
    at ReactiveEffect.run (app.js:8824:25)
    at instance.update (app.js:15724:56)
    at updateComponent (app.js:15549:26)

products.js:1694 Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at u (http://127.0.0.1:8000/js/resource/js/components/store/products.js:1694:105603)
    at f (http://127.0.0.1:8000/js/resource/js/components/store/products.js:1694:105750)
    at Proxy.value (http://127.0.0.1:8000/js/resource/js/components/store/products.js:1694:13734)
    at t (http://127.0.0.1:8000/js/resource/js/components/store/products.js:1694:80029)


Any clue?
