### ISSUE TITLE
Application freeze when pausing or ending stream in chrome android 11

### ISSUE THREAD

**Issue by OnlyBjarne** [gruhn/vue-qrcode-reader#228]
**Describe the bug**
When pausing/ending the camera stream in Chrome for Android 11 the application freezes and the user has to close and reopen the browser app.

Works in Firefox Android

Works on Decode Continuously demo
Freezes on Pause & Validate demo

**To Reproduce**
1. Open chrome for android 11
2. Go to: [Pause and validate](https://gruhn.github.io/vue-qrcode-reader/demos/Validate.html
)
2. Scan a qr-code
3. Freezes when pause

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy S20 FE]
 - OS: [Android 11]
 - Browser [Chrome]
 - Version [88]

**Comment by hyrumcoop** [comment]
I'm also experiencing this in Chrome 88 with a Pixel 4a (Android 11). Haven't tested it in Firefox yet.

**Comment by aarhus** [comment]
You don't need to close the browser - if you start to switch to a new window and just return to Chrome it works fine!
