### ISSUE TITLE
QrcodeStream Fails to Initialise if Permission is Permanently Granted

### ISSUE THREAD

**Issue by stefanadelbert** [gruhn/vue-qrcode-reader#230]
**Describe the bug**
When using Firefox, when the component mounts for the first time, permission is requested and if granted, all works as expected. If permission is granted permanently though, the next time the component mounts the stream does not display. I was able to replicate this behaviour at https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html.

In my code it appears to me as if the promise passed by the `init` event is not resolving or rejecting.

**To Reproduce**
- go to https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html
- when asked for permission, select the relevant device and check "Remember this decision"
- close the browser window
- go (again) to https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html
- notice that the component doesn't load

**Screenshots**
Notice how the browser shows that camera has been allowed, but the component does not load fully.

![image](https://user-images.githubusercontent.com/2541773/108955699-b9ed4600-76c2-11eb-8719-52a6866c8e57.png)

**Desktop (please complete the following information):**
 - OS: Linux (Linux 5.11.0-1-MANJARO #1 SMP PREEMPT Mon Feb 8 07:36:52 UTC 2021 x86_64 GNU/Linux)
 - Firefox
 - 85.0.2 (64-bit)

**Comment by gruhn** [comment]
Thanks for reporting this. I can't reproduce it though. I get this result though when the camera is already in use. For example when site is also opened in Chrome. Could that been an issue in your case?

It's weird that Firefox does not shows "ERROR: is the camera already in use?" in this case. Chrome does.

**Comment by stefanadelbert** [comment]
I was also surprised that I didn't get any error message and I think this has to do with the promise passed to the `init` function not being resolved (or rejected).

I got Firefox 86.0.1 yesterday and I've just started a fresh desktop session. I went directly to https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html and could see a red flashing camera in the URL bar (i.e. access to the camera was allowed), but the qrcode component didn't load. So that's the same behaviour with nothing else running.

If I keep the Firefox window open (with the component not loading, but the camera supposedly "in use") and then open a Chromium window at the same location, I get the component loading up fine. I'm able to open another Chromium window at the same location and again get the component loading up fine, i.e. two simultaneous instances of the component loading up fine in Chromium.

Please let me know if there is anything else you'd like me to try out.

**Comment by gruhn** [comment]
When I said I couldn't reproduce it, I tried it on Ubuntu Firefox 85.*. I now upgraded to Firefox 86 but still can't reproduce it :man_shrugging: 

I really just guessing but I see you have a lot of browser extensions installed. Could that have anything to do with it?
