### ISSUE TITLE
In iPhone, Safari in iOS

### ISSUE THREAD

**Issue by flourigh** [gruhn/vue-qrcode-reader#232]
**Describe the bug**
Using your demo Upload file, in iOS, the camera open without option to select image galery
This app work in this scenário https://www.ginifab.com/feeds/qr_code/qr_code_scanner.html

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus
 - OS: 14.2
 - Browser Safari

**Comment by gruhn** [comment]
See #167
