### ISSUE TITLE
NotReadableError Cordova

### ISSUE THREAD

**Issue by DamienBouffort** [gruhn/vue-qrcode-reader#235]
**Describe the bug**

When I use qrcode reader in my project, an error appears : ERROR: is the camera already in use?
But no other app uses my camera. 
My vuejs project is separate from my cordova project, they are in two different directories. 
I use "npm run build" to build my vuejs project in the cordova '\www' directory, then "cordova run android" in the cordova project directory for testing

**Smartphone :**
 - Device: Galaxy S8
 - OS: Android 9
 - Wrapper for VueJS app: Cordova

**Comment by vesper8** [comment]
@DamienBouffort did you ever figure it out? I'm also using Cordova, with an S9. Works perfect on IOS.. but `NotReadableError` on this S9. Would really help some tips if you figured it out, or else an alternative?

Thanks!
