### ISSUE TITLE
export 'QrcodeStream' was not found in 'vue-qrcode-reader'

### ISSUE THREAD

**Issue by isakemanuel** [gruhn/vue-qrcode-reader#237]
I was unable to import the package using the installation instruction. 

```
import { QrcodeStream }  from "vue-qrcode-reader"

export default {
  components: {
    QrcodeStream
  }
}
```
Using the code above yielded the error `export 'QrcodeStream' was not found in 'vue-qrcode-reader'`

The workaround I used was to import it directly from source
```
import { QrcodeStream }  from "vue-qrcode-reader/src/index.js"

export default {
  components: {
    QrcodeStream
  }
}
```

**Comment by BaihakiTanjung** [comment]
<img width="639" alt="Screen Shot 2021-09-30 at 11 01 28" src="https://user-images.githubusercontent.com/58780032/135385065-9f2cb998-4670-4249-ac63-4daa2400bdca.png">
Like thi its work
