### ISSUE TITLE
v3 release breaks ipad/safari compatibility

### ISSUE THREAD

**Issue by kris-sum** [gruhn/vue-qrcode-reader#239]
**Describe the bug**
The v.3.0.0 release breaks compatibility for ipad. Previous v2 release worked fine.

**To Reproduce**
Browse demo page on an ipad

**Screenshots**
Debugging the ipad remotely, I get
  
    Error in callback for watcher "shouldScan": "TypeError: Reflect.construct requires the first argument be a constructor"
    found in
    ---> <QrcodeStream>
 
  
    vue.runtime.esm.js?2b0e:1889 TypeError: Reflect.construct requires the first argument be a constructor
    | globalHandleError | @ | vue.runtime.esm.js?2b0e:1880
    | handleError | @ | vue.runtime.esm.js?2b0e:1840
    | run | @ | vue.runtime.esm.js?2b0e:4571
    | flushSchedulerQueue | @ | vue.runtime.esm.js?2b0e:4311
    | (anonymous) | @ | vue.runtime.esm.js?2b0e:1981
    | flushCallbacks | @ | vue.runtime.esm.js?2b0e:1907
    | promiseReactionJob
    
 - Device: iPad (5th gen)
 - OS: iOS 13.6.1
 - Browser: Safari

**Comment by CrAsH1101** [comment]
We are experiencing same error on iPhone devices too (v13.7, v14.4).
Any clues?

**Comment by zch233** [comment]
We are experiencing same error on iPhone devices too (v13.7, v14.4). too
Any clues?

**Comment by DaiND1902** [comment]
I has the same issue.

**Comment by yknamja** [comment]
I have the same problem too.
