### ISSUE TITLE
Issues with Nuxt deployment and mobile camera access. 

### ISSUE THREAD

**Issue by shot-codes** [gruhn/vue-qrcode-reader#241]
**Description**
I am experiencing similar issues to https://github.com/gruhn/vue-qrcode-reader/issues/22
- I am using `qrcode-stream` with Nuxt. I have set it up as plugin and it works as expected on desktop when running the development server. I get no prompt on mobile devices across various browsers (I have tested on major browsers on both iOS and Android).
- In https://github.com/gruhn/vue-qrcode-reader/issues/22 the issue raiser mentioned that the issue was that they weren't using HTTPS and addressing that solved the problem. I have since deployed with Netlify, and when I access the app I don't see any request for the camera on any device/browser at all. Find the app here https://sleepy-mestorf-6aa5d8.netlify.app

**To Reproduce**
It is tough to add a minimal example using fiddle with Nuxt. I can absolutely add the steps to reproduce, as well has refernce my repository. It is a barebones Nuxt app with a single page where I have attempted to add your components.

**Desktop (please complete the following information):**
 - OS: MacOS 11.2.3 
 - Browser safari, chrome, firefox
 - Version: 3.0.0

**Smartphone (please complete the following information):**
 - Device: iPhone 12, Samsung Galaxy s8
 - OS: iOS 14.5, Android 9
 - Browser safari, chrome, firefox
 - Version 3.0.0

**Comment by MDileg** [comment]
Hello programmer team, I create a project with nuxt 3, and use qr-scanner package, my project run successfully and camera works, but when i shared my project to another device with my (ip and port) camera not working, it shows me (No camera found), but I know i get all access in browser and computer, please help how i solve that problem
