### ISSUE TITLE
German characters

### ISSUE THREAD

**Issue by ajdinmuratovic35** [gruhn/vue-qrcode-reader#242]
Hello, when QR code that holds the name with German characters is scanned the decoded result does not show the German characters. Can you please let me know why is this and how to resolve it?

Regards

**Comment by gruhn** [comment]
![CC82809E-A79B-4216-A11B-A10484065789](https://user-images.githubusercontent.com/26570572/118398415-cbf2db00-b658-11eb-8097-6ad75d3642b7.jpeg)

can‘t reproduce

**Comment by ajdinmuratovic35** [comment]
you are right! The issue comes up from QR code creator not reader!

**Comment by gruhn** [comment]
alright :+1:
