### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by beruic** [gruhn/vue-qrcode-reader#247]
Hi guys!
I used this plugin in a vue2 app and it worked perfectly. Very cool component for Vue. The only one with camera scanner feature I think.
No I am trying to use it in another app with Vue 3 and Typescript and it does not work with Typescript either.
It would be nice to have TS support as well.

_Originally posted by @skykit-alejandrorodriguez in https://github.com/gruhn/vue-qrcode-reader/issues/203#issuecomment-832137537_

**Comment by gruhn** [comment]
Right. If anybody is motivated to take of that, I'll be happy to merge it. Just don't have a lot of time on my hands at the moment.
