### ISSUE TITLE
 Uncaught TypeError: Invalid attempt to iterate non-iterable instance.

### ISSUE THREAD

**Issue by t8ysn** [gruhn/vue-qrcode-reader#249]
When using any of the tracking examples, I keep getting the error:

`
app.483c306a80639a7201bc.hot-update.js:20 Uncaught TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _createForOfIteratorHelper (app.483c306a80639a7201bc.hot-update.js:20)
    at VueComponent.paintBoundingBox (app.483c306a80639a7201bc.hot-update.js:164)
    at app.js:149380`

**Comment by gruhn** [comment]
Do you get the same error on the demo page?

**Comment by t8ysn** [comment]
No but I effectively copied the code form the demo page with respect to tracking
