### ISSUE TITLE
Can you please release latest version to npm ?

### ISSUE THREAD

**Issue by rajagopalx** [gruhn/vue-qrcode-reader#25]
Thanks for the JsQr update.

**Comment by gruhn** [comment]
Sorry it takes so long. I encountered some performance problems due to the upgrade

**Comment by rajagopalx** [comment]
ohh no problem.  Current version have good performance. We do many hundred of QR scan with help of your library. Once again thanks a lot for this library.

**Comment by gruhn** [comment]
Hmm... Must be something on my side then. If you say it's fine I'll trust you.

**Comment by rajagopalx** [comment]
Extremely Sorry Gruhn.  I meant current version to 0.7.1.  Sorry for not mentioning the version.

**Comment by rajagopalx** [comment]
I installed the latest version (0.7.2) and tested with some random QR codes.  I feel QR codes are not get scanned as fast as in 0.7.1.

**Comment by gruhn** [comment]
Yeah, don't worry. I'll see what I can do.
