### ISSUE TITLE
imageData is null

### ISSUE THREAD

**Issue by fraaalk** [gruhn/vue-qrcode-reader#250]
When using QrcodeDropZone or QrcodeCapture **@detect** event as described in the api (https://gruhn.github.io/vue-qrcode-reader/api/QrcodeCapture.html#events), imageData inside the returned promise is always null. 

In https://github.com/gruhn/vue-qrcode-reader/blob/master/src/misc/scanner.js#L28 its set to null.
Is it possible to pass the imageData? This is necessary to display a preview of the uploaded or dragged file.

Copy the api example and console.log(imageData)

 - OS: macOS 11.2.2
 - Browser Chrome
 - Version 91.0

**Comment by Call-ship-it** [comment]
Same issue. Is there any solutions?

**Comment by nabenzine** [comment]
This bug is really anoying, is there any news on that?

Thank you!

**Comment by gruhn** [comment]
No news. Sorry I’m too busy to debug this. If anyone is able to pin this down I’ll be happy to merge.
