### ISSUE TITLE
QR-code-reader stops working after some minutes

### ISSUE THREAD

**Issue by LauwersA** [gruhn/vue-qrcode-reader#252]
I implemented a qr-code-reader on a site. Everything works fine on my tablet.  If I lay my tablet aside for a couple of minutes and want to scan another code, it can't be detected anymore. There also is'nt a red rectangle indicating detection. I'm sure both codes work and after i refresh the page, everything works fine again for some time.  
I already tested is with android tablets and ipads. I keep getting the same behaviour.

**Comment by gruhn** [comment]
Yeah, probably duplicate of #233. Bottom line: I can't reproduce it.
