### ISSUE TITLE
Fix Import to work with SSR

### ISSUE THREAD

**Issue by JemiloII** [gruhn/vue-qrcode-reader#259]
**Describe the bug**
Every time I load this module on an ssr page with nuxt. My application throws an error as it is looking for browser globals. Please check for these globals so that it doesn't crash with an SSR load!

**To Reproduce**
Create a nuxt with SSR enable and load the qrcode-stream element.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/5192788/129458106-0f1d2ffd-4768-4a1a-a92c-d517181550e8.png)

**Desktop (please complete the following information):**
ALL

**Smartphone (please complete the following information):**
ALL

**Comment by gruhn** [comment]
It's difficult to eliminate these SSR errors. The library relies heavily on Web APIs. A workaround might be something like:
```html
<template>
  <client-only>
    <qrcode-stream />
  </client-only>
</template>

<script>
export default {

  components: {
    'qrcode-stream': async () => {
      const { QrcodeStream } = await import("vue-qrcode-reader")
      return QrcodeStream
    }
  }

}
</script>
```
