### ISSUE TITLE
Drag and Drop Image to decode

### ISSUE THREAD

**Issue by monsdroid** [gruhn/vue-qrcode-reader#26]
In some situations its not possible to access the camera device (e.g. no camera present/not supportet api)
In such cases it would be nice to be able to `drag and drop` or `file choose` an image to feed to the decoder which is already there.
The Panel could be a AspecRatio container derived from the video constraints or extra parameters to the component. AR settings should superseed height/width these days.

Best regards and thanks for the great work so far! Using your component in cooking-cloud.com App. so far no bugs/error reports from testing people

**Comment by gruhn** [comment]
Sorry, it took so long. I was totally overthinking how to implement this.

**Comment by monsdroid** [comment]
Thanks for taking the Ratio into Account!
