### ISSUE TITLE
Safari iOS debugging due to window.isSecureContext

### ISSUE THREAD

**Issue by platdesign** [gruhn/vue-qrcode-reader#260]
Following line prevents debugging on iOS devices in a not secure context with `allow media capture on insecure sites`-option enabled in debugger:

https://github.com/gruhn/vue-qrcode-reader/blob/35f718f6dd3f1926e25501af80984fdd4d8b7f28/src/misc/camera.js#L74

**Comment by gruhn** [comment]
Random idea: can you monkey patch it in the console?
```
window.isSecureContext = true
```

**Comment by platdesign** [comment]
@gruhn Exactly what i did to determine if the check (`window.isSecureContext !== true`) is my problem - before opening the issue. ;)

```js
if (process.env.NODE_ENV === 'development') {
	Object.defineProperty(window, 'isSecureContext', { value: true });
}
```

BTW: For my case it's not relevant anymore. Added SSL-certs to dev-env for having a secure context.

**Comment by gruhn** [comment]
Ah ok, so this would be a workaround for other people? I'm not sure what to do about other than just leaving this issue open for other people to find 🤷‍♂️
