### ISSUE TITLE
Vue 3 - Quasar v2.1.0: components dont render

### ISSUE THREAD

**Issue by luntovsky** [gruhn/vue-qrcode-reader#263]
**Describe the bug**
vue-qrcode-reader was running fine on quasar v1.9.6 (vue 2)
after updating to quasar v2.1.0 (vue 3) vue-qrcode-reader wouldn't render components QrcodeStream, QrcodeDropZone and QrcodeCapture despite having installed release "3.1.0-vue3-compatibility.2" of vue-qrcode-reader.

**To Reproduce**
Sry couldn't build a min.js file of 3.1.0-vue3-compatibility.2 release to include in jsFiddle.
Here are all the steps to reproduce the issue.
Install Quasar:
```
npm install -g @quasar/cli
```
Create new Quasar V2 Project:
```
quasar create qrcode-test
```
confirm everything with enter, until creation process has started:
```
cd qrcode-test
yarn add vue-qrcode-reader@3.1.0-vue3-compatibility.2
quasar dev
```
import and muont vue-qrcode-reader inside **src/pages/Index.vue**:
```
<template>
  <q-page class="flex flex-center">
    <QrcodeStream />
  </q-page>
</template>

<script>
  import { defineComponent } from 'vue';
  import { QrcodeStream } from 'vue-qrcode-reader'
  
  export default defineComponent({
    name: 'PageIndex',
    components: { QrcodeStream }
  })
</script>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/33714789/134354513-89df5162-b252-4bc8-9886-1025062e1279.png)
![image](https://user-images.githubusercontent.com/33714789/134354590-65f45b69-f46b-4611-a1c0-fe06144bbe68.png)

**Desktop**
 - OS: macOS Big Sur
 - Browser: safari
 - Version 14.1.1

**Comment by mila76** [comment]
I used https://www.npmjs.com/package/vue3-qrcode-reader and work correctly
