### ISSUE TITLE
Cordova iOS support?

### ISSUE THREAD

**Issue by bitterdev** [gruhn/vue-qrcode-reader#265]
Hey there. Great add-on. For the PWA this is working like a charm. Anyway. We also have native app versions and i'm not able to get this running on iOS. When i run within the emulator i get error messages like insecure context and in iOS device i get the error message that there is no camera available. Is there a trick? 3rd-party add-on required? Some config tweaks? Thanks.

**Comment by samydoesit** [comment]
What hostname is your cordova app using?

I also had this insecure context error (SSL error) when building a capacitorjs app for android and ios.
When i first tried it in development the hostname in capacitor.config.js was something like "localhost:3000".

Try to change it for development to "localhost" just remove the port. The insecure context error on iOS was gone in my case.
