### ISSUE TITLE
iOS 15 cannot preview imge from camera but it still using camera

### ISSUE THREAD

**Issue by Pixmann** [gruhn/vue-qrcode-reader#266]
I have problem on iOS when I upgrade iOS version to iOS 15.

The camera still open but cannot preview image from camera.

It can preview image from camera when I go out from web page and come to web page again.

i don't know when i open your web demo it still working but my web page is not.

My Current installed version of vue-qr-code-reader is 3.0.3 and version of vue cli is 4.5.13 (ฺBuild Vue2)

**Comment by potados99** [comment]
Same problem here :(

**Comment by uaru** [comment]
I have the same problem.

I think the problems is the same as in https://github.com/gruhn/vue-qrcode-reader/issues/264.

**Comment by uaru** [comment]
Another workaround is to change the orientation of the device, eg. from vertical to horizontal, and back - this is probably the quickest way to force the browser to repaint the camera area without reloading.

**Comment by st4nny** [comment]
At this moment i have put in onInit method an alert() with custom message, after close, the camera will appear correctly.

**Comment by mnordstr** [comment]
> 
> 
> Ok, I have a theory. Can you guys confirm that [this demo](https://gruhn.github.io/select-camera-demo/) reproduces the problem?

Reproduces for me on iOS 15.0.1 (iPhone 11 Pro).

**Comment by mnordstr** [comment]
> 
> 
> Also, does the issue still occur here (pick any demo): https://gruhn.github.io/select-camera-demo/dist/
> 
> Otherwise I have a fix.

Here it works immediately.

**Comment by gruhn** [comment]
Fix is out: https://github.com/gruhn/vue-qrcode-reader/releases/tag/v3.0.4

I'll close this. Make a noise if the issue still occurs.

**Comment by rtybanana** [comment]
This is still happening for me on an iPad Air 2 running iOS 15.1.

**Comment by guizmo51** [comment]
Hey I also have the same issue on iOS 15.2.1  using 3.1.0 version.
How can I quickly fix it or help ? 
Thanks !
