### ISSUE TITLE
Total canvas memory use exceeds the maximum limit (256 MB)

### ISSUE THREAD

**Issue by danikupers** [gruhn/vue-qrcode-reader#267]
Hello,

After scanning multi QR codes after each other (tried on different iPhones 7,8, 12) with Browser Safari , we are getting random (not every time after the same amount of scans) an Console error: Total canvas memory use exceeds the maximum limit (256 MB), it doens't want to scan than anymore. 

I'm using the continously modus

Is there any solution for this?

Greets Dani

**Comment by gruhn** [comment]
Do you have iOS 15 on these devices?

**Comment by danikupers** [comment]
Hi, no 13 and 14

Verstuurd vanaf mijn iPhone

**Comment by mobjelo** [comment]
I have the same issue on the latest iOS 15.
I leave the camera constantly on for scanning and then after a while no QR codes will be detected anymore.

Only on iPad's.

In some cases I see this message appearing in the iPad console logs:
"Total canvas memory use exceeds the maximum limit (736 MB)" 
in 
VueQrcodeReader.common.js:9221

Looks like there is a memory loop.

**Comment by danikupers** [comment]
Yes i think its a memory loop.
I couldn't fix it, so i used an external barcode scanner (bluetooth, click on on iphones) with vuejs  , many times faster.
