### ISSUE TITLE
Camera selection

### ISSUE THREAD

**Issue by AuspeXeu** [gruhn/vue-qrcode-reader#269]
If someone has multiple rear cameras, how would the user select which one he wants to use?

**Comment by gruhn** [comment]
Ideally users don‘t have to make that decision and we can always pick an appropriate rear camera by default. If you have a device where this is not the case please elaborate.

**Comment by AuspeXeu** [comment]
I have a Microsoft Surface Pro with a front and a rear camera. By default, the rear camera that is selected is the virtual camera of OBS Studio which I also have installed on my device. Unfortunately, there is no way to select a different rear camera. However, I have seen other websites to give the option to choose which camera to provide access to so it must be maybe an option that is passed to the browser when asking for camera permissions?

**Comment by robertsLando** [comment]
@gruhn What about handle `camera` as a id in the default case (if the id matches some of available media devices) ? 

I mean here: https://github.com/gruhn/vue-qrcode-reader/blob/master/src/misc/camera.js#L55

```js
return devices.find(d => d.deviceId === camera) ? { deviceId: { exact: frontCamera.deviceId } } : undefined
```

**Comment by gruhn** [comment]
I gave in. Passing a deviceId is now possible via the [`constraints`](https://master--vue-qrcode-reader.netlify.app/api/QrcodeStream.html#constraints) prop.
