### ISSUE TITLE
h is not a function type error on browser version

### ISSUE THREAD

**Issue by Piping** [gruhn/vue-qrcode-reader#27]
Hi, 

I try to run the vue code directly from browser.

After all, execution exception happened.

here is the segment of the code 

```js
keepDecoding: function() {
                    var e = this;
                    if (this.shouldDecode) {
                        var t = this.captureFrame();
                        window.requestAnimationFrame(function() {
                            var r = t.data
                              , n = t.width
                              , i = t.height
                              , o = h()(r, n, i);  // this is error
                            null !== o && (e.decodeResult = o.data),
                            window.setTimeout(e.keepDecoding, 400)
                        })
                    }
                },
```

**Comment by gruhn** [comment]
Seems like [jsQR](https://github.com/cozmo/jsQR) is missing in your environment. This is the JavaScript library we use to scan QR codes.

What do you mean by 

> I try to run the vue code directly from browser.

Have you installed `vue-qrcode-reader` with a NPM or via script import? Both should be sufficient to automatically include all dependencies like `jsQR`.

**Comment by Piping** [comment]
Hi,
i did not use npm install, but use script tag directly  from readme.me file!

**Comment by gruhn** [comment]
Sorry, I totally forgot about this. Also sorry because this issue turned out to be totally my bad. I ran the browser build with the old `jsQR` version while using the new API. Should be fixed now.
