### ISSUE TITLE
Qr code Drop Zone 

### ISSUE THREAD

**Issue by markblackburn77** [gruhn/vue-qrcode-reader#275]
If your device defaults to the wrong camera, please [open this demo](https://gruhn.github.io/vue-qrcode-reader/select-camera-demo.html).
You should see a list of all cameras installed on your device.
Copy the list and mark the camera that was picked by default and the camera that should actually be picked.
For example like this:

```
FaceTime HD Camera (Built-in)     [DEFAULT]
A different Camera                [PREFERRED]
Another different Camera
```

**Comment by gruhn** [comment]
You have to follow these ☝️ instructions. Please don't just post the instructions themselves here.
