### ISSUE TITLE
[bug] QrCodeCapture opens camera on smartphones

### ISSUE THREAD

**Issue by robertsLando** [gruhn/vue-qrcode-reader#278]
**Describe the bug**
QrcodeCapture is actually opening camera instead of gallery onsmartphones. Just go on your demo caputre from a phone and check

**Smartphone (please complete the following information):**
 - Device: iPhone and Android
 
Ref: https://github.com/zwave-js/zwavejs2mqtt/issues/1936

**Comment by jmgiaever** [comment]
https://gruhn.github.io/vue-qrcode-reader/demos/Upload.html

This normal "file input" for example opens up camera.

**Comment by robertsLando** [comment]
I have fixed on my pr by replacing the qr capture using a vuetify file input: https://github.com/zwave-js/zwavejs2mqtt/pull/1956/files#diff-e4bfeb4664ba4b2f60bd94dc8ae9e323e103bae0ceae09a0244cf4193dd94ff2R169

**Comment by gruhn** [comment]
This is supposed to be a feature. It comes from the `capture` attribute on the `input` element: 

```html
<input capture="environment" />
```
You can simply override it with: 
```html
<qrcode-capture :capture="false" />
```
Check the docs: https://gruhn.github.io/vue-qrcode-reader/api/QrcodeCapture.html#props

**Comment by hellmediadev** [comment]
`<qrcode-capture :capture="false" />` did not work for me. [gruhn suggests](https://github.com/gruhn/vue-qrcode-reader/issues/382#issuecomment-1739087365) to use null instead of false. This works.
