### ISSUE TITLE
Qr code scan on Huawei P30 Pro

### ISSUE THREAD

**Issue by thisisforeagle** [gruhn/vue-qrcode-reader#282]
10x lens is selected by default when using this with Huawei P30 Pro.
Can we manually select camera?

**Comment by gruhn** [comment]
Can you show the **exact** list of cameras produced when you open this demo on your device: 

https://gruhn.github.io/vue-qrcode-reader/select-camera-demo.html

**Comment by thisisforeagle** [comment]
Sorry to bother you,

I submitted the issue form on mobile and did not see the link to the demo url.
I've corrected the issue using the code on the demo page.

Thank you,
Darragh King

**Comment by gruhn** [comment]
I'm not sure what you mean...

Can you please post the entire list of cameras from the linked demo page. Including all cameras. Even the ones which are not selected by default. In the exact order. For example list this: 

```
FaceTime HD Camera (Built-in)     [DEFAULT]
A different Camera                [PREFERRED]
Another different Camera
```
