### ISSUE TITLE
Safari: QrcodeCapture doesn't show camera streams / @decode/detect don't fire on file upload

### ISSUE THREAD

**Issue by mheiduk** [gruhn/vue-qrcode-reader#283]
**Describe the bug**
On Safari 15.1 (MacOS Monterey 12.0.1) `@decode` or `@detect` don't fire on file upload. Furthermore on iOS Safari 15.1 no front/rear-camera is shown when selected in the QrcodeCapture demo dropdown.

**To Reproduce**
https://gruhn.github.io/vue-qrcode-reader/demos/Upload.html

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.0.1
 - Browser: Safari
 - Version: 15.1

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.1
 - Browser: Safari
 - Version: 15.1

**Comment by arnebr** [comment]
Safari and onChange is a Problem since iOS5, yes  you read that correct. See  https://github.com/scottjehl/Device-Bugs/issues/25#issue-4526877
