### ISSUE TITLE
`QrcodeStream` not supported in iOS Chrome, iOS Firefox, ...

### ISSUE THREAD

**Issue by cbaxter713** [gruhn/vue-qrcode-reader#29]
I have implemented vue-qrcode-reader into my Vue application, and it is working great in Mac desktop Chrome, Firefox and Safari, as well as mobile Safari.  However in iOS Chrome, it is not working and appears to be returning the NotSupportedError error name...however the documentation states that it is supported.  And yes, my site is served over https.

Any thoughts or help would be greatly appreciated

**Comment by gruhn** [comment]
iOS Chrome is forced to use Apples WebView component and therefore has limited capabilities. Until now I assumed those capabilities would be at least equivalent to those of Safari. Since you said it works for you in Safari but not in Chrome though, I was really surprised. 

After a little bit of digging around I found [this](https://support.google.com/chrome/forum/AAAAP1KN0B0CkZPoDcJvjM/?hl=en). It looks like my assumption was wrong. Unless you think this has some different cause for some reason, I'll update the browser support table.

**Comment by gruhn** [comment]
Yeah, my thoughts exactly :/

**Comment by dakshshah96** [comment]
@gruhn Still doesn't work on Chrome for iOS.

**Comment by gruhn** [comment]
@dakshshah96 nope. We still have the same problem. There is no way to fix this. We have to wait for Apple to introduce [getUserMedia support in WKWebView](http://www.openradar.me/33571214). The comment above was auto generated by semantic release and is a little bit misleading. I closed this [in a commit](https://github.com/gruhn/vue-qrcode-reader/commit/43d03ff0549fd796645123e31f1c826618a3717f) where I documented this issue in the README.

**Comment by waziaq** [comment]
Haven't update for this problem? @gruhn

**Comment by gruhn** [comment]
Sadly no: https://bugs.webkit.org/show_bug.cgi?id=208667

**Comment by manofirmz** [comment]
Bro, look that: https://stackoverflow.com/a/54678952

**Comment by gruhn** [comment]
@manofirmz this is related to a different issue. We already include all of these attributes:

https://github.com/gruhn/vue-qrcode-reader/blob/00df74650bf3a8edce9fadb951497d52b7adf5dd/src/components/QrcodeStream.vue#L12-L14

We really can't do anything but to wait for Apple to implement support.

**Comment by manofirmz** [comment]
@gruhn oh, sorry man :/

**Comment by anditsung** [comment]
try using ios firefox it was working fine.
anyone still have problem?

**Comment by gruhn** [comment]
Yes! I can't believe it. After more than 3 years [Apple finally fixed it in iOS 14.3](https://blog.bitsrc.io/ios-14-3-brings-webrtc-to-wkwebview-closing-gap-on-ios-accessibility-90a83fa6bda2). @anditsung thanks for pointing this out.

**Comment by kaosweaver** [comment]
Update your documentation https://gruhn.github.io/vue-qrcode-reader/api/QrcodeStream.html#browser-support so iOS users aren't wondering HOW it is working for them on Safari when the docs say it won't.
