### ISSUE TITLE
QR Code Scan "showConfirmation"

### ISSUE THREAD

**Issue by osahene** [gruhn/vue-qrcode-reader#296]
I am developing a mobile app with Quasar. When the Camera scans a QR code and then the RESULT is valid, I would want there to be a pop up (QDialog) and the message is written in the modal.
I would be very grateful for your assistance.
Please find the code

`

Last result: {{ result }}

<qrcode-stream @decode="onDecode" @init="onInit"/>
<q-btn label="Click me" color="primary" @click="showScanConfirmation = true" />

        <q-card-section>
        <q-btn
            fab
            color="primary"
            icon="verified"
            class="absolute"
            style="top: 0; right: 12px; transform: translateY(-50%);"
        />

        <div class="row no-wrap items-center">
            <div class="col text-h6 ellipsis">
            
            </div>
            
        </div>

        <q-rating v-model="stars" :max="5" size="32px" />
        </q-card-section>

        <q-card-section class="q-pt-none">
        <div class="text-subtitle1">
            Name of product
        </div>
        <div class="text-caption text-grey">
            <p class="decode-result">
                Last result: <b>{{ result }}</b>
            </p>
        </div>
        </q-card-section>

        <q-separator />

        <q-card-actions align="right">
        <q-btn v-close-popup flat color="primary" ripple label="Confirm" @click="secondDialog = true" />
        <q-btn v-close-popup flat class="bg-red" ripple label="Cancel" />
        </q-card-actions>
    </q-card>
    
   </q-dialog>
  

    

    <q-dialog v-model="secondDialog" persistent transition-show="scale" v-show="result ? true : false" transition-hide="scale">
        <q-card class="bg-teal text-white" style="width: 300px">
            <q-card-section>
            <div class="text-h6">Confirmation</div>
            </q-card-section>

            <q-card-section class="q-pt-none">

                <div class="row no-wrap items-center">
                    <div class="col text-h6 ellipsis">
                    I agree to check out prodName 
                    </div>
                    <div class="col-auto text-green text-caption q-pt-md row no-wrap items-center">
                    <q-icon name="verified" />
                    </div>
                </div>
            </q-card-section>
            <q-card-actions align="right" class="bg-white text-teal">
            <q-btn flat label="OK" v-close-popup class="q-mr-2" />
            <q-btn flat label="Cancel" v-close-popup="2" class="bg-blue" />
            </q-card-actions>
        </q-card>
    </q-dialog>
</div>

**Comment by MilosPaunovic** [comment]
[https://codepen.io/milospaunovic/pen/XWzwjqo?editors=1010](https://codepen.io/milospaunovic/pen/XWzwjqo?editors=1010)

**Comment by osahene** [comment]
Good morning,
Please, I beg of you to assist me with a code to perform the task. I would
be very grateful.
Thank you
