### ISSUE TITLE
getUserMedia Issue iOS - Cordova 

### ISSUE THREAD

**Issue by ImranGholizadeh** [gruhn/vue-qrcode-reader#297]
iOS app is calling the device's native camera which is overlaying the getUserMedia stream that we currently have implemented and working on the browser. 
the native camera and its UI are occluding the UI overlaying the getUserMedia stream.

What is expected to happen?
the user grants permission for the app to use their camera which opens the getUserMedia stream and renders the UI that is implemented and working on the browser.

What does actually happen?
the native iOS camera completely covers and occludes the getUserMedia stream and UI and the getUserMedia steam is frozen.

I can give access on testflight. 

**Screenshots**
![IMG_5878 copy](https://user-images.githubusercontent.com/96802946/160286857-6ff0d323-5598-492a-a73a-a570419f8ef7.PNG)
![IMG_5879 copy](https://user-images.githubusercontent.com/96802946/160286860-48dd727f-c491-437f-934e-d39833d47113.jpg)

**Desktop (please complete the following information):**
working on all browsers

**Smartphone (please complete the following information):**
iphone 12 pro max

**Comment by ImranGholizadeh** [comment]
Note that to make getUserMedia work I had to add a new layer of permissions in xcode which worked.. I know the QR reader is working because I can still scan a QR code an get redirected.. however, the UI and stream is occluded by the native camera stream.

**Comment by linxiaowang** [comment]
The same problem just happened to me , is there any solutions about this?

**Comment by ImranGholizadeh** [comment]
Hello linxiaowang,

Yes, this issue has been solved by adding the following code to your config file.

<preference name="AllowInlineMediaPlayback" value="true" />    

Ensure the value for AllowInlineMediaPlayback is true which disables the native full screen controller and allows html5 to play inline on iOS.

Steps
1. Find your config.xml file in your xcode projects staging folder
2. Edit the preference value for AllowInlineMediaPlayback to true

<preference name="AllowInlineMediaPlayback" value="true" />  

3. Rebuild and test getUserMedia on the simulator.
