### ISSUE TITLE
Example code issue ?

### ISSUE THREAD

**Issue by guizmo51** [gruhn/vue-qrcode-reader#30]
Hello ! thanks for your library ! 
however I have an issue.... I used your demo code but it doesn't work on Chrome on MacOS, Firefox for mac or Chrome on android. The decode and locate events are not triggered.  I have no log to provide (no issue in console). 
I tried using https and localhost. thanks for your help !
In attachment : Vue.js debugger in Chrome. locate and decode events seem triggered very late (few minutes after..)
![capture d ecran 2018-04-19 a 11 35 13](https://user-images.githubusercontent.com/2675497/38983965-dca09afe-43c5-11e8-838e-c43ef51c3112.png)

**Comment by gruhn** [comment]
When you say you used the demo code, do you mean you copied the demo code and implemented the ourself or have you used the [demo page](https://gruhn.github.io/vue-qrcode-reader) ?

**Comment by diazabdulm** [comment]
I'm sorry for leaving this comment here but I just want to thank you Niklas. I'm the President of a program and I've been looking all over for a truly working QR code scanner. Yours is the best. Keep it up!

**Comment by gruhn** [comment]
Holy shit, thank you so much :grinning:
