### ISSUE TITLE
Wrong camera selection -> Desk View Camera in iOS 16

### ISSUE THREAD

**Issue by Frost2Ice** [gruhn/vue-qrcode-reader#320]
Please add "Desk View Camera" (iOS 16) into deviceBlackList

```            
Front Camera
Back Camera [DEFAULT]
Back Telephoto Camera
Back Ultra Wide Camera
Desk View Camera [REMOVE THIS PLS]
```

**Comment by gruhn** [comment]
If you open a PR, I’ll quickly merge it. Only make sure format the commit message properly. See: https://github.com/gruhn/vue-qrcode-reader/blob/master/CONTRIBUTING.md#commit-messages

**Comment by Frost2Ice** [comment]
Someone already opened. Thanks to #321 fix(camera): Desk View Camera was added into blacklist

**Comment by gruhn** [comment]
Ah yes, done.
