### ISSUE TITLE
Bug green screen on S9+

### ISSUE THREAD

**Issue by StoreExecution** [gruhn/vue-qrcode-reader#323]
**Describe the bug**
i tried all the demo pages and its not working on my Samsung Galaxy S9+ on chrome  , i just get a green view in both front and back camera , but in firefox it works perfectly fine 

**To Reproduce**
no specific steps i tired  both integrating the API and using the demo it didn't work in both cases 

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://ibb.co/nbpwQmy)

 
**Smartphone (please complete the following information):**
 - Device: [e.g. Andorid]
 - OS: [Android 9]
 - Browser [e.g.Chrome ]
 - Version [e.g. 110.0.5481.65]

**Comment by JustDylan23** [comment]
I can reproduce this on my samsung A8 via the latest chrome version

**Comment by diogenes0803** [comment]
I can reproduce this from note8
