### ISSUE TITLE
iPhone camera goes into DeskView with QR code reader app - RealtimeMediaSource error

### ISSUE THREAD

**Issue by JKcolab** [gruhn/vue-qrcode-reader#336]
I'm writing an app (Quasar, Vue3, Capacitor) which uses awesome vue3-qrcode-reader plug-in (set to QR stream).

This allows me to scan in a QR code, which it does, the first time on my iPhone 12 Pro.

The second time the camera goes to Desk View (Continuity Camera) and I can only reset it by re-loading the app.

Looking at the Xcode console on the second time I see the error messages:

App[1745:620605] RealtimeMediaSource::selectSettings failed constraint 10
I've gone through the Info.plist (and most of the WWW) and found no clues.

I've also followed some advice about adding a line to config.xml without success.

Works fine on Android.

Advice gratefully received.

**Comment by gruhn** [comment]
Probably related to #322
