### ISSUE TITLE
Can't scan qrcode on Iphone 6 plus

### ISSUE THREAD

**Issue by tranthotuong** [gruhn/vue-qrcode-reader#339]
**Describe the bug**
When I update version **from 2.3.18 to 3.1.6**, My iphone scan qr not work.

**Smartphone (please complete the following information):**
 - Device: iPhone6 plus
 - OS: IOS
 - Browser safari
 - Version 12.5.7

**Comment by tintin10q** [comment]
I also have this issue with an Iphone 8

**Comment by tintin10q** [comment]
Don't just auto close the issue?

**Comment by gruhn** [comment]
On the [demo page](https://vue-qrcode-reader.netlify.app/) I don't notice a problem on iPhone SE / iOS 16.6. Can't really do anything about it without some way to reproduce.

**Comment by JCs3lma** [comment]
Experienced it as well in Android 5 and 7

**Comment by tintin10q** [comment]
Would a screen recording help?

**Comment by gruhn** [comment]
better than nothing 😁
