### ISSUE TITLE
Page is not loading qrcode-reader

### ISSUE THREAD

**Issue by Zolak94** [gruhn/vue-qrcode-reader#34]
I installed thispackage and I want to use it in my qrscan.blade.php and i put everything like you said in app.js and made in components file vue-qrcode-reader and put code from TheFirstResultDemo.vue in it and its just not working. Can someone help me get this package to work?

this is my qrscan.blade.php
```
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Vue</title>
		<link href="{{ mix('css/app.css') }}" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div id="app"></div>
                <qrcode-reader @decode="onDecode" :paused="paused"></qrcode-reader>
		<script src="{{ mix('js/app.js') }}"></script>
    </body>
</html> 
```

**Comment by gruhn** [comment]
Can you provide more details on what exactly isn't working. Are the events handlers not called? Does the component just not render? Are there any error messages?

**Comment by Zolak94** [comment]
This is my app.js

```
require('./bootstrap');

window.Vue = require('vue');

import Vue from 'vue' 
import VueQrcodeReader from 'vue-qrcode-reader'
 Vue.use(VueQrcodeReader) 

const app = new Vue({
    el: '#app',
    components: { App },
});
```
and in QRcodeReader.vue i copy pasted TheFirstResultDemo.vue the problem is that its not showing anything just a white page nothing else.

**Comment by gruhn** [comment]
Looks like you are mounting your Vue instance to the `#app` element. From there on Vue only take control over that element and all its child elements. You placed the `qrcode-reader` element outside `#app` though so Vue isn't able to process that. 

Also where exactly do you make use of anything from `TheFirstResultDemo.vue`. Do you have a copy of that in your filesystem? But where do you use/import it? Or have you just copied this...

`<qrcode-reader @decode="onDecode" :paused="paused"></qrcode-reader>`

line from the template?

**Comment by Zolak94** [comment]
so how should my app.js look like? Whole content of TheFirstResultDemo.vue i copied to QrcodeReader.vue and put it in ./components/QrcodeReader.vue

**Comment by gruhn** [comment]
Ok so your `/components/QrcodeReader.vue` is basically a copy of `TheFirstResultDemo.vue` ? First of all you should pick a different name to avoid confusion and naming collisions. 

The component this package provides is called `QrcodeReader` and when you include it in HTML, it should look somewhat like this 

`<qrcode-reader></qrcode-reader>`

TheFirstResultDemo.vue is wrapper for this component so if you copy that component and call it  ./components/QrcodeReader.vue you have a component called QrcodeReader which in turn is using a different component also called QrcodeReader.

But lets first check if at least something works. Leave everything as it is and change you blade template like so:

```html
<div id="app">
  <qrcode-reader></qrcode-reader>
</div>
```
This should make you see something for now.

**Comment by Zolak94** [comment]
My blade is like this now
```
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
		<meta name="csrf-token" content="{{ csrf_token() }}">
        <title>Vue</title>
		<link href="{{ mix('css/app.css') }}" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div id="app">
		<qrcode-reader></qrcode-reader>
		</div> 
		<script src="{{ mix('js/app.js') }}"></script>
    </body>
</html> 
```
Still nothing, blank page if I inspect it there is no errors.

**Comment by gruhn** [comment]
I assume you are using Vue with Laravel. I can only guess what your setup looks like. Is it possible you could share your full code base? Or at least the part that will enable me to reproduce your problem?

**Comment by gruhn** [comment]
Any news? Could you resolve your issue?
