### ISSUE TITLE
Is there any simple example of how to use this?

### ISSUE THREAD

**Issue by barartm** [gruhn/vue-qrcode-reader#35]
Im trying to understand how to use this on a simple white html page, but demo page does not have a simple read code (some obfuscade js and not divs)... browser instructions says "<script src="vue.js"></script>" and there is no vue.js file, if you go to sample source files they are a .vue files, there is no a index.html file or something to start to work with, i think that a simple "example" folder with a index.html file and link to js would be helpful for newbies,

**Comment by gruhn** [comment]
Good point. I'll put together a simpler demo.

**Comment by gruhn** [comment]
How about that? Please tell me if you encounter problems or if you think something could be clearer:

```html
<!doctype html>
<html>
<head>
  <title>Vue QR-Code Reader DEMO</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.16/vue.js"></script>

  <style type="text/css">
    .decoded-content {
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      max-width: 100%;

      color: white;
      font-weight: bold;
      padding: 10px;
      background-color: rgba(0,0,0,.5);
    }

    .error {
      color: red;
      font-weight: bold;
    }
  </style>

  <!-- Download those from: github.com/gruhn/vue-qrcode-reader/dist -->
  <script type="text/javascript" src="vue-qrcode-reader.browser.js"></script>
  <link rel="stylesheet" href="vue-qrcode-reader.css">
</head>

<body>
  <div id="app">
    <qrcode-reader @init="onInit" @decode="onDecode" :paused="paused">
      <div v-if="decodedContent !== null" class="decoded-content">{{ decodedContent }}</div>
    </qrcode-reader>

    <div class="error">
      {{ errorMessage }}
    </div>
  </div>

<script type="text/javascript">
Vue.use(VueQrcodeReader)

new Vue({
  el: '#app',

  data () {
    return {
      paused: false,
      decodedContent: null,
      errorMessage: ''
    }
  },

  methods: {
    onDecode (content) {
      this.decodedContent = content
      this.paused = true
    },

    onInit (promise) {
      promise.then(() => {
        console.log('Successfully initilized! Ready for scanning now!')
      })
      .catch(error => {
        if (error.name === 'NotAllowedError') {
          this.errorMessage = 'Hey! I need access to your camera'
        } else if (error.name === 'NotFoundError') {
          this.errorMessage = 'Do you even have a camera on your device?'
        } else if (error.name === 'NotSupportedError') {
          this.errorMessage = 'Seems like this page is served in non-secure context (HTTPS, localhost or file://)'
        } else if (error.name === 'NotReadableError') {
          this.errorMessage = 'Couldn\'t access your camera. Is it already in use?'
        } else if (error.name === 'OverconstrainedError') {
          this.errorMessage = 'Constraints don\'t match any installed camera. Did you asked for the front camera although there is none?'
        } else {
          this.errorMessage = 'UNKNOWN ERROR: ' + error.message
        }
      })
    }
  }
})
</script>
</body>
</html>
```

**Comment by barartm** [comment]
This is a good start... it works on a single html, now im trying to use this on a laravel blade (because there is not much documentation about using it on laravel or install it with composer) but it give me errors using it on a blade:

@extends('layouts.app')
@section('page-title', 'Scan QR')
@section('page-heading', 'Scan QR')

@section('breadcrumbs')
    <li class="breadcrumb-item">
        <a href="{{ route('scan.index') }}">Scan QR</a>
    </li>
    <li class="breadcrumb-item active">
        Scan QR
    </li>
@stop

@section('content')

@include('partials.messages')

{!! Form::open(['route' => 'scan.index', 'id' => 'scan-qr-form']) !!}
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <h5 class="card-title">
                        Escanear Un Vale
                    </h5>
                    <qrcode-reader @init="onInit" @decode="onDecode" :paused="paused">
      					<div v-if="decodedContent !== null" class="decoded-content">{{ decodedContent }}</div>
    					</qrcode-reader>
    					<div class="error">
      						{{ errorMessage }}
    					</div>
                </div>
            </div>
        </div>
    </div>
{!! Form::close() !!}

<br>
@stop

@section('styles')
<style type="text/css">
    .decoded-content {
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      max-width: 100%;

      color: white;
      font-weight: bold;
      padding: 10px;
      background-color: rgba(0,0,0,.5);
    }

    .error {
      color: red;
      font-weight: bold;
    }
  </style>
<link rel="stylesheet" href="{{ asset('assets/css/vue-qrcode-reader.css') }}">
@stop
@section('scripts')
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.16/vue.js"></script>
<script type="text/javascript" src="{{ asset('assets/js/vue-qrcode-reader.browser.js') }}"></script>
Vue.use(VueQrcodeReader)

new Vue({
  el: '#app',

  data () {
    return {
      paused: false,
      decodedContent: null,
      errorMessage: ''
    }
  },

  methods: {
    onDecode (content) {
      this.decodedContent = content
      this.paused = true
    },

    onInit (promise) {
      promise.then(() => {
        console.log('Successfully initilized! Ready for scanning now!')
      })
      .catch(error => {
        if (error.name === 'NotAllowedError') {
          this.errorMessage = 'Hey! I need access to your camera'
        } else if (error.name === 'NotFoundError') {
          this.errorMessage = 'Do you even have a camera on your device?'
        } else if (error.name === 'NotSupportedError') {
          this.errorMessage = 'Seems like this page is served in non-secure context (HTTPS, localhost or file://)'
        } else if (error.name === 'NotReadableError') {
          this.errorMessage = 'Couldn\'t access your camera. Is it already in use?'
        } else if (error.name === 'OverconstrainedError') {
          this.errorMessage = 'Constraints don\'t match any installed camera. Did you asked for the front camera although there is none?'
        } else {
          this.errorMessage = 'UNKNOWN ERROR: ' + error.message
        }
      })
    }
  }
})
</script>
@stop



Error: 
 ErrorException (E_ERROR)
Use of undefined constant decodedContent - assumed 'decodedContent' (this will throw an Error in a future version of PHP) (View: /home/xxxxxx/xxxxxx/resources/views/scan/scan.blade.php)


<qrcode-reader @init="onInit" @decode="onDecode" :paused="paused">
                          <div v-if="decodedContent !== null" class="decoded-content"><?php echo e(decodedContent); ?></div>
                        </qrcode-reader>

**Comment by gruhn** [comment]
Oh ok, I see what is going on here. Vue and Blade template syntax are not compatible. They both use double curly braces `{{ }}` to insert variable content.

Because Blade is processed first it assumes `{{ decodedContent }}` refers to a PHP variable but in this context it's undefined. 

A workout would be to escape those characters like this: `@{{ decodedContent }}`

See ["Displaying Raw Text With Curly Braces"]( https://laravel.com/docs/5.0/templates)

**Comment by barartm** [comment]
Yep, using the escape works exactly as expected :D lets play now with it

**Comment by gruhn** [comment]
Cool :grinning:

Escaping is probably only a workaround. There are plenty other ways to define Vue templates. But I you can explore those while you advance :blush:

I'll add this demo soon. 

You can close this issue if you consider this done.

**Comment by leondroidgeeks** [comment]
Can someone please provide an example for how to use this with Single File Components? Project was setup with vue-cli. I get the following error:
```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <QrcodeReader>
       <App> at src/App.vue
         <Root>
```

**Comment by gruhn** [comment]
Please show me your entire `.vue` file.

**Comment by leondroidgeeks** [comment]
I ended up importing the distribution files only in my local component. Default import locally didn't work.

```
import 'vue-qrcode-reader/dist/vue-qrcode-reader.css'
import {
  QrcodeReader
} from 'vue-qrcode-reader/dist/vue-qrcode-reader.common'


components: {
    "qrcode-reader": QrcodeReader
  }
```

**Comment by gruhn** [comment]
Note that the default export is not the component itself.

Have you maybe did this

```javascript
import VueQrcodeReader from 'vue-qrcode-reader'

Vue.component('qrcode-reader', VueQrcodeReader)
```

Instead of

```javascript
import VueQrcodeReader from 'vue-qrcode-reader'

Vue.use(VueQrcodeReader)
// Or
Vue.component('qrcode-reader', QrcodeReader)
```

**Comment by gruhn** [comment]
I still haven't published the simple demo. Reopening this to remember myself. Until then people with this problem can find a solution here.

**Comment by Sennik** [comment]
Kind reminder. I'll appreciate a Laravel (5.6+) demo... :-)

**Comment by gruhn** [comment]
@Sennik noted. It might take a while though. I never use Laravel.

**Comment by arshfaisal** [comment]
```
<!doctype html>
<html>
<head>
  <title>Vue QR-Code Reader DEMO</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.16/vue.js"></script>

  <style type="text/css">
    .decoded-content {
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      max-width: 100%;

      color: white;
      font-weight: bold;
      padding: 10px;
      background-color: rgba(0,0,0,.5);
    }

    .error {
      color: red;
      font-weight: bold;
    }
  </style>

  <script src="https://unpkg.com/vue-qrcode-reader@1.2.1/dist/vue-qrcode-reader.browser.js"></script>
  <link rel="stylesheet" href="https://unpkg.com/vue-qrcode-reader@1.2.1/dist/vue-qrcode-reader.css">
</head>

<body>
  <div id="app">
    <qrcode-stream @init="onInit" @decode="onDecode" :paused="paused">
      <div v-if="decodedContent !== null" class="decoded-content">{{ decodedContent }}</div>
    </qrcode-stream>

    <div class="error">
      {{ errorMessage }}
    </div>
  </div>

<script type="text/javascript">
  import VueQrcodeReader from 'vue-qrcode-reader';
  var qrcode = Vue.component('qrcode-stream',{
  template : '#task-template',
  data : function(){
      return this.tasks; //Notice: in components data should return an object. For example "return { someProp: 1 }"
  },
  props : ['task']
});
Vue.use(VueQrcodeReader)

new Vue({
  el: '#app',
components: {qrcode: qrcode},
  data () {
    return {
      paused: false,
      decodedContent: null,
      errorMessage: ''
    }
  },

  methods: {
    onDecode (content) {
      this.decodedContent = content
      this.paused = true
    },

    onInit (promise) {
      promise.then(() => {
        console.log('Successfully initilized! Ready for scanning now!')
      })
      .catch(error => {
        if (error.name === 'NotAllowedError') {
          this.errorMessage = 'Hey! I need access to your camera'
        } else if (error.name === 'NotFoundError') {
          this.errorMessage = 'Do you even have a camera on your device?'
        } else if (error.name === 'NotSupportedError') {
          this.errorMessage = 'Seems like this page is served in non-secure context (HTTPS, localhost or file://)'
        } else if (error.name === 'NotReadableError') {
          this.errorMessage = 'Couldn\'t access your camera. Is it already in use?'
        } else if (error.name === 'OverconstrainedError') {
          this.errorMessage = 'Constraints don\'t match any installed camera. Did you asked for the front camera although there is none?'
        } else {
          this.errorMessage = 'UNKNOWN ERROR: ' + error.message
        }
      })
    }
  }
})
</script>
</body>
</html>
```

**Comment by arshfaisal** [comment]
Hi,
I use your above mention example and I am getting below error:

Vue warn]: Unknown custom element: <qrcode-stream> - did you register the component correctly? For recursive components, make sure to provide the "name" option.


I just cut and paste your code and make HTML file and when i run on browser its showing error in console 

Any solution?

**Comment by chris-faulkner** [comment]
> Hi @gruhn ,
> I use your above mention example and I am getting below error:
> 
> Vue warn]: Unknown custom element: - did you register the component correctly? For recursive components, make sure to provide the "name" option.
> 
> I just cut and paste your code and make HTML file and when i run on browser its showing error in console
> 
> Any solution?

Seems like the code is slightly wrong, but the jsfiddle is right, change <qrcode-stream to <qrcode-reader and the ending too

**Comment by chris-faulkner** [comment]
I just got this set up in a fresh Laravel app if anyone needs help.
Thanks for the great package!

**Comment by gruhn** [comment]
@ghost my bad. The example I posted still included `script` and `link` references to version 1.2.1, although `qrcode-stream` wasn't introduced until `1.3.0`. Hence the error `Unknown custom element: ...`. 

@chris-faulkner jep `qrcode-reader` works but it's deprecated. It got renamed to `qrcode-stream` when the other components (`qrcode-capture`, `qrcode-drop-zone`) where introduced to avoid confusion with the package in general. The jsfiddle version was even less up-to-date then the version in the code snippet. 

I updated the jsfiddle link and removed the code snippet in the comments so I'll don't have to keep both up-to-date all the time.

**Comment by Harrrrry** [comment]
Hi @gruhn ,
can I use the ajax in a method, after adding ajax it stops decoding the QR

`<script type="text/javascript">
Vue.use(VueQrcodeReader)

new Vue({
  el: '#app',

  data () {
    return {
      paused: false,
      decodedContent: null,
      errorMessage: ''
    }
  },

  methods: {
    onDecode (content) {
    	//alert(content);
    	$.ajax({
                      type:"POST",
                      url:site_url+"/qrAttendence",
                      data: { 
                          'student_attandence_data': content
                      },
                      success:function(result){
                      	if(result == '1'){
                      		this.decodedContent = "Welcome student."
                      	}else{
                      		alert('Student booking data not found.')
                      	}
                      }
                      
        })
      //this.decodedContent = content
      //this.paused = true
    },

    onInit (promise) {
      promise.then(() => {
        console.log('Successfully initilized! Ready for scanning now!')
      })
      .catch(error => {
        if (error.name === 'NotAllowedError') {
          this.errorMessage = 'Hey! I need access to your camera'
        } else if (error.name === 'NotFoundError') {
          this.errorMessage = 'Do you even have a camera on your device?'
        } else if (error.name === 'NotSupportedError') {
          this.errorMessage = 'Seems like this page is served in non-secure context (HTTPS, localhost or file://)'
        } else if (error.name === 'NotReadableError') {
          this.errorMessage = 'Couldn\'t access your camera. Is it already in use?'
        } else if (error.name === 'OverconstrainedError') {
          this.errorMessage = 'Constraints don\'t match any installed camera. Did you asked for the front camera although there is none?'
        } else {
          this.errorMessage = 'UNKNOWN ERROR: ' + error.message
        }
      })
    }
  }
})
</script>`

**Comment by chris-faulkner** [comment]
@gruhn Thanks for clarifying that, I've just found your package yesterday so I'm not that familiar. It was pretty simple to add as a component in Laravel though 👍

**Comment by gruhn** [comment]
Now that this issue just points to a jsfiddle link, I simply included the link right in the README.

**Comment by ibailetti** [comment]
> I just got this set up in a fresh Laravel app if anyone needs help.
> Thanks for the great package!

Hello Chris, can you share it?, please.
Im trying to set the proyect up following Laravel best practices.  The ones files that i have to modify are a VUE file "QRCodeReader.vue" in "/resources/components" for the js functionality a file "app.js" in "/resources" to register VUE components (in this case register QRCodeReader.vue) and a view file "qrcode.blade.php" in "/views/pages" to show what the camera its pointing and scan the qrcode image.

**Comment by stella-maris** [comment]
@gruhn I imported the `VueQrcodeReader` globally in my `main.js` file. It works fine and all, but when it comes to my unit test, it throws the error message: 
`[Vue warn]: Unknown custom element: <qrcode-capture> - did you register the component correctly? For recursive components, make sure to provide the "name" option.` 

I thought since I import it globally that I don't need to import it explicitly in my spec file. Is this not the case?

`main.js`: 
```
import VueQrcodeReader from 'vue-qrcode-reader';
Vue.use(VueQrcodeReader);
...
new Vue({
  router,
  store,
  i18n,
  render: h => h(App),
}).$mount('#app');
```

**Comment by gruhn** [comment]
Yes, it should be registered:

https://github.com/gruhn/vue-qrcode-reader/blob/4f9eb7202ed97964f14799fbdc5fc10751511d2e/src/index.js#L6-L10

Hard to tell what's going on with so little context.
