### ISSUE TITLE
Support barcode formats other than QR codes

### ISSUE THREAD

**Issue by gruhn** [gruhn/vue-qrcode-reader#356]
The [barcode detector polyfill](https://github.com/Sec-ant/barcode-detector) used in vue-qrcode-reader [supports a bunch of other barcode formats](https://github.com/Sec-ant/barcode-detector/blob/190c8d351e6ed18aea33b38a46e557750bbe5caa/src/utils.ts#L1-L16) not just QR codes. It's probably not too hard to make use of that in vue-qrcode-reader. Previously, people have ask for that: #199 #49. 

We could add a new prop `formats` on all three components: `QrcodeStream`, `QrcodeDropZone`, `QrcodeCapture`, which accepts an array of strings and/or a single string and passes the value through to the `BarcodeDetector` constructors: [here](https://github.com/gruhn/vue-qrcode-reader/blob/master/src/misc/scanner.ts#L19), [here](https://github.com/gruhn/vue-qrcode-reader/blob/master/src/misc/scanner.ts#L111) and [here](https://github.com/gruhn/vue-qrcode-reader/blob/master/src/misc/scanner.ts#L119). 

Some things to consider: 
1. What if the component prop is changed during scanning? The user probably expects the different formats to be recognized immediately. It's probably necessary to interrupt and restart scanning to construct a new `BarcodeDetector` instance.
2. Different barcode formats look quite different. Will [tracking](https://vue-qrcode-reader.netlify.app/demos/CustomTracking.html) still work as is?

Anyone willing to contribute, I'd be happy to merge your PR :slightly_smiling_face: Also check out [CONTRIBUTING.md](https://github.com/gruhn/vue-qrcode-reader/blob/master/CONTRIBUTING.md)

**Comment by FourAndHalf** [comment]
could you assign me this issue, I am willing to work on it

**Comment by gruhn** [comment]
@FourAndHalf really cool that you want to contribute. Looks like @samydoesit has already started working on this though.

**Comment by FourAndHalf** [comment]
oh, no worries

**Comment by gruhn** [comment]
(Posting new demo videos here, so GitHub will generate me a link)

https://github.com/gruhn/vue-qrcode-reader/assets/26570572/bec5bebe-97b8-446c-b4c5-8681b1567e5c

https://github.com/gruhn/vue-qrcode-reader/assets/26570572/d382d2a9-3fa1-4b28-8821-392c5025045c

**Comment by gruhn** [comment]
closing this. Thanks @samydoesit !
