### ISSUE TITLE
pngquant` binary doesn't seem to work correctly

### ISSUE THREAD

**Issue by barartm** [gruhn/vue-qrcode-reader#36]
[user@server xxxxxxxxxx]$yarn add vue-qrcode-reader
yarn add v1.7.0
info No lockfile found.
[1/4] Resolving packages...
warning laravel-mix > img-loader > imagemin-optipng > optipng-bin > bin-wrapper > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[6/6] ⠐ node-sass
[-/6] ⠐ waiting...
[3/6] ⠐ mozjpeg
[-/6] ⠐ waiting...
error /home/xxxxx/xxxxxxx/node_modules/pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /home/vauroleseg/dashboard/node_modules/pngquant-bin
Output:
⚠ The `/home/xxxxx/xxxxxxxxx/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully

**Comment by gruhn** [comment]
I have no idea what `pngquant` is. It's not an explicit dependency of `vue-qrcode-reader`.

Please check if you get the same error running `yarn add vue-qrcode-reader` in a fresh/empty project directory and if so also check if other dependencies cause the same error when installed via yarn.

**Comment by barartm** [comment]
Is there any way to install it on laravel with composer? i just installed yarn on my server (i never used yarn in my life) in order to install vue-qrcode-reader but it throw me that error and this command created a new folder "node_modules" that inside have 100+ foders.... this is annoying... why so complicated?
