### ISSUE TITLE
Does anybody use the locate event?

### ISSUE THREAD

**Issue by gruhn** [gruhn/vue-qrcode-reader#37]
Does anybody use `locate` for anything other than painting the QR code position over the camera stream like in the [*Track location* demo](https://gruhn.github.io/vue-qrcode-reader/)?

I think it might be a good idea to provide this out of the box and remove `locate`. Maybe by introducing a prop called `track`. You could pass true/false to enable this tracking or pass a repaint function to customize painting. This function would be called to produce each frame. This could look somewhat like this:

```html
<qrcode-reader :track="repaint"></qrcode-reader>
```
```javascript
methods: {
  repaint (canvas2dContext, locationArray) {
    // paint the location to the canvas
  }
}
```

Reactive property mutation (live stuff in `data`or `computed`) in response to `locate` events can become really memory intensive. I believe this is because Vue handles reactive property updates asynchronously. `locate` can be triggered several times a second. This fills up the event loop or something. I'm not really sure there but replacing `locate` with `track` should avoid this problem.  

If you like/don't like this idea, have additional suggestions or have a different use case for `locate` please come forward 😊

**Comment by rajagopalx** [comment]
I too used `locate` only for painting  QR Code. Initially, I faced little bit struggle to achieve this. After seeing your example code only I make it working.  It's very good idea that QR Code  painting  out of the box.
