### ISSUE TITLE
Can format related modules be added to vue qrcode reader v3. *? Version 3. * cannot scan barcodes,

### ISSUE THREAD

**Issue by dolin-tan** [gruhn/vue-qrcode-reader#372]
Can format related modules be added to vue qrcode reader v3. *?    Version 3. * cannot scan barcodes

**Comment by gruhn** [comment]
That should be possible. We would have to 
* branch-off the latest v3 commit
* install sec-ants barcode-detector polyfill 
* and repeat the steps in #356
If someone would like to pick this up, I’d be happy to merge it :)
