### ISSUE TITLE
what is  Chrome requires HTTPS or localhost ?

### ISSUE THREAD

**Issue by a123likeyou** [gruhn/vue-qrcode-reader#38]
on my phone is the error: error.name === 'NotSupportedError'
what can  i do  to deal with the problem

**Comment by rajagopalx** [comment]
Do you connect your phone via Remote Devices option in Chrome? If yes then localhost is enough. 

You can find Remote Devices under `More Tools->Remote Devices`

**Comment by rajagopalx** [comment]
Or else try [ngrok](https://ngrok.com/)  or [serveo](https://serveo.net/)

**Comment by a123likeyou** [comment]
My project was developed on the web site, and now I'm going to test the results of the scan through my cell phone, but the address is not localhost or HTTPS on my mobile phone, so the ambulance reports this error on the page. How should I solve it?

**Comment by rajagopalx** [comment]
Try ngrok. You can turn your http address into https. Do you using windows or linux or mac ?

**Comment by a123likeyou** [comment]
I am using window, so now I try to change the address to HTTPS. Is this the only way to do it?

**Comment by rajagopalx** [comment]
There may be other ways. But above one is an easy way.

Refer:
https://www.youtube.com/watch?v=oy13mDsXC4s  (ngrok)
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/  (Chrome Remove Device Debugging)

**Comment by a123likeyou** [comment]
OK, thank you very much

**Comment by rajagopalx** [comment]
Welcome
