### ISSUE TITLE
capture="false" does not work in iOS Safari any more

### ISSUE THREAD

**Issue by hellmediadev** [gruhn/vue-qrcode-reader#382]
**Describe the bug**
passing false to the :capture attribute of `<qrcode-capture>` should load a file dialog instead of the camera.
In iOS 16.6.1 on Safari the camera is loaded as soon as there is a capture attribute - no matter of which value.

**To Reproduce**
This DOM element is created by the template:
<input type="file" name="image" accept="image/*" capture="false" multiple="">
Try this element in Safari iOS 16

**Desktop (please complete the following information):**
 - OS: 16.6.1
 - Browser Safari

**Comment by gruhn** [comment]
Have you tried 
```
:capture="null" 
```
like in the [demo](https://vue-qrcode-reader.netlify.app/demos/Upload.html) ? Note, the colon `:` is important.

**Comment by hellmediadev** [comment]
> Have you tried
> 
> ```
> :capture="null" 
> ```
> 
> like in the [demo](https://vue-qrcode-reader.netlify.app/demos/Upload.html) ? Note, the colon `:` is important.

Thank you for your great support. With `null` it works.

**Comment by hellmediadev** [comment]
Would be great to be mentioned in https://gruhn.github.io/select-camera-demo/dist/api/QrcodeCapture.html ❤️

**Comment by gruhn** [comment]
Huh? How did you find that link? That's not even the old link to the documentation but the GitHub pages deployment for [some random side repo](https://github.com/gruhn/select-camera-demo) I created for debugging 😅 

FYI: official documentation is here: https://vue-qrcode-reader.netlify.app/ 😉 (but that one is also worth updating)
