### ISSUE TITLE
Error when trying to include vue and vue-qrcode-reader

### ISSUE THREAD

**Issue by preoteasa** [gruhn/vue-qrcode-reader#384]
I have tried to include vue and vue-qrcode-reader in the head of a simple html file:

```
<script src="./vue.global.prod.js"></script>
<script src="./vue-qrcode-reader.umd.cjs"></script>
```

I believe I used the latest versions of both files. However I get the following error:

Uncaught TypeError: Ve.use is not a function
    at vue-qrcode-reader.umd.cjs:3:34148
    at vue-qrcode-reader.umd.cjs:1:199
    at vue-qrcode-reader.umd.cjs:1:233

I wrote an example inspired from the simple live demo:

https://vue-qrcode-reader.netlify.app/demos/Simple.html

But this simple demo does not seem to work either.

**Comment by Sec-ant** [comment]
This looks like a problem of the execution order. Can you check whether adding `defer` works?

```
<script defer src="./vue.global.prod.js"></script>
<script defer src="./vue-qrcode-reader.umd.cjs"></script>
```

**Comment by preoteasa** [comment]
It does not work. In addition I get a new error from the html body about Vue not being found.

**Comment by gruhn** [comment]
Sorry that "Simple" demo was broken for a while already (for various reasons). Should be fixed now. @preoteasa Can you confirm? To fix your local version you also need to upgrade to v5.4.7.

**Comment by preoteasa** [comment]
Thank you. I managed to run the Simple demo, and based on it, I also managed to update my example to work. I did not manage to scan a code yet, as my computer camera is quite bad and it does not focus. I have to set it up to be able to open it from the phone.
