### ISSUE TITLE
如图示错误，无法编译

### ISSUE THREAD

**Issue by edrp** [gruhn/vue-qrcode-reader#389]
![image](https://github.com/gruhn/vue-qrcode-reader/assets/4567753/9194fb8a-ed5b-4904-a83f-f31199181f6c)

**Comment by Sec-ant** [comment]
webpack 4 不认识 `import.meta`，webpack 5 文档显示[支持 `import.meta.url`](https://webpack.docschina.org/api/module-variables/#importmetaurl)。如果不能升级 webpack 版本的话，应该可以通过 babel loader 插件 [`babel-plugin-transform-import-meta`](https://github.com/javiertury/babel-plugin-transform-import-meta) 解决
