### ISSUE TITLE
Not working on iOS safari (latest 11.4)

### ISSUE THREAD

**Issue by xvaara** [gruhn/vue-qrcode-reader#39]
![1b70f505-ce3c-40f1-8219-854809816c50](https://user-images.githubusercontent.com/130606/41344859-cd398268-6f0a-11e8-821e-e17baaa2eb41.jpeg)
Tested on iPad also, same error.

**Comment by gruhn** [comment]
No idea where this is suddenly coming from. I'm not really positive this is related to your issue but I just pushed an update to the demo page so you might want to check again (make sure to clear your cache).

If you already tried to implement something with `vue-qrcode-reader` you could try to fallback to version  `0.7.3` and tell me if that works on your devices. You can install it via 

```
yarn add vue-qrcode-reader@0.7.3
# or
npm install --save vue-qrcode-reader@0.7.3
```

Checkout the documentation for this version [here](https://github.com/gruhn/vue-qrcode-reader/tree/f2957a5ad6459d21856148a3a42f1405e072abae).

**Comment by xvaara** [comment]
I attacked a console to my iphone and it said this:
![screen shot 2018-06-14 at 10 37 05](https://user-images.githubusercontent.com/130606/41398422-f49e9464-6fbf-11e8-8fe1-9f98ceb1b5c2.png)

**Comment by xvaara** [comment]
just quickly tested my iphone and it supports only 640x480 ad 1280x720 resolutions. Tried with this: https://webrtchacks.github.io/WebRTC-Camera-Resolution/

**Comment by gruhn** [comment]
Hmm... in theory [it should be fine](https://github.com/gruhn/vue-qrcode-reader#video-constraints-prop) but this error message indeed indicates that something is wrong there. 

Unfortunately, I have no iOS device to test on :disappointed: . I have to rely on you to find the cause. Can you setup a test project with `vue-qrcode-reader` and play around with the `video-contraints` prop? Try to pass different resolution configurations and see if that changes anything. Somewhat like this:

```html
<qrcode-reader :video-constraints="constraints"></qrcode-reader>
```
```javascript
data () {
  return {
    constraints: {
      width: 640,
      height: 480
    }
  }
}
```

The easiest way to get started is probably to clone the demo page and run the included dev-server:

```bash
git clone -b gh-pages git@github.com:gruhn/vue-qrcode-reader.git
cd vue-qrcode-reader/dev

# then
yarn install
yarn run dev

# or
npm install
npm run dev
```
If you're not familiar with this workflow, don't hesitate to ask. I'll explain in detail or will provide an easier way!

**Comment by thwonghenry** [comment]
I confirmed that passing `{ width: 640, height: 480 }` as `video-constraints` can init the camera with `vue-qrcode-reader@0.8.2` on iOS 11.4.
But compared with Android, it is incredibly choppy that it renders the camera ~5 seconds a frame.
(The scanning is still fast when I point my camera to the QR code, even if the QR code is not showing in the video frame yet.)

**Comment by gruhn** [comment]
@thwonghenry thanks for helping me out. Can you also check if [this](https://thomasbilliet.com/react-qr-reader/) works better.

**Comment by thwonghenry** [comment]
@gruhn it works fine with the default delay (500 ms)

**Comment by gruhn** [comment]
What do you mean by *default delay*? Delay until the stream starts or delay between frames?

Can you also check if it still works with the following constraints object:

```javascript
{
  width: { ideal: 680 },
  height: { ideal: 480 }
}
```

**Comment by bakoversalto** [comment]
Very handy component! 
Could this barcode-reader solve the issues with iOS? Seems to work fine on my iPhone
https://serratus.github.io/quaggaJS/

**Comment by gruhn** [comment]
@thwonghenry sorry, I suggested the wrong properties:

```javascript
{
  width: { ideal: 640 }, // NOT 680
  height: { ideal: 480 }
}
```

I'm trying to figure our if Safari has a problem with the `ideal` property in general. Both QuaggaJS and react-qr-reader seem to avoid this property by default. After some digging around with google I believe `ideal` is at least not causing errors as long as specific values are used (the ones @xvaara mentioned).

As for the potential `scan-interval` property, I hope I'm able to optimize `vue-qrcode-reader` so that this is not necessary. Especially because visual tracking requires high frame rates. For people who don't rely on that feature (can be disabled with `:track="false"`) we could automatically set higher scan intervals though. What do you think @thwonghenry ?

**Comment by thwonghenry** [comment]
@gruhn Oh the constraints with `ideal` works now, didn't notice the wrong width. 😂 Thanks.

I think your approach on scan interval having a sensible default value is great, which should be good for now.
But eventually, I think the library should still allow developers to tune for their needs 🤔, their application's supported devices can be different and cannot be controlled by the library.

**Comment by gruhn** [comment]
Cool! I'll push an update soon so you can do a final check. I'll also include a new demo with visual tracking disabled so you can check if performance is acceptable. 

Maybe your right. I like to keep the components API as simple as possible though. Although just another prop isn't really a big deal, those stack up quickly. Usually my opinion is:

_simplicity + convenience > ultra configurable_

I'll prefer to wait until people come up with valid use cases.

Thanks for helping @thwonghenry @bakoversalto

**Comment by gruhn** [comment]
@thwonghenry updated demo page :up:

**Comment by thwonghenry** [comment]
@gruhn Sorry I was busy past few days. I tried your demo page and it works really well now, thanks a lot!
