### ISSUE TITLE
Component types not included in library

### ISSUE THREAD

**Issue by ttoino** [gruhn/vue-qrcode-reader#390]
Even though this library is made using typescript, and types are included for the `misc` package, types are not included for the components themselves, which show up as `any`.

![image](https://github.com/gruhn/vue-qrcode-reader/assets/14280476/b0d12fc3-5bf3-4f6a-8fff-cada03eb08b9)

**Comment by Sec-ant** [comment]
Seems related: https://github.com/qmhc/vite-plugin-dts/issues/277

**Comment by Dyskal** [comment]
hi, since the 5.5.0 version, the component types are no longer included!
