### ISSUE TITLE
The h5 page is used in the Android app, and the native input tag is used in the h5 page for uploading pictures. There is no problem in uploading pictures. But clicking on qrcode returns NotAllowedError directly, and the Android app opens the album and camera permissions

### ISSUE THREAD

**Issue by LunckyB** [gruhn/vue-qrcode-reader#392]
I have two buttons, one is the upload picture button, the second is to click evoke scan function. uploading pictures is no problem, click scan code to report an error;

"vue-qrcode-reader": "^3.1.0"
<qrcode-stream @decode="onDecode" camera="auto" :torch="false"></qrcode-stream>

It works fine on ios, android is not

**Comment by gruhn** [comment]
`NotAllowedError` indicated that the user has rejected camera access. You might want to check your browser settings and reset permissions. For Chrome on Android: https://support.google.com/chrome/answer/114662?hl=en&co=GENIE.Platform%3DAndroid
