### ISSUE TITLE
Possible Features to Adjust Camera Expossure

### ISSUE THREAD

**Issue by mich1342** [gruhn/vue-qrcode-reader#399]
Hi,

Could we adjust the expossure of the camera? It would be great to scan QR Code shown in a display like OLED screen

**Comment by gruhn** [comment]
Looks like there the API offers something related to exposure:

https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints#exposuremode

Haven‘t tested but I suspect browser support is bad (especially Safari). Anyway, adding a prop for this shouldn’t be too hard.

**Comment by Sec-ant** [comment]
Just add a comment here: There's a write-up on how to properly apply this constraint and check for its support: https://webrtchacks.com/bad-lighting-fix-with-javascript-webcam-exposure/#post-3807-_ttmtkt8og756

**Comment by gruhn** [comment]
Ok so this probably just boils down to adding [two props here](https://github.com/gruhn/vue-qrcode-reader/blob/master/src/components/QrcodeStream.vue#L57). Maybe `exposure-more` and `exposure-time`. Adding the values to the `cameraSettings` object [here](https://github.com/gruhn/vue-qrcode-reader/blob/master/src/components/QrcodeStream.vue#L112-L118). That should automatically trigger the watcher that requests a camera. The `cameraSettings` object is passed to [this function](https://github.com/gruhn/vue-qrcode-reader/blob/master/src/misc/camera.ts#L115-L119) which then calls `runStartTask` [here](https://github.com/gruhn/vue-qrcode-reader/blob/master/src/misc/camera.ts#L27). And there we can somehow implement the logic mentioned in this article:
> Just add a comment here: There's a write-up on how to properly apply this constraint and check for its support: https://webrtchacks.com/bad-lighting-fix-with-javascript-webcam-exposure/#post-3807-_ttmtkt8og756

**Comment by Sec-ant** [comment]
I can look into this after vacation (~2.18).
