### ISSUE TITLE
Improve performance with WebAssembly

### ISSUE THREAD

**Issue by gruhn** [gruhn/vue-qrcode-reader#4]
Scanning a frame for QR codes is a rather expensive operation. The library responsible for this job (`jsQR`) also makes up a major part of the bundle size. Maybe performance could be increased by using a WebAssembly module instead. This component depends on modern browser features anyway so browser support shouldn't suffer too bad?

**Comment by radar155** [comment]
Thank you for your awesome library and your awesome support! Switching to WebAssebly would be a killer feature, both to have better performance and to reduce bundle size. Moreover, it seems that support from major browser it's almost the same both for WebAssembly and getUserMedia/Stream API.
![schermata del 2018-02-06 10-58-57](https://user-images.githubusercontent.com/10564129/35853121-fd1206c8-0b2c-11e8-9b9e-43bcf874f111.png)
![schermata del 2018-02-06 10-58-32](https://user-images.githubusercontent.com/10564129/35853149-079befc8-0b2d-11e8-999e-ebf40dca71b9.png)

Have you ever thought about using WebWorkers? Should they improve performance in this scenario? Maybe using concurrency.. I admit I know nothing about the qr decoding algorithm, I don't know if it can be implemented concurrenlty.
![schermata del 2018-02-06 11-00-07](https://user-images.githubusercontent.com/10564129/35853367-9c1ba5c6-0b2d-11e8-866d-297e9ab0b2a0.png)

**Comment by gruhn** [comment]
Thanks :grin: 

I have no in depth knowledge about QR code processing either. I thought there might be a library that's using WebAssembly out of the box. I haven't found one yet but [quirc-js](https://github.com/zz85/quirc.js) looks promising. It's build with asm.js (I think) and shows pretty decent performance. I really like to get position tracking smoother and quirc-js [seems to do this pretty well](https://zz85.github.io/quirc.js/test_webrtc.html). My previous attempts to migrate to quirc-js caused bad memory leaks though and I don't know why. I can open a pull request to show you my work if your interested. [Bundle impact of quirc.js](https://bundlephobia.com/result?p=quirc-js@1.1.2) is also heavier [compared to jsQR](https://bundlephobia.com/result?p=jsqr@1.0.1).

Web Workers would also be a good idea. I don't even think they have to be used internally in the scanning process. Maybe it's already beneficial to wrap *everything scanning related* in a worker and communicate results with the UI. I wanted to checkout [this package](https://github.com/developit/workerize-loader) for a long time anyway.

However, I'm rather busy at the moment but pull requests are welcome if you like to help :grin::+1:

**Comment by radar155** [comment]
quirc.js is pretty fast! Maybe I could debug that memory leaks but iIm very busy too. If you want, open a PR, I will take a look in few weeks.

**Comment by gruhn** [comment]
I just discovered [AssemblyScript](https://github.com/AssemblyScript/assemblyscript) which compiles TypeScript to WebAssembly. __jsQR__ is written in TypeScript so this might yield some performance gain.

**Comment by StefanFeederle** [comment]
Do you know about the Shape Detection API? It's using native modules to scan for barcodes (and text and faces). This way we could avoid shipping huge js/webassembly bundles.
https://github.com/WICG/shape-detection-api
https://www.chromestatus.com/feature/4757990523535360

**Comment by gruhn** [comment]
Yeah, I heard of it. I hope this becomes usable soon.

**Comment by qnp** [comment]
Hello,
I would appreciate an example of a working Worker using quirc-js, if someone acheived to do it ?
