### ISSUE TITLE
Rear camera doesn't work on some phones

### ISSUE THREAD

**Issue by SalamanderTheGray** [gruhn/vue-qrcode-reader#40]
One few Samsungs phones rear camera doesn't work in your demo app, as in mine. Other in other libs it work but i use vue for my app and your is easiest to use for me right now. There are images.

Front: 
https://drive.google.com/file/d/18WEVo4iyhQpVpyx7ld1A2Q4FhUtRVDhk/view?usp=sharing

Rear:
https://drive.google.com/file/d/1WNGmvRPQj9Wt81yL6KSgXZlBhcsNtyyd/view?usp=sharing

**Comment by gruhn** [comment]
I think this is my bad. I introduced a bug in the latest update. Can you check if it works for you on the demo page now?
