### ISSUE TITLE
Disable capture property on QRCodeCapture

### ISSUE THREAD

**Issue by paulwer** [gruhn/vue-qrcode-reader#404]
Hey everyone,
we want to force this component (QRCodeCapture) to open file manager on mobile, because we combine it with the stream-component in the app itself. As of the capture property is there by default, mobile phones open the camera everytime.

Any suggestions to implement this?

Thank you very much.

**Comment by gruhn** [comment]
You can overwrite it. Something like this:
```html
<qrcode-capture :capture="null" />
```
See: https://vue-qrcode-reader.netlify.app/api/QrcodeCapture.html#props

**Comment by paulwer** [comment]
worked great. thank you very much.
