### ISSUE TITLE
How to avoid wide-angle cameras

### ISSUE THREAD

**Issue by busa2004** [gruhn/vue-qrcode-reader#406]
I want to change deviceBlackList to avoid choosing wide-angle and telephoto cameras.
vue-qrcode-reader 3.1.0, vue 2.6.11 version in use.
Is there any way I can change deviceBlackList?

https://www.npmjs.com/package/vue-qrcode-reader/v/3.1.0
ISO 17.2.1
iPhone 13 Pro Max
Korea

**Comment by gruhn** [comment]
I just configured a legacy distribution channel. Please create a pull request with your changes and target branch [3.x](https://github.com/gruhn/vue-qrcode-reader/tree/3.x). When we merge that, it should publish a new legacy version.
