### ISSUE TITLE
CDN download link returns file does not exist

### ISSUE THREAD

**Issue by yannic-bruegger** [gruhn/vue-qrcode-reader#409]
**Describe the bug**
When trying to download the Without-NPM-Version linked in README.md, unpackage shows that the file is not there.

**To Reproduce**
Click the download link in README.md
https://unpkg.com/vue-qrcode-reader/dist/vue-qrcode-reader.umd.cjs

**Message**

``Cannot find "/dist/vue-qrcode-reader.umd.cjs" in vue-qrcode-reader@5.5.1``

**Comment by gruhn** [comment]
Ah yes, should be `.js` instead of `.chs`:

https://unpkg.com/vue-qrcode-reader/dist/vue-qrcode-reader.umd.js

**Comment by yannic-bruegger** [comment]
Created a tiny PR, thanks! :)
https://github.com/gruhn/vue-qrcode-reader/pull/411
