### ISSUE TITLE
Serious bug（严重的bug）

### ISSUE THREAD

**Issue by carpONE** [gruhn/vue-qrcode-reader#410]
在 vue2 ^2.5.22使用最新版5.5.1出现Object(...)is not a function
![image](https://github.com/gruhn/vue-qrcode-reader/assets/81232339/e240acca-2f12-4d62-b6d7-e8f03bfe1cd1)

**Comment by Sec-ant** [comment]
5 开头的大版本是适配 vue3 的。

https://github.com/gruhn/vue-qrcode-reader?tab=readme-ov-file#how-to-make-it-work-with-vue-2

**Comment by carpONE** [comment]
非常谢谢您的回答，这种情况需要怎么解决
![image](https://github.com/gruhn/vue-qrcode-reader/assets/81232339/ce2a38b1-64bc-4c2a-a6ee-5a8e3d404ba7)
