### ISSUE TITLE
版本3.1.9是否支持formats？如果不支持我应该如何实现？

### ISSUE THREAD

**Issue by carpONE** [gruhn/vue-qrcode-reader#413]

**Comment by Sec-ant** [comment]
见 #372，需要有需求的开发者贡献代码，并参考 https://github.com/gruhn/vue-qrcode-reader/issues/406#issuecomment-1882875138 提交 PR。

**Comment by carpONE** [comment]
在本地调试中，我加了data_matrix参数，扫码时还是不支持data_matrix类型？
![image](https://github.com/gruhn/vue-qrcode-reader/assets/81232339/12eadc6d-4dd8-4f52-bb48-40cd73efb1fd)

**Comment by Sec-ant** [comment]
如果在[这个 demo 页面](https://vue-qrcode-reader.netlify.app/demos/CustomTrackingWithFormats.html)中 `data_matrix` 是能够正常工作的，那么问题就不是出在 `BarcodeDetector` 中，而是可能出在你实现方式上。建议先用最小的可复现 demo 来定位问题出现的位置和原因，并参考 5.x 版本的代码调整 3.x 的结构。

**Comment by carpONE** [comment]
我不太确定是否BarcodeDetector 的版本问题，这个demo版本是可以的，但这个demo是5.x版本，由于5.x版本中的BarcodeDetector与3.x版本的不一样，3.x版本的BarcodeDetector 版本是1.0.3在npm官网上没有

**Comment by Sec-ant** [comment]
> 我不太确定是否BarcodeDetector 的版本问题，这个demo版本是可以的，但这个demo是5.x版本，由于5.x版本中的BarcodeDetector与3.x版本的不一样，3.x版本的BarcodeDetector 版本是1.0.3在npm官网上搜索不到

你需要更新 BarcodeDetector 版本。实际上 BarcodeDetector 1.x 是另外一个包，现在已经不维护了，它也不支持其他 formats。目前继续维护的版本是 2.x，所以这个依赖需要升级到 2.x。

**Comment by carpONE** [comment]
是的，升级后是可以识别了，我是否 可以推送到3.x分支上？

**Comment by Sec-ant** [comment]
> 是的，升级后是可以识别了，我是否 可以推送到3.x分支上？

ok，不过我并不是本仓库的维护者，提交 PR 时建议用英文写明做了哪些修改，然后让仓库拥有者 @gruhn 审查修改并合并。

**Comment by carpONE** [comment]
好的，谢谢

**Comment by carpONE** [comment]
提交失败，是不是网络问题？显示如下：
![image](https://github.com/gruhn/vue-qrcode-reader/assets/81232339/43f2e668-b971-4bf0-b45c-7c9f05d76e73)

错误内容如下：
WARN  GET https://registry.npmjs.org/--no-install error (ETIMEDOUT). Will retry in 10 seconds. 2 retries left.  WARN  GET https://registry.npmjs.org/--no-install error (ETIMEDOUT). Will retry in 1 minute. 1 retries left. D:\.pnpm-store\v3\tmp\dlx-15668:  ERR_PNPM_META_FETCH_FAIL  GET https://registry.npm.taobao.org/--no-install: request to https://registry.npmjs.org/--no-install failed, reason: connect ETIMEDOUT 104.16.25.34:443  This error happened while installing a direct dependency of D:\.pnpm-store\v3\tmp\dlx-15668

**Comment by Sec-ant** [comment]
像是命令行参数有些问题，搜了一下可能和这个问题有关：https://github.com/pnpm/pnpm/issues/4790

**Comment by carpONE** [comment]
现在出现这个问题，我应该怎么处理，能否帮我提交？：
remote: Permission to gruhn/vue-qrcode-reader.git denied to carpONE. unable to access 'https://github.com/gruhn/vue-qrcode-reader.git/': The requested URL returned error: 403

![image](https://github.com/gruhn/vue-qrcode-reader/assets/81232339/fa3d9676-7b03-4dff-b7aa-f3b2cbc750f5)

**Comment by Sec-ant** [comment]
你不能直接在本仓库创建分支，简单的 PR 提交步骤是：

1. fork 一份本仓库到你的账户下；
2. 将你 fork 的仓库克隆到本地；
3. 本地切换到 "3.x" 分支；
4. 基于 "3.x" 分支新建一个新的分支，名字可以为 "support-formats"，反映你做的修改内容；
5. 将你做的修改提交（commit）到这个新的分支；
6. 将这个新的分支 push 到你 fork 的仓库中；
7. 在 GitHub 上发起 Pull Request，source 是你仓库下的 "support-formats" 分支，target 是这个仓库下的 "3.x" 分支。

你先尝试一下这个步骤，如果你实在遇到困难，再考虑让我帮你提交。
