### ISSUE TITLE
corresponding type declarations

### ISSUE THREAD

**Issue by diadal** [gruhn/vue-qrcode-reader#418]
Cannot find module 'vue-qrcode-reader' or its corresponding type declarations.ts(2307)

**Comment by gruhn** [comment]
> Cannot find module 'vue-qrcode-reader' 

sounds like type declarations are not the issue. Have you ran `npm install vue-qrcode-reader` ?

**Comment by SummerIsComin** [comment]
Cannot find module 'vue-qrcode-reader' or its corresponding type declarations. the same problem
