### ISSUE TITLE
Unable to read PDF417 Barcodes

### ISSUE THREAD

**Issue by thisisayush** [gruhn/vue-qrcode-reader#425]
**Describe the bug**
Tried reading a PDF417 Barcode, and simply unable to read it. Tried with file upload as well just in case.

**To Reproduce**
Here's the PDF417 Cropped that I'm trying to read.
![barcode-pdf417](https://github.com/gruhn/vue-qrcode-reader/assets/22245433/495555c8-7205-4c19-be89-d34440504eee)

**Screenshots**
Not Applicable

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Edge
- Version: Edge Windows (23.0.2420.65)

**Smartphone (please complete the following information):**

- Device: Samsung S22 Ultra
- OS: Android 14
- Browser: Edge, Samsung Internet and Chrome
- Version: Chrome Android (123.0.6312.99), Edge Android (123.0.2420.74), Samsung Internet (24.0.7.1)

**Comment by Sec-ant** [comment]
[This](https://github.com/gruhn/vue-qrcode-reader?tab=readme-ov-file#some-of-my-qr-codes-are-not-being-detected) applies to other formats of barcodes, can you try?

> #### Some of my QR codes are not being detected.
> 
> - Make sure, there is some white border around the QR code.
> - Test your QR codes in the upstream packages: [`barcode-detector`](https://github.com/Sec-ant/barcode-detector) -> [`zxing-wasm`](https://github.com/Sec-ant/zxing-wasm) -> [`zxing-cpp`](https://github.com/zxing-cpp/zxing-cpp), and file detection issues in the highest-level repository where the problem first occurs.
