### ISSUE TITLE
Component not working on mobile patforms

### ISSUE THREAD

**Issue by Ognj3n** [gruhn/vue-qrcode-reader#43]
Hi there, 

Great component by the way. Works fine in the web browser(Google Chrome).

However I have hard time with it when it comes to loading it on mobile. Tryed with Safari and Google Chrome on iPhone 6 and it fails. It's not being loaded at all, and when I try pc's browser responsive option it loads fine there. 

I hope you will give me some hints on how to make this work, since I'm stuck.

**Comment by gruhn** [comment]
Unfortunately, it definitely not works with Google Chrome on iOS (see #29).

What's the iOS version on your phone? 11+ is required.

**Comment by Ognj3n** [comment]
My iOS version is 11.4, however Safari is not loading this component. 

Works fine with Google Chrome on Androind.

**Comment by gruhn** [comment]
iOS is really giving me a hard time lately :man_facepalming: 

I'm on vacation until next week so I have limited options to test right now. Can you somehow connect to the developer console on your phones Safari and check if there are any errors (sorry no idea how this works on iOS).

**Comment by gruhn** [comment]
Any news?
