### ISSUE TITLE
ERROR Failed to execute 'detect' on 'BarcodeDetector': Barcode detection service unavailable. DOMException@ er@ @

### ISSUE THREAD

**Issue by KarryCMT** [gruhn/vue-qrcode-reader#432]
**Describe the bug**
I used the mobile Edge browser to scan the code normally in the development, and the latest Google Chrome browser to scan the code reported an error. Source code and screenshots have been uploaded

**To Reproduce**
### Source code
[code.zip](https://github.com/gruhn/vue-qrcode-reader/files/15282454/code.zip)
**Screenshots**
![image](https://github.com/gruhn/vue-qrcode-reader/assets/43637008/a8ce1e9f-7ec9-40bb-ae8b-7b13301ceb63)
- OS: Windows 10 x64
- Node Version: v14.21.3
**Smartphone (please complete the following information):**
- Device: iPhone 13
- OS: IOS16.5
- Browser : Google Chrome
- Version :125.0.6422.33

**Comment by gruhn** [comment]
@Sec-ant do you think that comes from `barcode-detector` somewhere?

**Comment by Sec-ant** [comment]
The error message comes from here: https://github.com/Sec-ant/barcode-detector/blob/fef9ee4fe1868bbe3fdc2983fe452863322ed732/src/BarcodeDetector.ts#L131-L135, I wonder if you can check if there're error messages logged in the dev tools console?

**Comment by KarryCMT** [comment]
@Sec-ant This is the error log available to me so far, there is no more information to refer to.
![image](https://github.com/gruhn/vue-qrcode-reader/assets/43637008/9fd476ce-180b-4d49-8ed1-faa5fbc09460)
![image](https://github.com/gruhn/vue-qrcode-reader/assets/43637008/836131de-b28e-4f90-843f-086f13bd2a4d)

This is all the dependencies configured for the project
  "dependencies": {
    "core-js": "^3.8.3",
    "vue": "^2.6.14",
    "vue-qrcode-reader": "^3.2.0",
    "vue-router": "^3.6.5"
  },
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "vconsole": "^3.14.6",
    "vue-template-compiler": "^2.6.14"
  },

**Comment by KarryCMT** [comment]
I also had this problem when I tested the scan code on another Android 13 phone，Don't you see how this is related to browser compatibility?
![image](https://github.com/gruhn/vue-qrcode-reader/assets/43637008/6f493d38-5f25-4e07-a5bd-6d5c0592d7d8)
![image](https://github.com/gruhn/vue-qrcode-reader/assets/43637008/20ce0672-c590-41af-9827-3e5492146322)
![image](https://github.com/gruhn/vue-qrcode-reader/assets/43637008/f1e809ef-a8b1-4969-8e1a-0ee087e0d2bb)

**Comment by Sec-ant** [comment]
The `Type Error` - `Load failed` and `Failed to Fetch` both suggest the same cause: The WASM binary cannot be successfully fetched. Would you check the network panel and see if there're failing requests to the `zxing_reader.wasm` file? And there should be a reason why the requests failed.

**Comment by KarryCMT** [comment]
@Sec-ant This is operated on the mobile terminal of the mobile phone, it seems that you cannot view the relevant content of zxing_reader.wasm, right?

**Comment by Sec-ant** [comment]
> @Sec-ant This is operated on the mobile terminal of the mobile phone, it seems that you cannot view the relevant content of zxing_reader.wasm, right?

The content of `zxing_reader.wasm` is irrelevant here. What I want to say is that when the component is loaded, it has to fetch the `zxing_reader.wasm` binary to instantiate the barcode detection module. And from the errors you provided, it seems that the fetch request failed. So I was asking whether you could check the failed requests in the "network" panel in the dev tools?

**Comment by KarryCMT** [comment]
@Sec-ant There is loading zxing_reader.wasm，But still reported an error, is it possible that the request status is wrong, I am on the local LAN access
![image](https://github.com/gruhn/vue-qrcode-reader/assets/43637008/ce246cd7-e06d-4530-af63-c87b1d6479fc)

**Comment by KarryCMT** [comment]
@Sec-ant I tried to use IOS Safari browser and IOS Google Chrome browser, but I couldn't request to get this zxing_reader.wasm file, and an error was reported after the request failed, but Edge browser can get it normally, I don't know what caused it.

**Comment by KarryCMT** [comment]
I know the problem. It's my network

**Comment by Sec-ant** [comment]
If you're on a local network and would like to use this component, you'll have to host the `zxing_reader.wasm` file on your own server. You can find related info [here](https://github.com/gruhn/vue-qrcode-reader?tab=readme-ov-file#i-get-a-failed-to-fetch-error-at-runtime-for-some-wasm-file), or in the repos of [`barcode-detector`](https://github.com/Sec-ant/barcode-detector) and [`zxing-wasm`](https://github.com/Sec-ant/zxing-wasm).
