### ISSUE TITLE
StreamLoadTimeoutError in your demo page

### ISSUE THREAD

**Issue by fessacchiotto** [gruhn/vue-qrcode-reader#436]
On your full demo page I get this error (Safari on MacOs 14.5):

`[StreamLoadTimeoutError]: Loading camera stream timed out after 3 seconds. If you are on iOS in PWA mode, this is a known issue (see https://github.com/gruhn/vue-qrcode-reader/issues/298)`

<img width="786" alt="Screenshot 2024-06-08 at 10 52 59" src="https://github.com/gruhn/vue-qrcode-reader/assets/97323/90185edc-1aa9-4acd-897c-cf5c473873a5">

**Comment by conx13** [comment]
in iPhone12 pwa ios(17.5.1) same error... about a month ago did not occur...
