### ISSUE TITLE
Can i config resolution of camera device?

### ISSUE THREAD

**Issue by alptangal** [gruhn/vue-qrcode-reader#439]
i tested some sample barcode then plugin can't read my sample.
i hope can hear more suggestion
thank you

**Comment by gruhn** [comment]
Have you specified the barcode format via the `formats` prop? 

https://gruhn.github.io/vue-qrcode-reader/api/QrcodeStream.html#formats

**Comment by alptangal** [comment]
`  const barcodeFormats = ref({
  aztec: true,
  code_128: true,
  code_39: true,
  code_93: true,
  codabar: true,
  databar: true,
  databar_expanded: true,
  data_matrix: true,
  dx_film_edge: true,
  ean_13: true,
  ean_8: true,
  itf: true,
  maxi_code: true,
  micro_qr_code: true,
  pdf417: true,
  qr_code: true,
  rm_qr_code: true,
  upc_a: true,
  upc_e: true,
  linear_codes: true,
  matrix_codes: true
})`
here is my config for `formats`, i tried 
`  const barcodeFormats = ref({
  aztec: true,
  code_128: true,
  code_39: true,
  code_93: true,
  codabar: true,
  databar: true,
  databar_expanded: true,
  data_matrix: false,
  dx_film_edge: false,
  ean_13: false,
  ean_8: false,
  itf: false,
  maxi_code: false,
  micro_qr_code: false,
  pdf417: false,
  qr_code: true,
  rm_qr_code: false,
  upc_a: false,
  upc_e: false,
  linear_codes: false,
  matrix_codes: false
})` 
too but plugin can't read my example barcode 128.
then i try with `https://strich.io/`
its working perfectly. so i though maybe the trouble in resolution that camera device received data to detect barcode.
*sorry english is not native language*

**Comment by gruhn** [comment]
Does it also not work on the [demo page](https://gruhn.github.io/vue-qrcode-reader/demos/FullDemo.html)? 

If no, can you try to process your barcode with: https://github.com/Sec-ant/barcode-detector . That's the downstream package we use for detecting barcodes. If this also does not work, the issue is there.

**Comment by alptangal** [comment]
yes, i tried your demo page but its same trouble.
can i connect to you on any chat channel?
