### ISSUE TITLE
Does not work offline due to xzing_reader.wasm depedency 

### ISSUE THREAD

**Issue by Leo-Felde** [gruhn/vue-qrcode-reader#441]
Pretty much the title; The component works wonderfully online however due to a request to get the binary file it doesn't work while offline:
firefox
![image](https://github.com/gruhn/vue-qrcode-reader/assets/55469851/d0b14ce8-42f8-4687-8836-c39e6a8a8933)

chrome
![image](https://github.com/gruhn/vue-qrcode-reader/assets/55469851/70ec3b96-8e05-4fd5-92ca-51d5aac930ca)

Is there a workaround to use a local wasm file or some other solution? Thanks in advance, the component is really awesome

**Comment by gruhn** [comment]
Hi, there is a workaround. See #354

**Comment by Leo-Felde** [comment]
> Hi, there is a workaround. See #354

Hey, thanks for quick answer
I've tried using setZXingModuleOverrides like in the isse you've sent me and I get this weird error I can't make sense of

![image](https://github.com/gruhn/vue-qrcode-reader/assets/55469851/ab2d5701-b2be-4bcf-9193-f8fa6d04bbc7)

**Comment by Leo-Felde** [comment]
I fixed it by instead of importing the .wasm like in the example, I just returned it's name and it worked

![image](https://github.com/gruhn/vue-qrcode-reader/assets/55469851/8174a8d8-b4ed-4c63-80bb-99c8ebfbdffe)

Thanks for the help

**Comment by baixjian** [comment]
> 我修复了这个问题，没有像示例中那样导入 .wasm，而是返回了它的名字，这样就成功了



> I fixed it by instead of importing the .wasm like in the example, I just returned it's name and it worked
> 
> ![image](https://private-user-images.githubusercontent.com/55469851/347191762-8174a8d8-b4ed-4c63-80bb-99c8ebfbdffe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MzQ3NDAsIm5iZiI6MTcyNDkzNDQ0MCwicGF0aCI6Ii81NTQ2OTg1MS8zNDcxOTE3NjItODE3NGE4ZDgtYjRlZC00YzYzLTgwYmItOTljOGViZmJkZmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEyMjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzODY1Nzg4NGIxY2I2ZTg4NTM4ZDgzZmUwMGU2YTVlNmFiOGZiOTg2NDNhYTU2ZDc1N2JhN2FiNmI2YzVjMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vBJI9A2q7afKsHAk35zKkkp3t-7qMZbHawkw5z0dsVo)
> 
> Thanks for the help

Just return the name and automatically find the wasm file as you posted the code？

**Comment by Leo-Felde** [comment]
> > 我修复了这个问题，没有像示例中那样导入 .wasm，而是返回了它的名字，这样就成功了
> 
> > I fixed it by instead of importing the .wasm like in the example, I just returned it's name and it worked
> > ![image](https://private-user-images.githubusercontent.com/55469851/347191762-8174a8d8-b4ed-4c63-80bb-99c8ebfbdffe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MzQ3NDAsIm5iZiI6MTcyNDkzNDQ0MCwicGF0aCI6Ii81NTQ2OTg1MS8zNDcxOTE3NjItODE3NGE4ZDgtYjRlZC00YzYzLTgwYmItOTljOGViZmJkZmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEyMjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzODY1Nzg4NGIxY2I2ZTg4NTM4ZDgzZmUwMGU2YTVlNmFiOGZiOTg2NDNhYTU2ZDc1N2JhN2FiNmI2YzVjMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vBJI9A2q7afKsHAk35zKkkp3t-7qMZbHawkw5z0dsVo)
> > Thanks for the help
> 
> Just return the name and automatically find the wasm file as you posted the code？

In my case yes, I think it might have happened because I was using webpack. In the [workaround](https://github.com/gruhn/vue-qrcode-reader/issues/354) gruhn provided they used the relative path if I'm not mistaken, you might want to try both and see if it works

**Comment by luogu** [comment]
> 我修复了这个问题，而不是像示例中那样导入 .wasm，我只是返回了它的名称，它就起作用了
> 
> ![image](https://github.com/gruhn/vue-qrcode-reader/assets/55469851/8174a8d8-b4ed-4c63-80bb-99c8ebfbdffe)
> 
> 谢谢你的帮助

Which file and code did you modify, or did you add a new code segment? Can you tell me in more detail? Thank you

**Comment by Leo-Felde** [comment]
> > 我修复了这个问题，而不是像示例中那样导入 .wasm，我只是返回了它的名称，它就起作用了
> > ![image](https://github.com/gruhn/vue-qrcode-reader/assets/55469851/8174a8d8-b4ed-4c63-80bb-99c8ebfbdffe)
> > 谢谢你的帮助
> 
> Which file and code did you modify, or did you add a new code segment? Can you tell me in more detail? Thank you

it was in the onMounted of my qr code reader component:

![Image](https://github.com/user-attachments/assets/9fed63ac-8354-493c-b3d7-d853c214a844)
