### ISSUE TITLE
Can you support uploading images and scanning barcodes?

### ISSUE THREAD

**Issue by duandao1950** [gruhn/vue-qrcode-reader#443]
RT

**Comment by gruhn** [comment]
It is supported. If you have any issues, please provide more details.

**Comment by duandao1950** [comment]
Please provide me with a file upload use case

**Comment by duandao1950** [comment]
1. Scan the barcode of the image using vue qrcode reader.

2. Upload an image with a barcode inside.

3. Scan the barcode in the uploaded image and identify it.

**Comment by gruhn** [comment]
https://gruhn.github.io/vue-qrcode-reader/demos/Upload.html
