### ISSUE TITLE
Option to use native Barcode Detection API

### ISSUE THREAD

**Issue by pastc** [gruhn/vue-qrcode-reader#446]
Will there be an option to use the native [Barcode Detection API](https://developer.mozilla.org/en-US/docs/Web/API/Barcode_Detection_API) instead of the wasm polyfill?

I would prefer it since it is more performant since it uses the os instead of just the browser.

**Comment by gruhn** [comment]
That used to be the default behavior. But then I noticed that (at least) Safari on macOS did not implement the API correctly. The `detect` function would not accept `Blob` inputs which is needed for `QrcodeCapture` and `QrcodeDropZone`. This was a while ago though, so this might have changed. Feel free to open a PR :)

**Comment by pastc** [comment]
Please see #447
