### ISSUE TITLE
BarcodeDetector not work in some of the application's built-in browser

### ISSUE THREAD

**Issue by wosiwq** [gruhn/vue-qrcode-reader#450]
**Describe the bug**
I'm running into a problem where some of the application's built-in browser, they have window.BarcodeDetector objects, but window.BarcodeDetector.getSupportedFormats() returns []

**Smartphone (please complete the following information):**
- Device: Realme GT Neo5
- OS: Android 14
- APP : Alipay

**Minimal Reproduction**
![image](https://github.com/user-attachments/assets/c911733c-d489-4b01-b890-4cfc1191a532)

**Screenshots**
- Chrome
![image](https://github.com/user-attachments/assets/0a5a7465-e0b6-4d65-a51e-90efb8b70f1d)
- Alipay
![image](https://github.com/user-attachments/assets/b942c5fb-b56b-48d9-8de9-189cf6d40d45)

**Comment by gruhn** [comment]
Ok that’s annoying. In the last release we stopped using the `BarcodeDetector` polyfill, if the browser natively supports it. Presumably, if you downgrade to [v5.5.7](https://github.com/gruhn/vue-qrcode-reader/releases/tag/v5.5.7) the problem goes away, right?

**Comment by wosiwq** [comment]
Yes, when I downgraded to [v5.5.7](https://github.com/gruhn/vue-qrcode-reader/releases/tag/v5.5.7) it worked fine!

If possible, I'd prefer it to determine if the user's browser supports the appropriate format, so that the native BarcodeDetector can be used if the user's browser does.
