### ISSUE TITLE
QrCodeDropZone format not working

### ISSUE THREAD

**Issue by cahVectorsoft** [gruhn/vue-qrcode-reader#453]
The issue is that in Capture uploading ean_13 files for example is totally fine, while in DropZone it is not working at all. This is because in https://github.com/gruhn/vue-qrcode-reader/blob/master/src/components/QrcodeDropZone.vue you did not pass the props.format to the processFile function.

should be like this
```
droppedFiles.forEach((file: File) => {
    onDetect(processFile(file), props.formats)
  })
```

Could you fix this? Thanks a lot!

**Comment by gruhn** [comment]
Ah yes, good catch 👍

**Comment by cahVectorsoft** [comment]
Thank you very! That was quick, I did not expect that :D
