### ISSUE TITLE
Can't detect QR code #851

### ISSUE THREAD

**Issue by VietHoang24** [gruhn/vue-qrcode-reader#456]
**Describe the bug**
I have been using a library to scan QR codes, but currently, the library cannot recognize my QR code, even though it was working fine before. After checking, I discovered that after starting the camera, the library tries to connect to the API but encounters an error. As a result, the QR code cannot be detected.

**To Reproduce**
Open camera and detect qr code 
```
curl 'https://fastly.jsdelivr.net/npm/zxing-wasm@1.1.3/dist/reader/zxing_reader.wasm' \
  -H 'sec-ch-ua: "Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"' \
  -H 'Referer: https://app.qa2024stg.upft.jp/' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --compressed
```
**Screenshots**

![image](https://github.com/user-attachments/assets/c3913ee0-ad51-43b9-b5c9-00352e05eb39)

**Comment by GuoConglie** [comment]
import wasmFile from "../../node_modules/zxing-wasm/dist/reader/zxing_reader.wasm?url";

setZXingModuleOverrides({
    locateFile: (path: string, prefix: any) => {
        const match = path.match(/_(.+?)\.wasm$/);
        if (match) {
            return wasmFile;
        }
        return prefix + path;
    },
});

try it!

**Comment by gruhn** [comment]
Background: #354

**Comment by VietHoang24** [comment]
I have checked it again, issue has been fixed, thank team alot !
