### ISSUE TITLE
Hello! 👋  I ported this to Svelte 5 🫡 

### ISSUE THREAD

**Issue by ollema** [gruhn/vue-qrcode-reader#458]
Hello!

To start off, this is actually not the first time I have ported this package. A year ago or so, I created [svelte-barcode-scanner](https://github.com/ollema/svelte-barcode-scanner/blob/main/src/lib/barcode-scanner.svelte) which draw a lot if inspiration from this package but I thought that I required a totally different API that focused more on total control of the detections to be able to implement debouncing as well as having multiple user definable region of interests (ROIs) to extract different parts of the image that based on anchor boxes.

This worked well for the Svelte 4 application I was building. When I started to migrate to Svelte 5 I had some time to rethink everything and I think I underestimated what you can do with the API you have designed for the `vue-qrcode-reader` (for example you can (ab)use the `track` function for debouncing purposes even though only one detection event is sent).

Therefore I decided to try and port this package and more of a 1:1 mapping of your API to Svelte.

It turned out to work pretty well I think!

Here is the repo:
https://github.com/ollema/svelte-qrcode-reader

and I also quickly ported the website and the demos (the API reference was not ported):
https://ollema.github.io/svelte-qrcode-reader/
just to make sure that everything works similar to how it works in this package (I think's very similar already!)

> Note: this website looks like crap - I did not focus on the design at all. In fact I just wrote HTML and then I used [PicoCSS](https://picocss.com/) with little to no custom CSS at all. This is not representative of what I have in mind for when I publish the package.

In this port a lot of stuff is _heavily inspired_ from your package. Of course the components are pretty different since it's Vue vs. Svelte but the supporting functions is almost exactly the same.

Now, I know that you have licensed this repo and your work with a permissive license (MIT), but I figured it is much nicer to ask you:

1. Would you be OK if I published (a more refined version) of this port as `svelte-qrcode-reader`?

2. If so, is it OK if I attribute you and your package in the `README.md` or would you rather be left out so to speak?

Thanks in advance, and do not hesitate to reply if you have any questions or concerns.

Best regards,

Olle

**Comment by gruhn** [comment]
Very cool :+1: I'll create a link in the README as well.

**Comment by ollema** [comment]
oh nice, it’s not fully ready for primetime yet but that would give me a reason to make it more production ready for sure.

I take it I have your blessing to use the sinilar name then? 🙂

**Comment by gruhn** [comment]
of course 🙂

**Comment by gruhn** [comment]
In fact, the name is a bit of a misnomer now that all kinds of barcode formats are supported.

**Comment by ollema** [comment]
yeah I figured that as well, hence why I went with svelte-barcode-scanner last time. but the same time your project is already well established so there is probably nothing to gain by changing it?

anyways, thanks a lot! will close this issue
