### ISSUE TITLE
Access camera picture

### ISSUE THREAD

**Issue by 1am** [gruhn/vue-qrcode-reader#46]
Hello

Is it somehow possible to access raw image from the camera using vue-qrcode-reader? I saw that jsQR allows that so my question is is the functionality somehow exposed by this library?

What I want to achieve is to have a snapshot of the whole frame at the moment when a code was decoded but not sure how to get there

**Comment by gruhn** [comment]
Not at the moment. Can you further explain your use case?

**Comment by 1am** [comment]
Hi. My use case is that I'm scanning codes on a electronics circuit board so at the same time if I'd make and save a picture and have a possibility to later detect some deriviations from their normal look.
Right now what i did is whenever a QR code is detected I'm printing thermal labels (done on localhost server side) so storing the image data would not be much burden to add in such setup.

**Comment by 1am** [comment]
Hi. 

You're right, maybe I've gone into too much detail. What I need is to send the camera image to server side for postprocessing. Maybe I could access the camera preview element from normal JS from onDetect method as in https://github.com/gruhn/vue-qrcode-reader#paused-prop ? 
The rest (printing, server, etc) I've got already covered, just missing the raw bitmap data of camera element. Never worked with this before so it's a bit uncharted territory stil :)

To clarify on what I've meant in 'derivation from their normal look' - I meant the boards which have normal QR code stickers on them.

**Comment by gruhn** [comment]
Ok thanks for clarifying this :+1: 

I'm planning to add a new event anyway. It would be similar to `decode` but communicates more details. This should also enable features like scanning images via drag-and-drop.

**Comment by gruhn** [comment]
Sorry, it took a while. Checkout the new `detect` event. It exposes image data of scanned frames.
