### ISSUE TITLE
Rescanning issue

### ISSUE THREAD

**Issue by jamesdo** [gruhn/vue-qrcode-reader#47]
I have some an app that requires certain QR codes to be scanned more than once in a row, if there were a way to set a _reset time_ of sorts so that a QR code could be rescanned after 5 seconds (or any time for that matter).

**Comment by gruhn** [comment]
You can reset the internal state by pausing the component (`:paused="true"`). After unpausing you should be able to scan the previous QR code again.

**Comment by ksheurs** [comment]
Hi @gruhn .. we are setting `this.paused = true` + `this.paused = false` in a `setTimeout`, but it seems we are still unable to rescan the same QR code. Is there another step we are missing? Thanks.

**Comment by gruhn** [comment]
@ksheurs sorry for the long wait. I was on vacation.

Checkout the validation demo and it's source code. Does that work for you?
