### ISSUE TITLE
iOS 11 Safari does not init video

### ISSUE THREAD

**Issue by gofka** [gruhn/vue-qrcode-reader#48]
Seems like the video can not initialise in latest mobile Safari.
`init` event says `'NotAllowedError'`

I've tried to use solution from [this webrtc issue](https://github.com/webrtc/samples/issues/929):
```
mounted() {
    let videoEl = document.getElementsByTagName('video')[0];
    videoEl.setAttribute('autoplay', true);
    videoEl.setAttribute('playsinline', true);
    videoEl.setAttribute('controls', true);
},
```
But no success.

**Comment by gruhn** [comment]
`'NotAllowedError'` usually indicates that the user denied camera access permission. Are you sure you haven't [disabled camera access](https://www.igeeksblog.com/how-to-stop-safari-accessing-iphone-camera-microphone-in-ios-11/)?

**Comment by gofka** [comment]
Yes. Camera access enabled in settings.

**Comment by gruhn** [comment]
does [this](https://webrtc.github.io/samples/src/content/getusermedia/canvas/) work on your device?

**Comment by gofka** [comment]
Yes, it works...
But it doesn't work in my single file component:

```
<template>
    <div class="scan">
        <qrcode-reader @decode="onDecode" :paused="paused"></qrcode-reader>
    </div>
</template>

<script>
    import {QrcodeReader}  from 'vue-qrcode-reader';

    export default {
        data() {
            return {
                paused : false
            }
        },
        components : {
            QrcodeReader
        },
        methods    : {
            onDecode(content) {
                this.paused = true;
                console.log(content);
            }
        }
    }
</script>
```

**Comment by gruhn** [comment]
Hmmm... what about the demo page. Does that work?

**Comment by gofka** [comment]
Yes, demo page works fine.
And my code above works fine everywhere except Safari iOS 11. On iOS it doesn't asks for camera permissions. Tested on different devices.

**Comment by gruhn** [comment]
Hmm... weird, your code looks fine to me. Maybe there is something with your environment somehow :man_shrugging: you could try to clone the demo page and run it locally and see if that works. Checkout [CONTRIBUTING.md](https://github.com/gruhn/vue-qrcode-reader/blob/master/CONTRIBUTING.md) for instructions.

**Comment by gruhn** [comment]
Oh wait! Checkout [this](https://stackoverflow.com/questions/44523609/getusermedia-is-not-allowed-in-localhost-safari-11).

**Comment by gofka** [comment]
I've tested my app on **Https** and everything is fine now. Thanks @gruhn  !

**Comment by gruhn** [comment]
Updated browser support section in README
