### ISSUE TITLE
This works with barcode??

### ISSUE THREAD

**Issue by anamarquezz** [gruhn/vue-qrcode-reader#49]
Hi, I like this, but i tried to scan a bar code, and is not happen nothing,
so my question is,
This works with barcode??

**Comment by gruhn** [comment]
nope, this component uses  [jsQR](https://github.com/cozmo/jsQR) under the hood which is not able to process barcodes.

**Comment by lxc455735702** [comment]
In fact, barcodes still have certain usage scenarios.
i hope this works with barcode

**Comment by stuta** [comment]
I have found in my C language tests that: 
* quirc is by far the fastest, but sometimes need (fast) image manipulation to work
* zxing works well with QR Code, but does not recognize so well Code 128 (and maybe other 1D barcodes)
* zbar is by far the best with 1D barcodes but not so good with QR Code

Different backends would be really good.

**Comment by gruhn** [comment]
See #109 and #114 

Sorry, I'm very busy so there hasn't been much progress yet.

**Comment by gruhn** [comment]
Just merged the experimental `worker` prop. Check the discussion at #109
