### ISSUE TITLE
Bebel problem

### ISSUE THREAD

**Issue by fortael** [gruhn/vue-qrcode-reader#5]
I don't know what the magical polifyll do you use, but i got error out of the box. 

`Uncaught ReferenceError: regeneratorRuntime is not defined`

I took code from demo and seems init method does not work. I don't see any text in row. So i see my face about 30 minutes and no reaction on any qr code.

I set `babel` language to fix error
`<script lang="babel">`

But it seems like I'm doing something wrong.

**Comment by gruhn** [comment]
Have you cloned the demo repository or did you just copy the code? If you copied the code, I think you have to install babels [transform-runtime](https://babeljs.io/docs/plugins/transform-runtime/#installation).

**Comment by fortael** [comment]
`<qrcode-reader
                :paused="paused"
                @decode="onDecode"
                @locate="onLocate"
                @init="(test)=> {console.log(test)} ">

            <div class="point" v-for="point in points" :style="positionOf(point)"></div>
            <div class="content">{{ content }}</div>
            <div class="controls">
                <button type="button" class="btn btn-primary btn-sm" @click="togglePauseOnCapture">
                    {{ pauseOnCapture ? 'Scan Continuously' : 'Pause On Capture' }}
                </button>
            </div>

        </qrcode-reader>`

Even like this i don't have any error or "test" word in console. I have no idea. I use laravel-mix. So problem is somewhere in webpack I guess.

**Comment by gruhn** [comment]
no problem :wink:
