### ISSUE TITLE
Undefined VERSION on every update

### ISSUE THREAD

**Issue by brunonavarrete** [gruhn/vue-qrcode-reader#52]
I'm using the plugin successfully in every aspect except that it seems to look for a VERSION variable that is undefined everytime I update npm. I've located and modified (against explicit orders) the following code on src/index.js

    // Plugin
    const plugin = {
      /* eslint-disable no-undef */
      version: VERSION,
      install,
    }

Still, on every update I have to change the VERSION for an integer (1). Any suggestions?

**Comment by gruhn** [comment]
Thanks for reporting. I don't know why I haven't encountered this before. This seems to be an artifact from the [vue-cli template I originally used to scaffold this project](https://github.com/Akryum/vue-share-components/blob/dev/template/src/index.js#L21). I don't know where this `VERION` variable was intended to come from :man_shrugging: but I want to use vue-cli 3 for upcoming releases anyway (#51) so I'll just remove this.

**Comment by brunonavarrete** [comment]
Great. If it helps, I've been using Laravel 5.6 which in turn uses Webpack 1.13.1 to handle scss and js.
