### ISSUE TITLE
Cant resolve '@/mixins/InitHandler'

### ISSUE THREAD

**Issue by elviskudo** [gruhn/vue-qrcode-reader#54]
hi,
thanks for your great component

but i found error
cant resolve '@/mixins/InitHandler'
how can i fix it?

thanks

**Comment by gruhn** [comment]
you copied one of the demo components right? 

Each demo component has the same `init` handler and I'm too lazy to maintain this redundancy so it's outsourced in a mixin called [InitHandler](https://github.com/gruhn/vue-qrcode-reader/tree/gh-pages/dev/src/mixins). Either include that file or copy all its contents into your component.

**Comment by elviskudo** [comment]
thanks, solved now
