### ISSUE TITLE
why box out of qr code

### ISSUE THREAD

**Issue by elviskudo** [gruhn/vue-qrcode-reader#55]
hi,

i wanna ask more
i already implement this component, but red box, far away from qr code in camera
how to solved it?

**Comment by gruhn** [comment]
in your implementation or the demo page? I introduced this issue recently on the demo page, I'll fix it soon. The version you can pull from NPM should be fine though, isn't it?

**Comment by elviskudo** [comment]
yes,
i implementation on my project, i copied code from your demo
thanks btw for your fix later

**Comment by gruhn** [comment]
hmm, can you try to re-install the package:

```bash
yarn add vue-qrcode-reader
# OR
npm install --save vue-qrcode-reader
````

**Comment by elviskudo** [comment]
![screen shot 2018-08-29 at 21 03 04](https://user-images.githubusercontent.com/1689090/44792934-3cb6e800-abcf-11e8-8eed-6f592d0b1eb5.png)

i just re install the package, but red box still far away from qr code
thanks btw

**Comment by gruhn** [comment]
can you share your implementation, including CSS?

**Comment by elviskudo** [comment]
```
<template>
	<div class="qr-code">
		<h1>QR Code</h1>
		<QrcodeReader
			@decode="onDecode"
			@init="onInit">
			<div class="decoded-content">{{ content }}</div>

			<LoadingIndicator v-show="loading" />
		</QrcodeReader>
	</div>
</template>

<script>
import { QrcodeReader } from 'vue-qrcode-reader'
import InitHandler from '@/mixins/InitHandler'

export default {
	components: { QrcodeReader },
	mixins: [ InitHandler ],
	data: () => ({
		content: null
	}),
	methods: {
		onDecode (decodedString) {
			console.log(decodedString)
			this.content = decodedString
		}
	}
}
</script>
```

**Comment by gruhn** [comment]
ok, I dont know... [this demo works on my device](https://jsfiddle.net/eywraw8t/318809/). Is it working for you too?

**Comment by elviskudo** [comment]
maybe i have to change the style code
which code to change the red box position?

**Comment by gruhn** [comment]
the position is not determined by CSS. It's painted to a canvas (see [`track` prop](https://github.com/gruhn/vue-qrcode-reader#track-prop)). It's important though that this [canvas and the underlying video element](https://github.com/gruhn/vue-qrcode-reader/blob/master/src/components/QrcodeReader.vue#L14-L22) have the same size so the coordinates of the red box are calculated correctly.

**Comment by edhead990** [comment]
Was having the same issue. The x position of the tracking layer seems to start at the halfway point of the video element. I found that adding a left value to the `.qrcode-reader__overlay, .qrcode-reader__tracking-layer` CSS definition fixed it for me:
```
.qrcode-reader__overlay, .qrcode-reader__tracking-layer {
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
}
```
(added `top: 0;` for good measure too)

**Comment by gruhn** [comment]
thanks @edhead990. I'm not able to reproduce this so I assume that does the trick.
