### ISSUE TITLE
Would it be possible/useful to fallback to single photo capture?

### ISSUE THREAD

**Issue by avishayp** [gruhn/vue-qrcode-reader#56]
First thanks for this fantastic project!
For chrome on ios users - would it be possible to replace https://github.com/gruhn/vue-qrcode-reader/blob/b8161f1079ec63399eafc49470a5c91133835bc4/src/misc/camera.js#L41 with a fallback to the "take photo or upload from library" dialogue?

**Comment by gruhn** [comment]
Cool idea! Until now I didn't know you could you could do

```html
 <input type="file" accept="image/*" capture="camera">
```

I'm not sure how to implement this though. I want to make sure, we don't just show a button you can click on. I want to keep the component layout agnostic or at least super flexible.

I'm also not sure if we should completely stop throwing that error there. Maybe only in some cases or maybe let the parent component decide (based on the error) whether to fall back or do something else.

It seems `capture` is only supported in mobile browsers so there should still be an error for desktop browsers that don't support WebRTC.

**Comment by avishayp** [comment]
My naive thought was to replace the `stream` with an annoying pseudostream that prompts the user to take photos. The downsides are fairly obvious:

 * The "standard" way to do this seems to imply injecting DOM element
 * Said standard way prompts user with a dialog + buttons, and "upload from photo library" is irrelevant
 * Interwebs say chrome on ios usage is ~4%, so why bother

I'm also not sure how/if to correctly implement this.

**Comment by avishayp** [comment]
The use case I have is a webapp where scanning QR code is part of some user flow. User does single successful scan, then moves on. 
For such use case, having an "upload file" button overlapping canvas in `QrcodeReader.vue`, and only visible in case `getUserMedia()` is not supported, would be great. It'll be like https://webqr.com/, only way better.
