### ISSUE TITLE
Unable to read QR code

### ISSUE THREAD

**Issue by iracic** [gruhn/vue-qrcode-reader#59]
Hi,
I am trying demo page here on my phone.
QR code used is one that is immediately scanned by native Android applications (I have tried 4-5 different Android applications, all worked without any problem).
Here, tried to test it on demo page and I am unable to get QR scanned. 
Am I missing something obvious or maybe there is problem with phone used for test (Huawei CAN-L11, Android 7.0 ) ?
On some other HTML demos, on Internet, QR codes are read but was very slow, ex: 10-20 seconds), or also didn't work.
Is this something known?
Which QR code you use for tests?

Also I have tried using laptop and also QR kod was not recognized. As in the case with the phone, camera is activated, grant given to access it, QR is visible by camera, as shown on the page. Still, QR code is not recognized.

Thank you,
Igor

**Comment by gruhn** [comment]
I mostly just [google qrcode](https://www.google.de/search?q=qrcode&tbm=isch&source=lnms&sa=X&ved=0ahUKEwjIj6unnqTdAhUHDCwKHcVLB9EQ_AUIDCgD&biw=1680&bih=850&dpr=1) and try to scan the search results. There shouldn't be a problem with special kinds of QR codes. Anyway, can you post the one you used?

* Which browser are you using? 
* When you are on your Laptop, have you tired dragging & dropping QR code image files?

Scanning on mobile can be pretty slow. I'm trying hard to improve this.

**Comment by rajagopalx** [comment]
I too faced some QR codes are get scanned. The issue is with jsqr library.  https://github.com/cozmo/jsQR/issues/89

**Comment by iracic** [comment]
Just tried more examples on google qrcode, many codes pass ok, there is shopify QR that is not recognized, 
https://cdn.shopify.com/growth-tools-assets/qr-code/shopify-faae7065b7b351d28495b345ed76096c03de28bac346deb1e85db632862fd0e4.png (true is that even native apps are slower on this one)
Drag and drop for png and svg worked OK on laptop. Doing imperfect photos (jpg) of example that works is not always recognized (slight angle, window reflection) - if you take from google code photo (I can send if you prefer)

Browser is Chromium (69 on laptop, also chrome on phone)

**Comment by gruhn** [comment]
@iracic oh yeah right. QR codes without at least a little bit of white border are not really recognized. The scanner also gets confused when there are multiple QR codes in view.

**Comment by iracic** [comment]
Ok. We can consider it as current implementation limitation and close the thread. Agree ?

**Comment by gruhn** [comment]
I guess so :/

**Comment by saikrishna15** [comment]
will this be implemented, Im unable to read few qr codes, but can read most.
