### ISSUE TITLE
force use of rear camera

### ISSUE THREAD

**Issue by plakhin** [gruhn/vue-qrcode-reader#6]
I'm using Google Chrome on Android 7.0. On some devices like Samsung Galaxy S/A series vue-qrcode-reader uses rear camera and on some devices like Xiaomi Redmi Note 4 it uses front camera. How can I force it to use rear camera?

**Comment by gruhn** [comment]
This shoud actually be the default behavior. Can you install the pull request I made via
```
npm install --save git+https://github.com/gruhn/vue-qrcode-reader.git#force-rear-camera 
```
and check if it works now?

**Comment by plakhin** [comment]
Thank you for response!
I'll be able to check on Xiaomi device in 2 days and will post a reply right after that.
Also I didn't install `webrtc-adapter` so will try it too! Thanks!

**Comment by plakhin** [comment]
Just tested on Xiaomi Redmi Note 4. I've installed webrtc-adapter and "force-rear-camera" PR, but nothing helped :(

**Comment by plakhin** [comment]
I've tried https://simpl.info/getusermedia/sources/ and I can select rear camera on Xiaomi and it works fine on that page, but vue-qrcode-reader still uses front camera.

**Comment by gruhn** [comment]
When you open the demo I linked in the README on your device, is the front camera selected as well?

Please open [this page](http://jsbin.com/nocutacota/1/edit?console) on your device and paste the console output here.

**Comment by plakhin** [comment]
Just tested on another Redmi Note 4 - absolutely the same.
Here is console output:
```json
[[object MediaDeviceInfo] {
  deviceId: "default",
  groupId: "f934df663ada25b9a7e737c723f5d5abdb42df795b8fa29ac1943bd8facb12f5",
  kind: "audioinput",
  label: "",
  toJSON: function toJSON() { [native code] }
}, [object MediaDeviceInfo] {
  deviceId: "739711fca720527edf844216059e285bfe3f7e65c670d48925e606b655a15b00",
  groupId: "",
  kind: "videoinput",
  label: "",
  toJSON: function toJSON() { [native code] }
}, [object MediaDeviceInfo] {
  deviceId: "327d9d32615f14ae2de71bd3252b6d37fa7a6e25d63b9d1f2b563331c7d3ef17",
  groupId: "",
  kind: "videoinput",
  label: "",
  toJSON: function toJSON() { [native code] }
}, [object MediaDeviceInfo] {
  deviceId: "default",
  groupId: "default",
  kind: "audiooutput",
  label: "",
  toJSON: function toJSON() { [native code] }
}]
```

![image](https://user-images.githubusercontent.com/25561058/33168537-770ce31e-d06b-11e7-90ae-f5037b919827.png)

**Comment by plakhin** [comment]
Here is the output from Samsung Galaxy S6 Edge which opens rear camera by default:
```
[[object MediaDeviceInfo] {
  deviceId: "default",
  groupId: "9eea2711f056de1db5ca15860b2292ef98b64b5833b24538c7341b2f1b487d5e",
  kind: "audioinput",
  label: "",
  toJSON: function toJSON() { [native code] }
}, [object MediaDeviceInfo] {
  deviceId: "6917a1ac049abf21a5b7d9d7406fc5abf7be6ee52c6b591975f36472d2b81177",
  groupId: "c3ca07767a639a38db3636b15d01d67c7940db5a8a4804135e8ecc84451a77ab",
  kind: "audioinput",
  label: "",
  toJSON: function toJSON() { [native code] }
}, [object MediaDeviceInfo] {
  deviceId: "7d166f2f670a89a9ecb2bc004d4188136058e672ef3a49e570ffc0d0367bb033",
  groupId: "52a59250b09b7e9d4f33f374f9119fe87b92509ba3c0b4c2783e2b966d9c9e3d",
  kind: "audioinput",
  label: "",
  toJSON: function toJSON() { [native code] }
}, [object MediaDeviceInfo] {
  deviceId: "8dea89f225d60abe2e366ea65d4f9ba937eafbf94b3bbb984d2853f10c710c0e",
  groupId: "",
  kind: "videoinput",
  label: "",
  toJSON: function toJSON() { [native code] }
}, [object MediaDeviceInfo] {
  deviceId: "6917a1ac049abf21a5b7d9d7406fc5abf7be6ee52c6b591975f36472d2b81177",
  groupId: "",
  kind: "videoinput",
  label: "",
  toJSON: function toJSON() { [native code] }
}, [object MediaDeviceInfo] {
  deviceId: "default",
  groupId: "default",
  kind: "audiooutput",
  label: "",
  toJSON: function toJSON() { [native code] }
}]
```

**Comment by gruhn** [comment]
Thanks :+1:

Have you tried opening the demo page on those devices? 

And can you also open the page you linked here on all devices and tell me the order in which the cameras are listed in the drop down element? For example like this:
```
Galaxy S6 Edge:
1. front camera
2. rear camera
```

**Comment by plakhin** [comment]
> Have you tried opening the demo page on those devices?

Yes, S6 Edge uses rear, Redmi Note 4 uses front.

>And can you also open the page you linked here on all devices and tell me the order in which the cameras are listed in the drop down element? For example like this:

```
For S6 Edge and Xiaomi Redmi Note 4 (absolutely the same):
1. camera 1
2. camera 2
````
camera 1 = front, camera 2 = rear

**Comment by plakhin** [comment]
Whoops, cleaned browser cache and now I see different picture, will provide all info in 10 minutes

**Comment by gruhn** [comment]
I should also mention that you have to `import 'webrtc-adapter'` somewhere in your project

**Comment by plakhin** [comment]
https://simpl.info/getusermedia/sources 

```
S6 Edge:
camera2 1, facing front
camera2 0, facing back

Redmi Note 4:
camera 1, facing front
camera 2, facing back
```

Demo page now uses rear camera on both devices.
My app with webrtc-adapter and pull request installed uses rear camera on both devices.
Will test on another Xiaomi Redmi Note 4 a bit later today.

**Comment by plakhin** [comment]
> I should also mention that you have to import 'webrtc-adapter' somewhere in your project

Just import?

**Comment by gruhn** [comment]
Yeah just import... This package pollutes your global scope, no need for assign it a variable. I think I'll include this by default in the next release

**Comment by plakhin** [comment]
I've tested with imported webrtc-adapter and installed #7 on 2 Xiaomi devices - now they use rear camera. Great! I think it's time to accept pull release and as I understand, starting from 0.6.4, there is no more need to install and/or import webrtc-adapter cause it is already included out of the box.

**Comment by gruhn** [comment]
Cool :grin: and yeah webrtc-adapter is now included

**Comment by plakhin** [comment]
Will be waiting next release. Thanks!

**Comment by plakhin** [comment]
When do you plan to release changes introduced in #7?

**Comment by gruhn** [comment]
I don't. I had the impression this wasn't part of your problems solution. Isn't the current version working for you?

**Comment by plakhin** [comment]
I'm still on git+https://github.com/gruhn/vue-qrcode-reader.git#force-rear-camera version and has no ability to check cause it's already in production.

**Comment by gruhn** [comment]
Not sure if I understand your problem but you can just run `yarn add vue-qrcode-reader`. This will automatically remove the GitHub reference and install the latest version from NPM.

**Comment by plakhin** [comment]
Yes, I know how to upgrade. What I meant is that app is already in production and I can't take Xiaomi device to test again after updating from PR version to 0.6.4 and I'm afraid it will use front camera again after upgrade since PR was not merged.

**Comment by gruhn** [comment]
I see... I don't think I'll make a difference but I'll include it in the next release.

**Comment by gruhn** [comment]
done

**Comment by plakhin** [comment]
Great! Thank you!
