### ISSUE TITLE
[Feature Request]  Beep Sound after scanning

### ISSUE THREAD

**Issue by rajagopalx** [gruhn/vue-qrcode-reader#60]
It is good to have out of the box options like beep sound, vibration after scanning.

**Comment by rajagopalx** [comment]
Thanks. I am happy to try demos for these features.  Once it's ready I will definitely share it here.

**Comment by defji** [comment]
simply just put into onDecode, like this

            onDecode(result) {
                window.events.$emit('qr-decoded', {result: result});
                var audio = new Audio("/sounds/qr_beep.mp3");
                audio.play();

            },

**Comment by gruhn** [comment]
Simple enough, I think we can close this
