### ISSUE TITLE
Choose file

### ISSUE THREAD

**Issue by dakshshah96** [gruhn/vue-qrcode-reader#63]
Thank you for this library and your continued support 🎉 

On devices where `navigator.getUserMedia` is not supported such as non-Safari browsers and installed PWAs on iOS, I want to fallback to giving users the option to upload a picture of the QR code.

I've gotten drag-and-drop to work properly but for mobile devices drag-and-drop wouldn't make sense so how do I display a 'Choose file' button and decode a QR code from the uploaded image using this library?

**Comment by gruhn** [comment]
Duplicate of #56
