### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by kicaal** [gruhn/vue-qrcode-reader#66]
How I can do ZOOM camera with this component?

**Comment by gruhn** [comment]
Do you want your users to be able to zoom in response to touch gestures? Or do you want a prop to configure a fixed zoom level? 

Both is not possible yet. I mean you could implement this yourself by scaling the component up and cutting off the overlay. That wouldn't improve scanning performance though. 

Why exactly do you want this feature?

**Comment by kicaal** [comment]
I want set zoom in the camera if my qr is far

**Comment by gruhn** [comment]
Ok but I'm pretty sure that zooming won't actually improve accuracy. So it doesn't matter if you scan QR codes zoomed in or not. If the QR code is too far away to be recognized it just can't be scanned. What do you think?

**Comment by debapriya1990** [comment]
@kicaal you can do it like the below example-
JavaScript Snippet:
`
navigator.mediaDevices.getUserMedia({video: { zoom: true }})
.then(mediaStream => {
  document.querySelector('video').srcObject = mediaStream;

  const [track] = mediaStream.getVideoTracks();
  const capabilities = track.getCapabilities();
  const settings = track.getSettings();

  const input = document.querySelector('input[type="range"]');

  // Check whether zoom is supported or not.
  if (!('zoom' in settings)) {
    return Promise.reject('Zoom is not supported by ' + track.label);
  }

  // Map zoom to a slider element.
  input.min = capabilities.zoom.min;
  input.max = capabilities.zoom.max;
  input.step = capabilities.zoom.step;
  input.value = settings.zoom;
  input.oninput = function(event) {
    track.applyConstraints({advanced: [ {zoom: event.target.value} ]});
  }
  input.hidden = false;
})
.catch(error => ChromeSamples.log('Argh!', error.name || error));
`

**Comment by dheimoz** [comment]
hey @debo900 thanks for sharing the snippet.
