### ISSUE TITLE
When Vue rerenders the component, Firefox ask permissions again

### ISSUE THREAD

**Issue by qnp** [gruhn/vue-qrcode-reader#69]
Greetings,
When the component is rerendered, Firefox asks again for camera permissions. It is really breaking user experience. Indeed, the rerender is triggered by Vue when for example a child component (present in the <qrcode-reader> slot) changes **or even when `paused` prop changes**.
See a live example https://codesandbox.io/s/v6qrmr7wll
In file `src/components/MyQrReader.vue`, i have some very simple logic in `onDetect` function. Set `if (true)` or `if (false)` to simulate validation of the QR code content and either pause the view or show tracker and borders in red.
Any ideas to prevent component to fully rerender (at least the to not call again the part asking for camera permissions) ?

**EDIT**
As a temporary fix, it seems that the prop `:camera="{}"` is getting everything wrong. Indeed, if I get rid of this, I do no longer observe the issue. However, it should be good to understand deeply why is it doing so and fix it.

**Comment by gruhn** [comment]
In contrast to Chrome, Firefox asks the user for permission every time a camera stream is requested. This happens [when the component is mounted](https://github.com/gruhn/vue-qrcode-reader/blob/bf5c446ad5b7ee947982c38719ed26ece90d9314/src/components/QrcodeReader.vue#L189) or when the camera props is modified. At least this is how it should be. 

The final constraints object which is passed to [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) to request a camera stream, is evaluated in [a computed property called `constraints`](https://github.com/gruhn/vue-qrcode-reader/blob/bf5c446ad5b7ee947982c38719ed26ece90d9314/src/components/QrcodeReader.vue#L102). 

Now, I haven't figured out why yet but it looks like `constraints` is re-evaluated when `paused` changes although there is no dependency between those properties. This causes a new stream to be requested not only in Firefox but also in Chrome. Of course in Chrome one doesn't notice really.

Maybe this also correlates with #68

**Comment by gruhn** [comment]
Ok, should be fixed in [v1.3.3](https://github.com/gruhn/vue-qrcode-reader/releases/tag/v1.3.3). Reopen if the problem persists.
