### ISSUE TITLE
Can't mount <qrcode-reader/> component

### ISSUE THREAD

**Issue by sayhicoelho** [gruhn/vue-qrcode-reader#70]
Recently I've successful installed and ran the vue-qrcode-reader in a legacy project. But now I'm in a new Vue project that needs the same feature: QR Code reader. The vue-qrcode-reader is awesome! I'm trying to execute, but it doesn't run anymore. I don't know why.

When I try to mount the component, I'm getting the error "Failed to mount component: template or render function not defined.".

Why is this happening? Is this a problem with Vue, or is it a problem with the project itself?

### Vue version
^2.5.2

### vue-qrcode-reader version
^1.2.2

### Browser
Chrome 70.0.3538.67 64 bits

**Comment by gruhn** [comment]
Maybe there is something with the way you import the component... Can you show me your implementation?

**Comment by sayhicoelho** [comment]
Thank you for reply, @gruhn.

I just published the code here https://pastebin.com/ZCrTNCKV.

**Comment by sayhicoelho** [comment]
The issue was solved by loading the plugin globally.

This doesn't worked for me:

```html
<template>
...
</template>

<script>
import { QrcodeReader } from 'vue-qrcode-reader'

export default {
  components: { QrcodeReader },
  ...
}
</script>
```

This works fine:

```js
import Vue from 'vue'
import VueQrcodeReader from 'vue-qrcode-reader'

Vue.use(VueQrcodeReader)
...
```
