### ISSUE TITLE
1.2.3 - @decode receives `undefined` instead of string

### ISSUE THREAD

**Issue by frandiox** [gruhn/vue-qrcode-reader#75]
First of all, thanks for this library!

It was working fine in 1.2.2 but now in 1.2.3 the `@decode` event gets `undefined` instead of the string value. I've tried with both complex and very simple QR codes and it is always undefined. It tracks the QR code well (I can see the red window tracking it). Why could it be? 🤔

**Comment by gruhn** [comment]
Sorry, totally my bad. Should be fixed now.
