### ISSUE TITLE
Camera doesn't work in iOS PWA mode

### ISSUE THREAD

**Issue by phong-et** [gruhn/vue-qrcode-reader#76]
Hi, I deployed my web app to heroku host
Camera load successfully on browser and pwa of android device, and it still works on iOS browser(Safari). 
When I used iOS PWA mode (select "Add to Home Screen" Safari's right menu item) but it can't load camera correctly. I installed latest version (v1.3.0). 
Have you ever met this issue ? 
Thanks for your reading :)

**Comment by acrollet** [comment]
@phong-et this is unfortunately a limitation of Safari - WebRTC video is only allowed in Safari.

cf. https://github.com/webrtc/samples/issues/933

**Comment by phong-et** [comment]
> @phong-et this is unfortunately a limitation of Safari - WebRTC video is only allowed in Safari.
> 
> cf. [webrtc/samples#933](https://github.com/webrtc/samples/issues/933)
Thank you !
Maybe we will wait iOS upgrade new version or force app switch to Safari browser to use camera

**Comment by gruhn** [comment]
@phong-et Arguably, user experience is not so good but note that the [QrcodeCapture](https://github.com/gruhn/vue-qrcode-reader/wiki/QrcodeCapture) component also starts the camera on iOS 11+

**Comment by phong-et** [comment]
> This issue has been resolved in version 1.3
Did you confuse ? I saw you also commented this message in issue #78

**Comment by phong-et** [comment]
> 🎉 This issue has been resolved in version 1.3.1 🎉
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/vue-qrcode-reader)
> * [GitHub release](https://github.com/gruhn/vue-qrcode-reader/releases/tag/v1.3.1)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

Did you confuse ? I saw you also commented this message in issue #78

**Comment by gruhn** [comment]
Ah dammit! Those comments are automatically posted by semantic-release when I close issues in commit messages. I referenced this issue in a commit where I updated the README. Sorry, this is not resolved :confused:

**Comment by a-rodin** [comment]
Is it possible to use HTML Media Capture instead of getUserMedia? It seems to be working even in PWA mode.

**Comment by gruhn** [comment]
@a-rodin Yes. However, it only works in iOS 11.3+. See:

https://stackoverflow.com/questions/46228218/how-to-access-camera-on-ios11-home-screen-web-app

**Comment by phlegx** [comment]
@gruhn can you confirm, that it works on iOS 11.3+ in PWA mode?

**Comment by gruhn** [comment]
> @gruhn can you confirm, that it works on iOS 11.3+ in PWA mode?

This only concerns `QrcodeCapture`. `QrcodeStream` is still not supported, sadly.

**Comment by GDanielRG** [comment]
Any news on this? I am also trying to use my PWA on ios and the scanner doesnt appears there, only on safari.

**Comment by phong-et** [comment]
> Any news on this? I am also trying to use my PWA on ios and the scanner doesnt appears there, only on safari.

I think Apple don't care about PWA, if PWA is so smooth then the App Store will decrease revenue.
Viruscona is so engough challenge for them in new year.
My honest adivce for you is either finding another solution(capture image then read it to get data)  or changing PWA to another platform

**Comment by NoahStahl** [comment]
I'm new to this and developing against a 7th gen iPad with iOS 13.4, and it seems to work well including in standalone/PWA mode. Perhaps this issue was recently addressed? I read this before trying and was worried it would block, but appears not to be the case. Can anyone else confirm the above applies with iOS Safari 13.4 -- it would be helpful to know if there is still something I'm missing or if I just lucked out on timing?

The only issue I see is a hang/black camera view when the app goes to background then comes back again via tapping home then the app icon.

**Comment by phong-et** [comment]
Oh, good new, I left PWA project because some its features aren't smooth
with iOS device before, I also changed to android phone, hope anyone will
test again this issue.

**Comment by phong-et** [comment]
> I'm new to this and developing against a 7th gen iPad with iOS 13.4, and it seems to work well including in standalone/PWA mode. Perhaps this issue was recently addressed? I read this before trying and was worried it would block, but appears not to be the case. Can anyone else confirm the above applies with iOS Safari 13.4 -- it would be helpful to know if there is still something I'm missing or if I just lucked out on timing?
> 
> The only issue I see is a hang/black camera view when the app goes to background then comes back again via tapping home then the app icon.

Oh, good new, I left PWA project because some its features aren't smooth with iOS device before, I also changed to android phone, hope anyone will test again this issue.

**Comment by gruhn** [comment]
@NoahStahl you're right! They seem to have fixed it in iOS 13.4:

https://bugs.webkit.org/show_bug.cgi?id=185448#c84
