### ISSUE TITLE
Error (Seems like this page is served in non-secure context (HTTPS, localhost or file://))

### ISSUE THREAD

**Issue by darrenlimch** [gruhn/vue-qrcode-reader#77]
Hi Dev
I getting this error on while i try to host and run on laravel (Seems like this page is served in non-secure context (HTTPS, localhost or file://)
I'm using free DDNS services...May i know how to resolve this issues?

**Comment by gruhn** [comment]
Browsers like Chrome and Safari won't allow access to the users camera unless the page is served over HTTPS.

Please review the browser support section in this projects README. You'll find help in the issues referenced there.
