### ISSUE TITLE
Closing camera stream

### ISSUE THREAD

**Issue by ItsANameToo** [gruhn/vue-qrcode-reader#80]
Is there a way to manually close the camera stream? Right now we have an issue where the camera will stay on when you start the component that uses `<qrcode-stream>` and close it before the camera is loaded. It will then turn on after the component has been closed and will stay on until the application is reloaded. It would be great to have a way to cancel / shutdown the stream when the component is unmounted or something, or to manually close any open streams.

**Comment by gruhn** [comment]
This shouldn't be happening. The stream should always be closed when the component is destroyed. So there shouldn't be a need to manually close remaining streams.

Note, that you can however close the stream manually WHILE the component is mounted using the camera prop. Maybe a temporary workaround could look somewhat like this:

```js
this.camera = false

await this.$nextTick()

// Destroy QrcodeStream
```

This is fairly abstract. I'll come up with more concrete examples while investigating this.

In the meantime, you might also want to check out the [Validation (hard)](https://gruhn.github.io/vue-qrcode-reader/demos/ValidateHard.html) demo.

**Comment by ItsANameToo** [comment]
Thanks, I'll take a look into the demo you linked and the workaround. If you need any additional information to reproduce it, let me know!

**Comment by ItsANameToo** [comment]
I've added the `this.camera = false` line to a `beforeDestroy()` function in the component, but it still stays on if you close it too quickly. The camera constraints are set in `mounted()` and if I add `setTimeout(() => { this.camera = false }, 2000)` it turns the camera off after 2 seconds as expected. It seems that the component gets destroyed before the actual camera stream is initialized and setting camera to `false` is not able to stop the stream being initialized.

Also; if the camera did not get turned off and you mount the component again, it will immediately show the camera feed but is unable to turn it off either when you properly close the component.

**Comment by gruhn** [comment]
I think this is fixed now. I chose the lazy solution though.

**Comment by ItsANameToo** [comment]
Thanks, will test that in a bit. For the time being I had disabled closing the component until the stream was properly loaded, which also solved the issue as you could no longer immediately close it 😬
