### ISSUE TITLE
Character limit

### ISSUE THREAD

**Issue by frandiox** [gruhn/vue-qrcode-reader#81]
Hi!

I'm maybe hitting some kind of character limit. My QR code encodes some info in JSON format (stringified). It works well up to about 900 characters in the JSON, but now I tried with about 1000 and it cannot read the QR code anymore. I tried to make the QR code bigger in the screen with no luck. It doesn't trigger decode event at all and it doesn't show the red square on screen either.

The QR code seems valid because I can read it with apps like QR Droid. Are you aware of any size limit? Thanks!

Tried with 1.3.1, 1.3.0 and 1.2.2

**Comment by gruhn** [comment]
Thanks for reporting this. I didn't know that. I'll try to reproduce this soon.

I'm pretty sure though that this is a limitation of jsQR - the library we are using to actually decode images.

https://github.com/cozmo/jsQR

We can open an issue at their repository but I'm not confident that this will be fixed anytime soon. We could migrate to a different library but as far as I know, jsQR is still one of the best options out there.

**Comment by frandiox** [comment]
@gruhn 	Hi! Could you reproduce this issue at the end? Should I open an issue in the other library and see if we get a reply?

**Comment by frandiox** [comment]
Looks like this is based on jsQR: https://github.com/nimiq/qr-scanner

**Comment by gruhn** [comment]
After a recent dependency update I tried again to scan a QR code encoding 1500+ characters of non-repeating text. It works but its super slow and the QR code is massive. Performance is a general problem so I consider this closed.

![download](https://user-images.githubusercontent.com/26570572/90274958-ca924900-de61-11ea-961f-71e00b9f5fb9.png)
