### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getContext' of undefined when routing to another page

### ISSUE THREAD

**Issue by rtarnec** [gruhn/vue-qrcode-reader#85]
Hi,
In chrome console I am getting the following error when I navigate away from a component containing a qrcode reader 

```
webpack-internal:///47:1 Uncaught TypeError: Cannot read property 'getContext' of undefined
    at VueComponent.repaintTrackingLayer (webpack-internal:///47:1)
    at VueComponent.onLocate (webpack-internal:///47:1)
    at Worker.i.onmessage (webpack-internal:///47:1)
repaintTrackingLayer @ webpack-internal:///47:1
onLocate @ webpack-internal:///47:1
i.onmessage @ webpack-internal:///47:1
```

More precisely:
1/ The qrcode reader is declared in a QrReader.vue component which contains a `<qrcode-stream @init="onInit" @decode="onDecode"></qrcode-stream>` tag, as shown in the doc.
2/ This component is included in a main component and is wrapped in a `v-show` directive, as follows: 
```
              <div v-show="showQrCodeReader">
                <qr-reader/>
              </div>
```
As soon as the qr code reader detects a value, it is hidden (`showQrCodeReader` is set to false)
3/ When I click on a link that route to the application home page I get the error shown above. 

Note that:

- this only happens when I scan a QR Code. If I don't scan anything (showQrCodeReader is never set to false) and navigate away, no problem.

- If I remove the `v-show` directive, no problem neither. 

- If I change the `v-show` directive to a `v-if one`, the error occurs **as soon as** the component is destroyed (i.e. as soon as `showQrCodeReader` is set to false, no need to navigate away) 

- No error is displayed when using Firefox.

Thanks in advance

**Comment by gruhn** [comment]
Thanks for providing so many details in advance, I'll look into it

**Comment by antonioribeiro** [comment]
Also experiencing after reading a QRCode

![image](https://user-images.githubusercontent.com/3182864/50232344-dd583000-0397-11e9-9821-62abfb0523c7.png)

Count is 242 but it keeps raising the exception indefinitely.

**Comment by konstantincole** [comment]
clearTrackingLayer is called over and over after QR scan success. Calling .getContext is failing when you hide element via v-show or v-if, these should be a event / callback to stop streaming.

**Comment by antonioribeiro** [comment]
This is killing Chrome on desktop, browser is becoming sluggish and terminating abnormally, so we are having to manually reload it from time to time.

**Comment by martindevnow** [comment]
I have this same issue with `v-if` but not with `v-show`

**Comment by gruhn** [comment]
Sorry, guys. I still had not enough time to fix this. I think this issue has been introduced in v1.3.3 though so you might be better off downgrading to v1.3.2

**Comment by ghostvar** [comment]
In my case, that happen if you try to destroy the component, like using v-if or updating routes,
and seem beforeDestroy hooks not work correctly.

but, that can be handled by using [pause props](https://gruhn.github.io/vue-qrcode-reader/api/QrcodeStream.html#paused) after onDecode() event was run.

example in my code: 
![image](https://user-images.githubusercontent.com/26864484/51303822-194ee580-1a69-11e9-92c6-8da1b50cd5cb.png)

I hope that can be help you.

**Comment by gruhn** [comment]
Just released v1.3.4

@rtarnec @ghostvar @martindevnow @antonioribeiro @konstantincole 

please check if this is solving the issue for you.

**Comment by saikrishna15** [comment]
Im using this v1.3.4, I see the fix is not working consistently, after qr code reading, throws this error , if we are reading more than once.

**Comment by gruhn** [comment]
@saikrishna15 can you be more specific? What are you doing exactly? 

You scan the first QR code. Than you just scan another one. Than you get the error? Do you modify any other props like `camera`, `paused`, `v-show`, `v-if` in between?

**Comment by saikrishna15** [comment]
Its inconsistent. I can't reporduce it always.

**Comment by frandiox** [comment]
I've been getting this error on Sentry for a while as well. Example code:

```vue
<VBtn
  v-if="showQrReader === false"
  @click="showQrReader = true"
>
  Scan QR Code
</VBtn>

<QrcodeReader
  v-else
  :paused="paused"
  @init="onInit"
  @decode="onDecode"
/>
```

It happens right after navigation 🤔

**Comment by pjbalt** [comment]
I was getting this memory leak as well sporadically in **v1.4.0** - would show up after route changes.  If your application can handle `location.reload()` you can issue that after route changes to wipe out the memory leak.

However for me this wasn't ideal, the **downgrade to v1.3.2 fixes the issue**.

**Comment by Damanii** [comment]
I am currently getting it in **v1.4.0**  when I use `:paused` but when using `v-if` instead, once the component is unloaded I dont get the error. Haven't noticed the issue except for this case since upgrading to **v1.4.0**.

**Comment by oimou** [comment]
It seems that `<qrcode-reader>`, which will apparently be removed in 2.0.0, still has this issue, but `<qrcode-stream>` has been fixed.
