### ISSUE TITLE
DOMException Error

### ISSUE THREAD

**Issue by MehboobAshraf** [gruhn/vue-qrcode-reader#87]
In Nuxt project, camera is working fine on localhost but on live website it is giving DOMException error.

**Comment by MehboobAshraf** [comment]
@gruhn issue is not with nuxt actually, I tried it with different browsers and it is working fine on mozilla, actually my application is serving on Http and because of this many browsers are not allowing to open the camera.

**Comment by MehboobAshraf** [comment]
There is no issue with nuxt, I think browser is not allowing to access camera for application which is running over HTTP

**Comment by gruhn** [comment]
This kind of exception should be caught though. If you listen to the `init` event, you should get a [NotSupportedError](https://gruhn.github.io/vue-qrcode-reader/api/QrcodeStream.html#events).

**Comment by gruhn** [comment]
Turns out NotSupportedError IS a DOMException

https://developer.mozilla.org/en-US/docs/Web/API/DOMException

so I assume this is working as intended.

**Comment by AlbatiQue** [comment]
@MehboobAshraf Can you share how you integrated with nuxt?

**Comment by delrueba** [comment]
> @MehboobAshraf Can you share how you integrated with nuxt?

You have to import your component differently:
`  components: {
    scanner: () => import('@/components/client-only/Scanner')
  }`
