### ISSUE TITLE
SOLUTION HERE!: Camera access in Chrome mobile === HTTPS needed  

### ISSUE THREAD

**Issue by DespertaWeb** [gruhn/vue-qrcode-reader#88]
Definetely you should make aware the dev's that **in Chrome mobile the camera is not accessible unless you create an external url with https protocol.**

I wasted one morning just for that.

- SOLUTION 1 : Create an external url with https with [NGROK.io](serveo.net): 
`ssh -R 80:localhost:8080 serveo.net`

- SOLUTION 2 :  Create an external url with https with [NGROK.io](ngrok.io)
https://www.youtube.com/watch?v=oy13mDsXC4s

Please, please, make sure this is noted in your documentation

**Comment by gruhn** [comment]
I think the best way to deal with this is via [Chrome Remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/) which also let's you forward localhost to your mobile device.

This solution was mentioned in #38 which is already linked in the READMEs _Browser Support_ section.

But it makes sense to make this solution more accessible. I'll update the README.
