### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by rajagopalx** [gruhn/vue-qrcode-reader#89]
In Troubleshooting Section, 

Under,

I can't test my app on my mobile device since I'm running a dev server on localhost but it's not served with HTTPS.

Pls add the below point.

Host your app through [netlify ](https://www.netlify.com/)or [firebase ](https://firebase.google.com/)at free cost. It comes with HTTPS. 

(I personally prefer netlify because of automatic deployment, automatic branch wise deployment and many more features when compared to firebase)

**Comment by gruhn** [comment]
Sure, open a Pull Request with your improvements :blush:
