### ISSUE TITLE
it not work in wkwebview

### ISSUE THREAD

**Issue by airkingZy** [gruhn/vue-qrcode-reader#91]
in ios,can work in safari,but i make a app,app have a wkwebview,it dosen't work in wkwebview.
because is a wkwebview?
i see you say it not work in chrome in ios.beacuse chrome in ios also made by wkwebview？
thanks，have a good day

**Comment by gruhn** [comment]
Unfortunately it won't work in WKWebView. And yes that's exactly the reason why Chrome for iOS is not supported. See:

http://www.openradar.me/33571214

You could fallback to the QrcodeCapture component though.

**Comment by airkingZy** [comment]
> Unfortunately it won't work in WKWebView. And yes that's exactly the reason why Chrome for iOS is not supported. See:
> 
> http://www.openradar.me/33571214
> 
> You could fallback to the QrcodeCapture component though.

thanks
