### ISSUE TITLE
QR reader choosing IR camera over regular camera

### ISSUE THREAD

**Issue by ItsANameToo** [gruhn/vue-qrcode-reader#92]
It seems that the infrared camera that is available on some laptops get chosen as default camera to scan the QR code with, but this doesn't produce usable results (see for example this post: https://blogs.gnome.org/jamesh/2017/10/22/thinkpad-infrared-camera/). Would it be possible to have a list returned of the available cameras for the chosen `facingMode`? That way a user might can choose a different camera if it happens to make use of the IR one. 

Maybe there's a better way to default to the right camera if there's more than one, but I don't know 🤷‍♂️

**Comment by gruhn** [comment]
Thanks for reporting this. I'm really not sure how to deal with this issue. For now you might be able to use:

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices

to get a list of cameras (videoinputs), filter by `label` and pass the right `deviceId` via the camera-prop. Somewhat like this: 


```
:camera="{ deviceId: ... }"
```

**Comment by gruhn** [comment]
I assume this is related to #179 

Reopen if the issue still occurs.
