### ISSUE TITLE
Props for input field

### ISSUE THREAD

**Issue by gdomingu** [gruhn/vue-qrcode-reader#93]
Hi there, thank you for all of your work on this. I was wondering if there is a way to pass in props to the input in the component from the parent? For example:
```
<qrcode-capture @decode="onDecode" :class="form-control-file" ref="imageSelector"/>
```
Would render:

```
<input 
  data-v-0b3f49e4=""
  type="file" 
  name="image" 
  accept="image/*" 
  capture="environment" 
  multiple="multiple" 
  class="form-control-file" 
  ref="imageSelector"
>
```
Thank you.

**Comment by gruhn** [comment]
Thank you too :)

The `input` field is the root element of the component so any prop/attribute that is not explicitly defined should end up on the there. See:

https://vuejs.org/v2/guide/components-props.html#Non-Prop-Attributes

Is that answering your question?

**Comment by gdomingu** [comment]
Oh wow that is is very handy. Thank you!
