### ISSUE TITLE
Stop/Restart scanner

### ISSUE THREAD

**Issue by BadiR3d** [gruhn/vue-qrcode-reader#96]
This component has been of great use to me, I've implemented my own qr scanner, but just struggling with stopping and restarting the sccanner, so I was wandering if there is a way to do that using code? I've tried using this.$destroy(), but this doesn't solve my problem, as I can't mount it again after using $destroy()... any assistance would be appreciated.

**Comment by gruhn** [comment]
What exactly are you going for with that? 

You can set `:camera="false"` to kill the camera stream, stop scanning and basically reset everything. The component still shows the last received camera frame though.

To get rid of that too and actually destroy the component, use `v-if`. Vue destroys all components inside a `v-if="false"` element and recreates them when you set it to `true` again. 

```html
<qrcode-stream v-if="false"></qrcode-stream>
```
This is also perfectly fine:

```html
<div v-if="false">
  <qrcode-stream></qrcode-stream>
</div>
```

**Comment by ziltonvasconcelos** [comment]
:camera="false" works only after decode. How can I stop camera stream without decode?

**Comment by BadiR3d** [comment]
I ended up using the v-if route... works great...

**Comment by gruhn** [comment]
@ziltonvasconcelos what are you trying to do? Do you want to mount the component without starting the camera right away?

**Comment by ziltonvasconcelos** [comment]
Solved with v-if, thanks!

Em seg, 4 de fev de 2019 11:03, Niklas Gruhn <notifications@github.com
escreveu:
